### ISSUE TITLE
"syntaxic sugar" for some fused glyphs

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1013]
Solesmes uses the glyph `(go@hd~)` (a torculus liquescens with first note being an oriscus). The only way to get it now is through fusion, but it would be best if `(gohd~)` had the same output (using fusion behind the scenes). Maybe the same principle could be applied to the `pes stratus` of https://github.com/gregorio-project/gregorio/issues/898 ? Anyway, this is not a top priority.

**Comment by eroux** [comment]
Also, it seems Solesmes is using pes stratus too, so it will certainly be more common in the future, it would be best if `(goho)` was working too. We'll see how things go with 4.2, but it would be wonderful to have that in 4.2 too if possible... is it a lot of work or is it more reasonable than #898 ?

**Comment by henryso** [comment]
#898 is an overhaul of the oriscus glyphs.  Currently, the reverse-ness of an oriscus is *relative* to whether the following note is above or below in *some* of the cases.  My intent is to remove this relative-ness for consistency.  So instead of "oriscus" and "oriscus reversus", there will simply be "ascending oriscus" and "descending oriscus" (and, of course, "scapus" varieties).

The current glyphs will be rationalized to this naming and the missing glyphs will be added.  For example, `FlexusOriscusTwoNothing` is currently only available with the descending oriscus, however its shape is what we currently call an "oriscus reversus".  Contrast that to "PesQuassusTwoNothing", whose oriscus is the "non-reversus" oriscus.  Sacrilege aside, Two figures are missing, a "flexus oriscus" with an "ascending oriscus" and a "pes quassus" with a "descending oriscus".  So I intend to come up with some sort of naming convention that will make all this consistent.

That is not a change to take lightly, and will probably take me a week or two to implement (given I work during the day).

Compared to that, this change (#1013, that is) is simply one of electing to fuse a glyph when certain branches of the state machine are hit, and is much less complex.

**Comment by henryso** [comment]
Should I draw pes stratus in the font (it would add 10 glyphs; we have about 860 more after I add the missing glyphs for #868 and #972) or just depend on fusion for this figure?

**Comment by eroux** [comment]
Well, 10 glyphs is almost nothing, let's do it!

**Comment by henryso** [comment]
Question about the naming.  It seems to be that a "pes stratus" is a pes followed by an oriscus.  Is "pes stratus" the correct name for a "pes" using oriscus for both notes?

**Comment by eroux** [comment]
Oh... I have 0 clue about that... if it's a "Nocturnale Romanum-ism", maybe we can call it `NRPesStratus`? I'll ask my contacts about that, but you can use this as a temporary name I think...

**Comment by henryso** [comment]
While you're asking, can you check if Solesmes's usage of "pes stratus" means the pes-followed-by-oriscus or the oriscus-followed-by-oriscus?  If not the latter, I think I would opt to just use fusion for these shapes.

**Comment by eroux** [comment]
Sure!

**Comment by eroux** [comment]
So, for Solesmes, a _pes stratus_ is a punctum fused with an oriscus above, no queue (the form in the NR doesn't correspond very well to the adiastematic shape apparently), so `(fhO)` is a pes stratus for them. So yes, fusion for the NR form is fine, sorry for mixing everything!

**Comment by henryso** [comment]
Given that clarification, since the NR form will not come into more common use (and moreso doesn't conform to a nondiastematic shape), I will leave out the "syntactic sugar" for it.  It means less to maintain (and fewer potential bugs to fix).

**Comment by eroux** [comment]
sure, sounds good
