### ISSUE TITLE
UPGRADE.md and empty syllables

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#1023]
Since empty syllables are now bar syllables, perhaps something should be noted in UPGRADE.md describing this (and the fix if you don't like the current result).

**Comment by eroux** [comment]
Indeed. Also, maybe empty syllables could raise warnings? There's no defined behavior for that and the output may change from version to version...

**Comment by henryso** [comment]
Do we still want empty syllables to raise warnings?  That's not done yet.

**Comment by eroux** [comment]
I think it would be a good idea yes... but we can leave it for 4.2.

**Comment by henryso** [comment]
Ok, reopening this issue then.

**Comment by henryso** [comment]
I think we need to try to get things printed to stderr from gregorio to print when doing auto-compiles from Lua.

**Comment by henryso** [comment]
As I start coding this and looking at the tests, I find that we are using a no-note syllable expressly for some cases of #767.  We even emit a special `\GreNoNoteSyllable` in this case.  Is that really undefined behavior?  Aren't we, by doing this, defining the behavior?  Or am I missing something?

**Comment by rpspringuel** [comment]
I don't think that the no note syllable is undefined.  At least as I thought about it in implementing the new spacing algorithm, the no note syllable is a type of bar line (i.e. should use `\GreBarSyllable`), call it a divisio nihil.  This was a deliberate choice in order to account for some of what I was seeing in the examples in #767.

The issue is that this is different from the old spacing algorithm, where the no note syllable was treated as a type of note (i.e. used `\GreSyllable`), call it a punctum invisum.  IIRC, this old behavior wasn't necessarily anything intentional, just the result of the fact that gregorio made the simple assumption that whatever wasn't a bar syllable, was a note syllable.  One could, therefore, consider this behavior to have been undefined, though it did operate in a predictable fashion.

The use of `\GreNoNoteSyllable` is the intermediary which allows the code to negotiate between these two different ways of treating the syllable.  It is not meant to imply that no-note syllables are their own type, but rather allows them to be treated as one type (punctum invisum) in the old algorithm and as something else (divisio nihil) in the new.

Further, this aliasing does not have to be tied to the old and new algorithms, though our user function changes them automatically.  With a simple `\let` statement, the end user could switch how a no-note syllable is treated without changing the bar spacing algorithm.

To that end, I don't think errors or warnings are needed here, but rather documentation explaining how things are defined and how the user can change them.

**Comment by henryso** [comment]
I agree with the above, so I propose we can close this with no further action.

**Comment by eroux** [comment]
ok!
