### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#103]
Currently, gregorio documentation is quite a mess, and there is no obvious way of fixing it. This issue aims at starting a discussion about how to improve Gregorio documentation, taking all aspects into account. Maybe a little overview of what we currently have:

* an incomplete, outdated and unpractical website
* an incoming documentation PDF for GregorioTeX public macros

Let's first give ideas about the ideal result, then, in a second time, propose solutions for what we want. Here are a few documentation ideas I like (realistic or not, sometimes contradictory, but that's a brainstorming):

 * [literate programming)(http://en.wikipedia.org/wiki/Literate_programming) (which was invented by Knuth, the TeX engine is done this way), usually (poorly) done in TeX with [.dtx files](http://www.tex.ac.uk/cgi-bin/texfaq2html?label=dtx) to give a pdf. Pros: elegant, Cons: very few tools, pdf output only
 * annotations in source code for public macros, similar to what is done with [doxygen](http://www.stack.nl/~dimitri/doxygen/) or [jsdoc](http://usejsdoc.org/), Pros: practical, Cons: doesn't really exist for TeX (AFAIK)
 * Possibility to have snippets of examples in the doc, with the compiled version easily accessible. The best would be to have a way for the user to modify the examples, a la [JSfiddle](http://jsfiddle.net/), but that's not for tomorrow...
 * dynamical documentation on a website, I think the best example is [angularJS documentation](https://docs.angularjs.org/api). For me it's the best possible example: it's autogenerated from sources, it has all different versions accessible, it can contain changelog, migration rules, it contains examples, etc. But it would require quite a lot of development to reach such a level...

What do you think?

**Comment by rpspringuel** [comment]
From the usage side, documentation needs to serve two purposes, in my opinion. The first is to tell the end user how to use the program. This would include (in no particular order) usage examples, upgrade instructions, feature lists, basic tutorials, and installation instructions.

The second purpose is to tell the developers what the program does and how it does it.  This includes a full list of functions with a description of what they do and their arguments, a list of variables and what they stand for, and any overarching guidelines that the code follows (such as naming conventions).

Ideally the two purposes are linked, in both a literal and figurative sense.  For example, descriptions of features for users or examples of how to do something should point to the explanation of how that is accomplished at the code level.  Likewise variable definitions should indicate which features make use of them.  This way an interested party can move seamlessly back and forth between the two to find all the information they need for their particular purpose, but at the same time the person who just wants the simple answer isn't overwhelmed by a bunch of technical details. 

Admittedly this is a tall order and I have never seen a set of documentation that fully lived up to it.  Maintaining this sort of documentation is a chore. 

Which brings me to the other side of the coin: the production side.  Ideally documentation should be easy to produce and maintain.  Changes should only need to be made once and dependencies clear so that updates can be made quickly, easily, and completely.  Furthermore, the more naturally documentation updates can be integrated into the normal development cycle, the more likely it is to get done.  At the same time, documentation requirements shouldn't get in the way of experimentation or the code will stagnate because changes are too much work.

I'm out of time for now, but there's the start of my thoughts.

**Comment by eroux** [comment]
I tend to disagree on the part where you say there should be documentation aimed at developers... In an ideal world where documentation is fun and easy to make, this might be possible, but we just don't live in this world. And I've honestly never seen any software with a full documentation for developers... There are comments in the code, of course, but someone wanting to modify Gregorio should read the code, the comments, make efforts to understand it, ask questions, etc. You all did, I don't believe there is any other viable option here. If the goal is to ease access to the code, I don't believe a full developer documentation is the way to go, it would be more rewriting everything in a script language (python, ruby, whatever), remove outdated parts (gregorioxml, opustex), clean everything, and thus reduce the size of the code by around 50, this is more realistic than writing a full featured developer documentation I believe... Also, there are techniques to ease the code access that have not been used enough (by me): make variable and function names significant and easy to understand, write clean code, etc. But TeX is not easy for this...

**Comment by rpspringuel** [comment]
I was describing what I consider to be the ideal, and as I indicated I've never seen documentation that lived up to it.  The most common failure is in the developer documentation which, as you indicated, usually ends up being in the code in the form of comments, where it exists at all.  If the code is well written, this can be sufficient, as some one who knows the coding language can read the code itself for further details.  I have seen, however, some terrible examples of spaghetti code which took hours to parse, even when they were commented (not saying there is anything like that here, just that I have seen such code).

Of course, well written code and comments doesn't help with navigation, but the slack there can usually be taken up by a good editor that allows code folding and jumping to various functions.  (Which reminds me, I need to look into finding just such an editor for TeX.  My usual editor, TeXShop, doesn't have these features.)

I do agree, however, that cleaning up the outdated stuff should take priority over adding something new (despite working to the opposite effect as I work on implementing the naming scheme in the TeX).

Responding to the different links you posted earlier:
* While literate programing has always sounded good to me in principle, I've never seen an implementation of it that actually seemed to work for me in the way it was supposed to.  I tried learning .dtx at one point and quickly gave up because it was easier to maintain my code and a separate documentation than it was to learn the integrated system.  For me, at least, the strictures imposed by the coding language are simply too much a part of the coding process for them to be ignored in the way that the literate programming ideal seems to imply.
* I've used annotations in the code extensively in python (where it's called a docstring) and find it to be a fairly natural way of doing things once you're in the habit of doing it.  Unfortunately (as you point out) this doesn't exist for TeX.

The other two systems I'm not at all familiar with.  Browsing the websites quickly, I'd say the first, JSFiddle, is less something we should worry about, and more something the people working on Illuminare score editor (or something else like it) should do.  The angularJS documentation does look nice, and I would love it if we could have something similar, but I've basically no idea as to how to go about doing that.  I would assume, since you say it's extracted from the source, that it starts with some sort of docstring for each function, but given that docstrings don't work in TeX, I don't know how we'd do that.

**Comment by eroux** [comment]
Quoting: `I have seen, however, some terrible examples of spaghetti code which took hours to parse, even when they were commented (not saying there is anything like that here, just that I have seen such code).`. Well, you should, there definitely is a lot of spaghetti code here, sometimes I'm so ashamed when I look at a few C files... they are just terrible. But Gregorio was my first software experience, and one of the main things it brought me is the determination not to do that again!

For `dtx` files, I agree, this is more an obstacle than a help.

About annotations, basically it would be very simple to do... It doesn't exist, but that doesn't mean we can't invent it! A few conventions would be enough, for instance if you take a look at [jsdoc](http://usejsdoc.org/), the description of the tag can is quite short (though there are a lot of tags). Of course, TeX is a very particular language, but I'm sure we can come up with something. For instance

    %%
    % @name  \greglyph
    % type macro
    % @scope generated
    % @requires \gre@temp the value of whatever
    % @sets \grefirstglyph to the value of whatever
    % @arg1 the first argument is whatever
    % @calledin \gresyllable

etc. Of course that's just a first draft, but it could greatly improve the readability of the code, and it could be parsed to give a good documentation for developpers, a kind of API doc, with links to relevant elements, etc. But that's just a thought, it might be difficult and also requires some investment... The advantage is that it could help on user doc and on API (here I'm referring to the functions used in a generated `.gtex` file).

**Comment by rpspringuel** [comment]
Something like that could certainly work.  TeX won't care if everything is commented out and it would be fairly simply to write a parser in python or what-not that could retrieve and format these blocks for use elsewhere.

Another trick is to wrap the code in `\iffalse ... \fi`.  Anything within this block will always be ignored and we don't have to worry about commenting every line.  This is the one trick I learned from dtx files that I actually like.

Other points:
1. It would be better to use both an opening and closing line and make them something fairly unique.  This will make them easier for the parser to find.  Perhaps something like `%% begin docstring %%` and `%% end docstring %%` or `\iffalse % docstring` and `\fi % docstring`.
2. Instead of `@calledin` it would be far easier to show the links in the other direction, i.e. `@calls`.  If I'm writing a new function that calls another function, having to go find and modify that other function's docs to indicate that it's called by my new function is something of a hassle.  On the other hand, it's pretty trivial to add to the docstring of the function I'm working on.  After all I'm already in the right place.  As long as the link between two functions is documented, a parser should be able to construct the links.  Indeed, if we really want a `@calledin` field (which is admittedly useful), then it could be autofilled by a script from the `@calls` fields.

On the issue of investment, anything implemented this late in the process is going to require some substantial upfront investment to get it off the ground simply because there is so much undocumented code.

**Comment by henryso** [comment]
Is this documentation for developers of GregorioTeX, with a separate user manual for people who only care about macros which affect their Gregorio output, or will the documentation for both users and developers be intermixed?  If the latter, perhaps the "docstring" identifier can indicate whether the documentation is for developers or users.  This way you can extract and generate documentation for both parties based on need.

Have you considered something like Markdown/reStructuredText for the formatting?  Just an idea.

Alternately, how about doxygen?  I have no idea how to do this or even if it's possible, but maybe it can adapted to parse the tex files for magic comments.

**Comment by rpspringuel** [comment]
I think it's probably a bit intermixed.

As I see it, within GregorioTeX we have three levels of commands:
1. The internal commands: These are the commands that appear in the package files, but not in documents or `gtex` files.  They're used by GregorioTeX to do different tasks as part of producing the output, but don't really stand on their own.  These commands only need documentation for developers (in my texrenaming branch these are the commands I'm prefixing with `\gre@`)
2. Gregorio commands: Under normal usage these commands are written by the command line tool to `gtex` files.  They basically are the TeX representation of the score content with each command standing for a particular element (usually a note-syllable pair).  Most users don't need to mess with these commands, but I've been able to accomplish some things which are impossible to represent in `gabc` by making tweaks at this level.  Documentation of these commands could be useful for advanced users (in my texrenaming branch these are the commands I'm allowing to retain the `\gre` prefix).
3. User commands: These are the commands that appear within your average user's document.  They control most of the appearance of the score and some of the more specialized content (such as commentary and annotations).  Most users would find documentation for these commands useful (in my texrenaming branch these are the commands I'm stripping prefixes from).

As a user, all I really need in the documentation is a basic description of what the command does, the correct syntax for using the command, and the list of arguments (along with what constitutes a valid input for each argument).  As a developer, I'd find all of that useful, as well as more technical things like dependencies, variable lists, etc.

Based on both of these, I'd say that for well written documentation, the User documentation is a subset of the developer docs.

Looking at doxygen, it doesn't appear to support TeX on the input side.  Not having used it before, I have no idea what sort of customizations it has available.  I do note, however, that there is a `Doxyfile` in the repository root, which implies that some one at one point thought doxygen might be useful for something in this project (though perhaps only for the command-line tool, which is written in C).

**Comment by eroux** [comment]
I like the idea of `\iffalse ... \fi`, it's cleaner that these `%` at every line... In fact `@calledin` is a bit blurish in my example, and it might not be really relevant: it meant that `\greglyph` can be called in the context of an argument of `\gresyllable`, but it's not called by `\gresyllable` directly... but this is a bit convoluted and not very relevant...

I thought about Markdown too. TeX purists would certainly be a bit shocked that something else than TeX is used for that; but for this kind of use, Markdown is appropriate and TeX is just not...

I totally agree on the three levels you exposed. I'm thinking about 3rd level as  commands of a regular TeX package, 2nd level as a kind of API, so that GregorioTeX files might be written by other softwares (not sure it's relevant, but who knows...), and also let users tweak their files if necessary. 1st level is maybe less important to document, and might not be relevant in a public documentation... but it doesn't hurt.

The Doxyfile was indeed for the C part, but was never used (at least not for a few years).

Maybe a first step would be to create a small documentation (just a .md file, or a wiki page) on what the different markups would be, and then start documenting the code with these markups when we change or proofread a macro? That won't make a documentation, but at least it's a starting point, it will greatly improve comments and make a doc possible in the future. What do you think?

**Comment by eschwab** [comment]
One downside I forsee to `\iffalse ...\fi` is that at a glance it may appear to be 'real' TeX code. Many text editors have a different fontface for comments which make them easy to see. I guess the difficulty lies in TeX not having a block comment markup.

**Comment by rpspringuel** [comment]
As much as I love TeX, going from TeX to html is not a really nice process and I can easily foresee this documentation ending up on the web if we do it right.  Markdown seems to be versatile and simple enough to make that conversion process much more feasible.

I agree that the best way to start is to decide on some starting conventions and have all changes going forward conform to them.  This will get us going enough to at least iron out the conventions and then as time permits, we can work our way through the back code.

@eschwab is right that `\iffalse ... \fi` won't stand out in a code editor the way real comments would.  Unfortunately I don't see anyway around that.

Hunting around on the web, I've found that there are other ways of creating block comments, some of which are advertised as being more robust than `\iffalse ... \fi` (which apparently has problems when another `\if...` appears inside of it).
http://tex.stackexchange.com/questions/87303/multi-line-block-comments-in-latex
http://www.ctan.org/pkg/comment
http://tex.stackexchange.com/questions/34482/contest-show-off-your-skillz-in-tex-friends-tex-sx-birthday/35017#35017

None would address @eschwab's concern and I'm not sure that they would gain us much in this context.  I think we start with the simple `\iffalse ... \fi` construction and move to one of the more robust solutions if that ends up proving problematic.

**Comment by eroux** [comment]
I think the system we have now is good enough to close this, what do you think?

**Comment by eschwab** [comment]
Yes, it seems to work for now given the limitations of documenting TeX across different medias/formats.

**Comment by rpspringuel** [comment]
We do have fairly complete documentation now, even if the convertibility between formats isn't ideal, so I think this can be closed.

**Comment by henryso** [comment]
Seems like everyone is in agreement.
