### ISSUE TITLE
900_gregorio.xml should not use the luainputenc package

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#1087]
This means removing `\usepackage[utf8]{luainputenc}`, which actually breaks the new gregorio, causing it to emit `oe? ae?` above the score.  Is there a way to check for this package and not generate the special character commands that cause problems with it, or is there a better way to encode things so that luainputenc doesn't break gregorio?

Should we also switch from times to libertine, which would also remove `\usepackage[T1]{fontenc}`?

(This bug was reported directly to me by Gerry Davila).

**Comment by rpspringuel** [comment]
Looking at the file, it appears that the use of `luainputenc` is for setting a default font which is "reasonable".  I guess the question then is what's the definition of "reasonable?"  If we simply picking a font that doesn't look out of place in a chant score, then I'd be inclined to switch to libertine in order to make things as simple as possible.

However, given the use of Times, I suspect that "reasonable" was originally defined as matching the default font that scribus uses for the rest of the document.  If that is the case, and we want to preserve that, then I'm not sure what the best way to go is.

As for testing if a package is loaded [see here.](http://tex.stackexchange.com/questions/16199/test-if-a-package-or-package-option-is-loaded)

**Comment by henryso** [comment]
I think the original intent was to translate the things in main-lualatex.tex for use with Scribus.  If you recall, the old main-lualatex.tex had these exact settings: `[utf-8]{luainputenc}`, `[T1]{fontenc}`, and `{times}`.  Nowadays, you typically want to use a Unicode font, so my opinion is (if you couldn't tell) to just switch to `{libertine}`.  Perhaps @eroux has an opinion.

On the package testing front, is there equivalent when not using LaTeX?  Perhaps we use the "safer" set of special characters if the user is not using LaTeX?

**Comment by eroux** [comment]
no inputenc, no fontenc, but fontspec and libertine would be best indeed. I don't think we have to change anything for non-LaTeX users, they usually know what they're doing and can debug easily
