### ISSUE TITLE
easing justified text at end of final line

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1110]
The following example:

```tex
\documentclass[11pt]{article} %%
\usepackage{fontspec} %%
\usepackage{gregoriotex} %%
\gresetlastline{justified}
\begin{document} %%

a\label{reprise}\par

\newcommand{\Ruber}[1]{\textit{\textcolor{gregoriocolor}{#1}}}

\gabcsnippet{%
(c4) Com(g)mu(h)ni(h)cán(h)tes,(h) et(h) di(h)em(h) sa(h)cra(h)tís(h)si(h)mum(h) ce(h)le(h)brán(h)tes,(h) (,) quo(h) U(h)ni(h)gé(h)ni(h)tus(h)  +(;) (g+) ([ev:\hfil]) <v>\Ruber{Sequitur p. \pageref{reprise}.}</v>{}()%
}%

\end{document}
```

![bug](https://cloud.githubusercontent.com/assets/60868/15318632/37bfdf80-1c27-11e6-935f-0876539b8821.png)

in which the right alignment is not correct.

**Comment by rpspringuel** [comment]
That would be a bug in the end of line shifts.  `\greseteolshifts{disable}` makes the problem disappear.  Further, giving the last "syllable" a note, also fixes the problem, so it is particular to lines which end with a `\GreNoNoteSyllable`.  It's too late tonight, but I'll look at the possibility of killing the eolshift in these cases tomorrow.

**Comment by rpspringuel** [comment]
I have a fix, but it's revealing a potential problem with the clef change discretionary.  Take a look at `/gabc-output/glyphs/clef_change`.  If you compile the gabc file, you'll see that the clef change which occurs between `test4` and `test5` puts an empty `BarSyllable` at the end of the line (after `test4`).  This prevents the lyrics in the previous syllable (i.e. `test4`) from sliding over under the end of line custos.  My fix accentuates this, pushing `test4` even further away from the end of the line.  This doesn't seem to be desirable to me, but I think the problem is with the underlying behavior: what is put in the discretionary.  Should that empty `BarSyllable` be there?  Shouldn't there be some recognition that there isn't anything to be printed and the before break argument be left blank?
