### ISSUE TITLE
build system for OSX

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#124]
The current build system for OSX is quite old and might not be the best solution. It is (more or less) documented in [macosx/README.MacPackage](macosx/README.MacPackage) (which should probably be renamed as `macosx/README.md`), but according to a few people using MAC, it's outdated. I really have no idea what is the best solution to distribute Gregorio for OSX, but maybe it could take the form of a [brew](http://brew.sh/) or [ports](https://www.macports.org/) package? Is building a `.pkg` still relevant? What do OSX users think? What do you personally use, and what do you think would be best for the beginner user?

**Comment by rpspringuel** [comment]
I've looked at creating a portsfile for Gregorio, and while I don't completely understand the process yet, I think that it should be fairly straight forward since we follow the standard configure/make/make install process and just need a post-flight script to install GregorioTeX.  Once the build and install scripts are finalized, I think it would be worth-while looking into this.

Of course, using MacPorts (or Homebrew, for that matter) still means that the user is building from source.  A `.pkg` file would be installing prebuilt software on to the user's system, and thus might be more user friendly to the less technically savy.  I've built a `.pkg` file before, but it's been a while and it wasn't as nearly complex as what needs to be done for Gregorio.  Give me some time and I'll look at what we've already got and give you my opinion on it.

**Comment by eroux** [comment]
Ok good! I'm just making sure we'll be able to make a proper complete release for 3.0 (proper source tarball, installer for windows, package for OSX, maybe debian packages, etc.), but it's no emergency

**Comment by rpspringuel** [comment]
Okay, after a gander, I'd say that what we've already got needs to be scrapped.  It's based on using PackageMaker which was deprecated in Xcode 4.6.  Of course, the last time I built a package, it was with PackageMaker (indeed, the program is still floating around on my system since I've always migrated everything when getting a new machine), so I don't know how to use the new system.

I'm willing to look into how to create a `.pkg` installer, but it's probably going to take me a while to figure it out.  For now I propose dropping what's there and replacing it with a simple README that points to the website instructions for building from source.

**Comment by eroux** [comment]
Yes, if it's complicated (which it seems), we can skip it for 3.0

**Comment by eroux** [comment]
[this thread](https://www.mail-archive.com/gregorio-users@gna.org/msg02499.html) gives no answer sadly... I'm wondering if it would be theoretically possible to compile gregorio and a package without a root access? Simply by launching a script that would install a few packages as a user, compile and package? I'm thinking about [this](http://www.macincloud.com/)...

**Comment by eroux** [comment]
Other interesting links to [cross-compile from Linux](https://github.com/crosstool-ng/crosstool-ng) and to [build a package from Linux](https://github.com/hogliux/bomutils)... what do you think? are "BOMs" what we want?

**Comment by eroux** [comment]
It seems that cross compiling from Linux is in fact illegal, compilation and running code made from Mac SDK has to take place on Apple hardware (I really dislike this company...). So even if I manage to find a SDK (it's possible to find a few on the Internet), compilation will be possible but not legal... and one of the main points that lead me to free software is not to have to do illegal things (which 95% of non-free software users do). So I'm giving up on cross-compilation... I'm trying to build the package now.

**Comment by rpspringuel** [comment]
I'm looking at the possibility of using [Packages](http://s.sudre.free.fr/Software/Packages/about.html) to create an installer.  Since it's Mac software, it would still be dependent on a Mac user to create the installer, but it is free.

**Comment by eroux** [comment]
Ok, good! I admit my preference would go to a script using pkgbuild and productbuild, (see [this tutorial](http://thegreyblog.blogspot.fr/2014/06/os-x-creating-packages-from-command_2.html) and the [second part](http://thegreyblog.blogspot.fr/2014/06/os-x-creating-packages-from-command.html)), it would allow to just rent one hour on macincloud, upload the sources, launch the script and get everything done automatically... but Packages is ok. Also, it seems to need README.html, LICENSE.html, etc. it would be good to automate the conversion if possible...

**Comment by rpspringuel** [comment]
Packages is supposed to be fully scriptable, so we should still be able to automate the build process.  The advantage is that with its GUI we should have an easier time getting things setup in the first place.

**Comment by eroux** [comment]
Sure, I forgot to mention that I really liked the fact that it has a cli in my last comment! In fact, the only thing that worries me is that it might be a burden to install in on a macincloud server without root access... or is it easy to set up if you're just a regular user? (I'm can't even be called a "beginner" on OSX, I've just never used it)

**Comment by rpspringuel** [comment]
Looking at the old README.MacPackage, I notice it recommends running configure with several options:

```./configure --enable-static-ltdl \
              --disable-shared \
              --enable-all-static \
              --disable-nls \
              --disable-dependency-tracking```

Can someone explain to me what all these options mean and how that's supposed to affect what gets installed.

**Comment by eroux** [comment]
* `static-ltdl` statically links with `/usr/lib/libltdl.a`
 * `disable-shared` and `enable-all-static` don't build `gabc`, `gregoriotex`, etc. as dynamic libraries (`.ddl` under windows, `.so` under unix), so that gregorio is more or less one executable, not a cli executable, linked with a library (libgregorio.a), with dynamic modules (gabc.so)
 * `disable-nls` disables gettext, but it's gone in 3.0 so it doesn't do much
 * `disable-dependency-tracking` [see here](http://www.gnu.org/software/automake/manual/html_node/Dependency-Tracking.html) seems to make compilation a bit faster but less precise, I don't think it should be here, but it has no incidence

The good news is that all of these will be outdated in 3.1, 3.0 will be the last with all the burden with libraries, modules, libtool, etc. I think the main difficulty here is that `src/gregorio` needs to be a more or less autonomous file, but when built without these options, it's just a libtool wrapper, and `make install` will transform it into something else (but obviously, this can't be done by a Mac package).

By the way, did I do something wrong with my files, or does `--enable-all-static` make compilation fail on `release-3.0` branch?

**Comment by rpspringuel** [comment]
Okay, so if I understand correctly, building with the first few options is the way to go as it'll lead to fewer files that have to be placed on the user's system and will be more forward compatible with where we're going.

**Comment by rpspringuel** [comment]
Oh, and for me at least, there are no problems with the `--enable-all-static` option.

**Comment by eroux** [comment]
Yes, also for the sake of simplicity... building the modules, etc. in the package would be quite difficult I believe... Also, in order to have a sane `src/gregorio` ready for install, I believe calling `make DESTDIR=/tmp install` and taking the file in `/tmp` (or whatever), it might make libtool do things in a proper way and remove the need for `--static-ltld` (but I cannot test right now).

**Comment by henryso** [comment]
`--enable-all-static` does appear to be broken in release-3.0 for me as well.  Investigating.

**Comment by eroux** [comment]
If you clone a brand new `release-3.0` branch, you'll see that it's not broken, what seems to break is to go from `refactor` to `release-3.0`

**Comment by henryso** [comment]
Yes, switching from the refactor branch left Makefiles in `src`.

**Comment by eroux** [comment]
the real bug is that `config.h` is not removed by `make clean`, I'm looking for a clean way to do this...

**Comment by eroux** [comment]
`make distclean` does, that's what should be used before switching branch I believe...

**Comment by rpspringuel** [comment]
Check out b43045f for the start of some work on this.  I haven't tested anything, but there should be enough there to give you some ideas of where I'm going.

**Comment by eroux** [comment]
BTW: when the way the package will behave will be clear, could you update [the TeXShop configuration page](http://gregorio-project.github.io/configuration-texshop.html)?

**Comment by rpspringuel** [comment]
No problem.

**Comment by rpspringuel** [comment]
Okay, I can build what appear to be working packages.  I'll try to find time later in the week to do some more thorough testing, but with the Triduum and an OS update to pull off before then, I'm not sure I will.  See b3144f0 for progress.

I still have to make changes to `VersionManager.py` so that it knows to look at the `pkgproj` files to adjust the version numbers.  I also need to make the updates to the website.

**Comment by eroux** [comment]
Good! Can you just open a pull request with what you have now so we can comment more easily? A few comments on what I've seen:

 * `$HERE` should be renamed `$BUILDDIR`
 * what does `sed -i.temp` do?

**Comment by henryso** [comment]
`-i.temp` makes backups of the changed files with the suffix `.temp`.  These are apparently deleted right after.

**Comment by rpspringuel** [comment]
The `sed` implementation on a Mac prohibits in place changes unless a backup file is created.

I could probably save the deletion until the general clean-up at the end of the script.  Since I wrote the script piece by piece, I didn't have the clean-up (or even the build phase) in place when I wrote those lines.

**Comment by eroux** [comment]
oh sorry, for an unknown reason, github is lagging quite a lot, and the file I was looking at was truncated after `sed -i.temp` (I didn't see the end of the line, nor the following lines), but now that I can see it entirely, it makes sense. Sorry!

**Comment by eroux** [comment]
Also, another not very important comment, you can use `make distclean` instead of the two last `make clean` in `create_package.sh`

**Comment by rpspringuel** [comment]
There was a commit where that line was incomplete, so it may not be GitHub's fault that you didn't see more than that.

**Comment by rpspringuel** [comment]
While we have a working installer with the merging of #212, there is still an outstanding issue:

GUI launched applications on Mac do not see the same `PATH` variable as Terminal (or other shell launched apps).  As a result, the Installer program runs `test.sh` and `postflight.sh` with a more limited `PATH` which generally does not include the TeX executables.  As a work around, I've currently hard coded the path to `kpsewhich` using the default path that TeXLive (and MacTeX) install to.  Of course, this will fail on systems where the TeX installation has been modified significantly.

I'm in need of ideas on how to fix this.  My current thought process runs something like this:

1. In `test.sh` look for `kpsewhich` in `PATH` and `/usr/texbin`.  If not found in either location, issue a _warning_ that the user either doesn't have TeX installed or has a non-standard installation.
2. In `postflight.sh` look for `kpsewhich` in the following places, using the first one found: `PATH`, `/usr/texbin/` `/`.  The first two are just tried outright, progressing to the next step if that one fails.  The last must use either `find` or `locate`.  If that one fails, then the installation fails at this point.

The reason that I don't put the `find` or `locate` step into `test.sh` is because this can take a while, especially `find` on a large system.  However, because `test.sh` doesn't look in all possible locations for TeX, it can't be sure that TeX is not there.  Adding the `find` or `locate` step would enable `test.sh` to be sure, and thus halt the installation on a system which doesn't have TeX (as it does currently).

Having the installation fail at the post-flight script leaves the files installed to their initial locations on the user's system.  This will give them a working command line tool, but no way to use TeX to generate scores.  I could modify the scripts failure conditions to clean up the installed files on a failure (returning the file system to the pre-install state).

**Comment by eroux** [comment]
Wow, reading "GUI launched applications on Mac do not see the same PATH variable as Terminal (or other shell launched apps)." I really have the feeling OSX starts to be like 90's Windows... Is there a reason why there are different PATH variables? Anyway, would [that](http://superuser.com/a/541068) be a possible solution to investigate? If not, we can do as you say, no problem.

**Comment by henryso** [comment]
Not that I'm a Mac user, but...

Are there other installers for TeX packages on Mac?  If so, maybe we can copy what they do?  If there aren't, then I'm actually in favor of failing the install if you can't find `kpsewhich` up front.  If you've modified your TeX installation significantly, then it's up to you in install Gregorio from git according to your non-standard set up.  I think you can even leave out find/locate for the same reason.

**Comment by eroux** [comment]
Good point, it might be a simpler solution

**Comment by rpspringuel** [comment]
@henryso Not that I know of. I get most of my packages through the TeXLive update utility. The rest I manually copy into my personal `texmf` directory. 

@eroux the solution you linked to involves editing the plist for the Installer application, not our package file. We might be able to script those changes to Installer, but I wouldn't be comfortable having our installation package making changes to the system Installer like that. 

I'll modify the scripts so that they check whatever limited `PATH` is available to the first before resorting to the hard coded path they currently use. I'll also make the error message a bit more verbose about the possible reasons for a failure so that the user has more guidance as to how to fix it.

**Comment by eroux** [comment]
ok I understand, that would be too ugly indeed...

**Comment by rpspringuel** [comment]
This is working for now.  We'll create a new issue when we look at making the switch to Xcode's native utils.
