### ISSUE TITLE
Documentation for installing alternate fonts

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#1240]
Since the build for 5.0 no longer includes gregorio and granapadano fonts by default, we have to figure out the logistics for users to download the alternate fonts.  There are placeholders in CHANGELOG.md and UPGRADE.md for this.

We should resolve this issue before we release 5.0.

**Comment by eroux** [comment]
I was initially thinking about a `gregorio-extra-fonts.zip` containing all the other fonts with some instructions on how to install them... wdyt?

**Comment by rpspringuel** [comment]
Some thoughts (in no particular order):

My instinct is for separate zips for each font set (so one for gregorio and one for granapadano), but this may be overkill.

What about the installers?  If the font files are in simple zips, that might not be friendly to those users who rely on the installers.  Do we create add-on installers or incorporate the extra fonts as optional installs into the existing installers for these users?

Zip files (be it one or many) would have the advantage of being the "universal option", enabling one installation method for all platforms.

Would it be practical to add a flag to `build.sh` and `install-gtex.sh` which would build and install the extra fonts at the same time as the rest of the process is taking place?

It would be worth looking at the possibility of writing a lua script which would use `kpsewhich` to determine the appropriate destination for the fonts and copy them there.  This script could be included in the zip file and thus installation would be as simple as `luatex install-fonts.lua`.

**Comment by rpspringuel** [comment]
I'm working on this and need some feedback on the following questions:

1. Right now `install-gtex.sh` will install all fonts which have been built and the source files for all fonts, even the ones which haven't been built.  Should this be changed so that only greciliae will be installed (both font and source)?  If all built fonts should be installed (current behavior), should it only install the source files appropriate to the built fonts (instead of all source files)?

2. Should the extra fonts be installed in the exact same place as greciliae (`fonts/truetype/public/gregoriotex/`), or should we create a separate directory in the texmf tree for them (`fonts/truetype/public/gregoriotex-extra/`)?  The first is more convenient, but the second makes it clearer that these fonts weren't installed at the same time.

**Comment by henryso** [comment]
As for the first point, I guess the root question is who will be using install-gtex.sh (as opposed to unzipping a TDS-structured zip file).  If it's someone installing from source, I think it should just do what it's currently doing.  If it's someone else, then we need to discuss it further.  However, my personal views are not very TeX-like (I don't think it's necessary to install font sources, for example), so take that into account.

As for the second point, I don't have any particular preference, as long as all installed fonts will be found.

**Comment by rpspringuel** [comment]
I'm fairly certain that install-gtex.sh is used only by those installing from source as neither the Mac nor the Windows installer makes use of it, but we have two groups of those people: those using a git clone and those using the distribution tarball.

Those building from the git clone will have all the prerequisites for building the extra fonts (since they are the same as what's needed to build greciliae, the defualt font), but will need to step outside of the usual build steps to have them built (issuing `make really-all-fonts` after `build.sh`).  Once they're built, though, the current install path will install them without any alterations.

Those using the distribution tarball currently get the sources for gregorio and grana panado in that tarball, but they aren't have been built and thus usable copies won't be installed if they follow the ordinary installation path (build.sh followed by install.sh).  If we keep things this way, building the additional fonts from the distribution tarball is possible (since the sources are there), assuming the user has the necessary python and fontforge prerequisites.  However, I don't expect these people to have those prerequisites (those that do are most likely building from a clone), and thus I expect these people might prefer to download and install the extra fonts pack (along with the installer users).

Perhaps then the following is in order:

1. Remove the gregorio and grana panado sources from the distribution tarball.  The assumption here is that those wanting the fonts will either be capable of building from a clone (and thus building them themselves when they build everything else) or will use the zip (which will contain the sources along with the pre-built fonts).  Further, this will mean that what's installed in sources will match what's installed in the usable working directories.
2. Adapt install-gtex.sh so that it doesn't explicitly look for particular font sources (right now it looks for greciliae-base.sfd, gregorio-base.sfd, and granapanado-base.sfd by name), but just picks up all that are available (i.e. *-base.sfd, kind of like it looks for *.ttf for the built fonts), this way it can handle either the distribuition tarball or a complete build from clone.
3. Install gregorio and grana panado into the same place as greciliae.  This way the result of using the distribution tarball and building from a clone is the same (except for the uninstall script).

**Comment by henryso** [comment]
I'm fine with all your suggestions.

**Comment by olivierberten** [comment]
I have no idea how complex that is but wouldn't it be possible to load the music fonts just like any other font? In which case, user could install their custom fonts in their usual font place and use them with a simple fontspec command...

**Comment by eroux** [comment]
well, it's more or less the case now, you can load them with the `\font` command if you want, just make sure you put them in the `\gre@font` (or so) macro, but I think the problem if we just let users put some files in their `~/.fonts/` directory is that we'll receive tons of mails of users whose documents are broken because the font is not in the correct version...

**Comment by olivierberten** [comment]
Well... people using custom fonts won't be the average user anyway so a simple warning in the doc should be enough imho...

**Comment by rpspringuel** [comment]
See #1306 for how I've solved all these issues.
