### ISSUE TITLE
Font size not taken into account when spacing lyrics

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1261]
In the following document the larger than normal lyrics text causes it to overlap with the low notes of the staff.  

```
% !TEX program = LuaLaTeX+se
\documentclass[12pt]{article}

\usepackage{fullpage}
\usepackage{libertine}
\usepackage{gregoriotex}

\begin{document}

\Large
\gabcsnippet{(c3) Hel(g)lo(g) nó(dc)}

\end{document}
```

This happens because the distance between the bottom line and the text baseline (`spacelinestext`) is a fixed value (currently 0.60617cm) which is only appropriate for font sizes of roughly 10 to 12 pt.  I propose changing the value to em units.  The current value is about 1.72em if the base font is 10pt and 1.44em if the base font is 12pt.  I thus think 1.5em is a good starting point.  I would also change this distance so that by default it is fixed with respect to the staff size.

Comments?

**Comment by eroux** [comment]
Well, I don't have a strong opinion on that, I don't find the current behavior particularly buggy... but if you change it, the `em` unit doesn't make any sense, the `ex` unit does

**Comment by cantatedomino** [comment]
I do very much appreciate the hard work of all the Gregorio developers, and the updates in Version 6, but this change did break the spacing in my engravings; Setting the Salve Regina (solemn tone) shifted the text in all the lines of chant to spacing required by the lowest note in the entire piece, rather than the lowest note for that particular line.I have a work-around that adds \grechangedim{spacelinestext}{0.60617 cm}{scalable} to my LaTeX preprocessor file.
