### ISSUE TITLE
strange install-gtex feature

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1263]
I'm usually using `./install-gtex.sh user` to install the current tex files, but now it says

```
./install-gtex.sh user
/home/eroux/texmf/scripts/gregoriotex/uninstall-gtex.sh exists; delete it to continue
```

which I don't understand... can someone explain?

**Comment by henryso** [comment]
If that file exists, it means that gregoriotex was already installed, so one should either first run the script to uninstall gregoriotex before installing (to make sure everything is clean), or delete it before installing, risking potentially leaving junk in the install directories.

We have a few options.
1. I can drop the check, with the risk listed above.
2. I can change the message to indicate the script should be run before doing a new install.
3. I can automatically run the script if it exists.

... or other things based on the above.  Suggestions?

**Comment by eroux** [comment]
Ok, understood, thanks! I think `3.` is a good idea... what do you think? Maybe it could be behind an `--auto` option, but making it the default doesn't sound bad

**Comment by rpspringuel** [comment]
I like option 3 as well.  Right now my personal install scripts (which I use to completely automate the whole build and install process) basically do just that.

As for whether that should be default or optional behavior, I could see it going either way.  If it's default, I'd have a `--safe` option which aborted the installation process when the script is present (the current behavior).  If it's optional, then the error message should mention that rerunning the script with the `--auto` option will take care of the problem.

One complication that occurred to me is the possibility of skipping the fonts in the install.  If `install-gtex.sh` is set to skip the fonts when installing, then the fonts should not be removed by `uninstall-gtex.sh`, otherwise the individual will be left with a non-working installation (version conflicts might still render the installation non-working, but that's the risk skipping the font installation runs).  I don't know how much skipping the fonts installation happens in the wild, but I make use of this option fairly regularly when testing pure TeX changes.  As a result, I've adapted my personal scripts to by pass the check by deleting `uninstall-gtex.sh` (and nothing else) when I call for a no fonts installation.

**Comment by henryso** [comment]
I'm inclined to run it if an option is given, erring on safety, though it may be an environment variable-based option for consistency (e.g., `AUTO_UNINSTALL=true ./install-gtex.sh user`).  The message should also change accordingly.

As for skipping fonts and stuff like that, `uninstall-gtex.sh` will delete exactly the files that were created during the install.  So if the install didn't install fonts, `uninstall-gtex.sh` will not delete them.

**Comment by rpspringuel** [comment]
> As for skipping fonts and stuff like that, uninstall-gtex.sh will delete exactly the files that were created during the install. So if the install didn't install fonts, uninstall-gtex.sh will not delete them.

Right, exactly.  The problem is that it's the current installation which isn't installing the fonts, not the last one which generated the `uninstall-gtex.sh` which is going to get run.  The situation I'm describing looks like this:

1. I make a full install: tex files, fonts, everything.
2. I do some work on the TeX files, leaving the font and binary alone
3. In order to test something, I install just the TeX files, skipping the fonts, font sources, examples, and docs.

If as part of step 3 I run the `uninstall-gtex.sh` file created in step 1 then I'll be left without any fonts installed.  This would lead to a non-working installation.  What needs to happen in step 3 is that only the files (or rather group of files, to account for changes in the file manifest) I'm about to install are deleted while the others are left in place.  Of course, in this case, the `uninstall-gtex.sh` script which is generated in this case won't delete the files left in place, so ideally the generation of `uninstall-gtex.sh` would take this into account, but I can live with it not doing so.

**Comment by henryso** [comment]
Sounds like a developer-specific problem.  Perhaps the best thing to do here is to add a way to ignore (and not generate a new) uninstall-gtex.sh and just install.  Would that help your workflow?

**Comment by rpspringuel** [comment]
If you really think it's developer only, then I can handle it with my personal scripts (indeed, I already have a work around in place, though it's probably not optimal).  There's no need for you to spend a bunch of time fixing my problem.  I pointed it out in case it might be a problem for others.
