### ISSUE TITLE
(efO e) pointing in the wrong direction (?)

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1272]
With latest gregorio, if I try

```tex
\documentclass[12pt]{article}
\usepackage{fontspec}
\usepackage[autocompile]{gregoriotex}
\begin{document}
\gabcsnippet{(c4) f(efO e)}
\end{document}
```

I get

![bug](https://cloud.githubusercontent.com/assets/60868/21681153/396cf834-d34e-11e6-8151-9e9233837cdf.png)

while Solesmes would like the oriscus to point to the following note (down)

**Comment by henryso** [comment]
As a workaround, you can use `e@fo e`.

**Comment by eroux** [comment]
Yes, that's what they use

**Comment by henryso** [comment]
This one is tricky because `efO` is detected as a particular shape (initially incorrectly called—by me—"virga strata") which is not aware of oriscus direction.

There are two solutions:

1. Drawing 5 additional glyphs and changing the executable to deal with direction on this shape.
2. Scrapping this shape as special and auto-fusing the glyph when this sequence is encountered.

What do you suggest?

**Comment by eroux** [comment]
That's a good question... I tend to be in favor of option 1 because it will look nicer in pdf viewers and Solesmes seems to use this glyph reasonably often... (and thus chances are that it will appear in a broader way in future scores)

**Comment by henryso** [comment]
Ok, will do.
