### ISSUE TITLE
Documenting the release process

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#134]
Where do you think the release process should be documented? I was thinking about a Wiki page. It would contain things like
 * how to package sources
 * how to upload the installer
 * what to put as release message
 * where to put the `.deb` files
 * how to do for OSX (in the future)
 * etc.

**Comment by henryso** [comment]
These things should absolutely go to the wiki.

**Comment by eschwab** [comment]
I was thinking about restructuring the source tree. We have folders for different platforms, `windows` `archlinux` `macosx` `cygwin`. If those were all put under a `platforms` or `distrobution_build` folder, then there could be a README.md in that folder with all the options/platforms layed out. This does not exactly pertain to releases but could help in the process of making the packages, `tarball`, `.deb`, `.pkg` for OSX, `.exe` etc. and for users who want to build their own git version.

**Comment by eroux** [comment]
Why not, yes, this could make things cleaner.

BTW, it's interesting that you mention the cygwin directory, I totally forgot its existence... I believe we can remove it, it's completely outdated by the Windows installer.

**Comment by rpspringuel** [comment]
Whether or not the cygwin folder is outdated will depend on our release cycle for development.  How often are we going to package a development release for Windows?  If we're doing this regularly, then being able to build from source via Cygwin on Windows doesn't provide any appreciable advantage.  If, however, we're lazy about packaging development releases into Windows installers, then the Cygwin build option would be the best bet for staying on the cutting edge.

Now, with the new git-flow work flow, my scripts need some work, but I do have some scripts that minimize the number of steps that it takes to package a Windows release.  The most time consuming part of them was switching between virtual machines (as I used a Ubuntu machine to compile the `.exe` and a Windows machine to create the installer).  For someone with WINE up and running, the process may be simpler.  I don't have it going because it doesn't make sense for me to have a virtual machine inside my virtual machine.

**Comment by eroux** [comment]
After looking a bit at the files, I deleted the `cygwin/` folder, as explained in the commit message of https://github.com/gregorio-project/gregorio/commit/bf81b3b661820770288dd90dc8af397b18a3ebd7 . But to answer your question, yes, building a gregorio installer is quite straightforward with Wine:

 * `./build.sh --mingw`
 * `./install-gtex.sh tds`
 * `wine32 'C:\\Program Files\Inno Setup 5\ISCC.exe gregorio.iss'` (which I copy/paste from the README)

and that's it. I think it should be a reasonable goal to have a Windows installer for every release...

Also, just to let you know, I'm building a [PPA](https://launchpad.net/~gregorio-project/+archive/ubuntu/gregorio), but I'm still at the very early steps...

**Comment by eroux** [comment]
I've made pages in the [wiki](https://github.com/gregorio-project/gregorio/wiki), tell me what you think!

**Comment by eschwab** [comment]
Under `Release Candidates` should not the last line be `vx.y.z-rc2`?

**Comment by eroux** [comment]
Indeed, fixed

**Comment by rpspringuel** [comment]
Looks good for standard releases.

What about development releases?  Are we going to bother with those or simply assume that anyone who wants the cutting edge of development should be building from source?

**Comment by eroux** [comment]
Yes, basically people who want more cutting-edge than release candidates will have to build from sources... I was thinking about some kind of build farm that would make some kind of continuous integration a la [travis ci](https://travis-ci.org/) (or maybe using travis directly), but that's another layer on top of it...
