### ISSUE TITLE
Alternate glyph for sharp accidental (alteration sign)

### ISSUE THREAD

**Issue by maxpawkas** [gregorio-project/gregorio#1399]
Gregorio uses it's own glyph for a sharp accidental.

Graduale Novum - a recognized (and trendsetting) chant book using neography (sharps included) uses a more "standard" form for a sharp.

Would you consider adding an .alt glyph for the sharp to follow this trend?

![gngregorio](https://user-images.githubusercontent.com/3966704/35877020-6818175e-0b74-11e8-9019-d27598ef0c6e.png)

**Comment by henryso** [comment]
I think this is a good idea, but I'm not the best person when it comes to drawing glyphs.  Truly, the largest difficulty here is in drawing the glyph.

**Comment by rpspringuel** [comment]
The first step is to choose the style for the sharp glyph, as there are several.  The one in the image @maxpawkas posted has the same thickness lines for both the vertical and the horizontal, but I seen sharps that use a thicker line for the horizontal ([see this picture](http://lilypond.org/pictures/bwv861-lilypond-large.png)).  There's also the question of the angles.  @maxpawkas image angles the verticals while others will angle the horizontals (in the aforelinked picture and the unicode character: ♯).

What sort of look should we be going for if we include this glyph?

**Comment by maxpawkas** [comment]
I think it’s better to follow a trend somebody has already started rather
than creating a new one (there is a Gregorio-specific sharp already).

Graduale Novum is a brand recognized widely in the Gregorian word, so I
don’t see any better options to follow when it comes to adding a sharp
glyph to Gregorio. Sharp in Gregorian Repertoire is something they (GN)
really introduced.



W dniu niedziela, 11 lutego 2018 Br. Samuel Springuel <
notifications@github.com> napisał(a):

**Comment by maxpawkas** [comment]
I think it’s better to follow a trend somebody has already started rather
than creating a new one (there is a Gregorio-specific sharp already).

Graduale Novum is a brand recognized widely in the Gregorian word, so I
don’t see any better options to follow when it comes to adding a sharp
glyph to Gregorio. Sharp in Gregorian Repertoire is something they (GN)
really introduced.

**Comment by rpspringuel** [comment]
Looking at that glyph again, I think what GN used was the pound sign (or hashtag for you new fangled social media users): #  At least on my system, it has the same slants as shown in the image.

Makes me wonder if the GN people know the difference between # and ♯.

If we follow the GN convention, then I would guess that at some point someone will complain that the sign isn't "correct" from a musical perspective.  @henryso, how hard would it be to add two alternate sharp glyphs?

@maxpawkas can you extract a high resolution scan of the GN sharp without anything else in the image?  If you want that specific glyph, having such a scan would make drawing it easier (as it could serve as a tracing template in FontForge).

**Comment by maxpawkas** [comment]
@rpspringuel I certainly can do my best to extract the scan. Not today tho.

I’m pretty sure the glyph they used has been chosen on purpose. The GN people are well educated musicians with academic degrees. They’re working on musical restitution of Gregorian Chant.

The decision to use a pound sign rather than the more common sharp glyph to me seems to be an esthetic decision. On a “normal” music staff the sharp is bigger than the field between lines. Here though the sharp is entirely between lines. Their choice won’t allow the horizontal lines of the sharp cross the lines of the staff neither when placed on a line nor when between. 
Notice how the sharp would “touch” the line in the example at the top had the horizontals been angled instead of verticals.

GN is a publication that (up to my knowledge) has first introduced sharps to GREG and hence - it’s always going to be a reference for any following editions.

**Comment by henryso** [comment]
@rpspringuel It's not hard to add glyphs once they're drawn, but they take up space, and these things take up two slots each.  In my opinion (and again, I'm not really an authority on aesthetics), the GN sharp doesn't harmonize with the rest of the glyphs.  The verticals on both the flat and the natural that we currently have in the font have their verticals perpendicular to the staff lines.  If it were me, I think that something fully square (like a tic-tac-toe board) might be best.  I'm curious about the source of the current "X" shaped sharp glyph.  It's been that way as far back as I've been involved with gregorio as a user.

**Comment by rpspringuel** [comment]
> The GN people are well educated musicians with academic degrees.

Certainly, but we're talking about a typographical issue here, not a musical one.  Knowing the difference between the two glyphs involves being familiar with either the Unicode spec or music engraving practices.  I've seen plenty of musicians who look at # on their keyboard and think its the sharp symbol.

Still, you're other points are well made and could very well represent their thinking.

> they take up space, and these things take up two slots each

How are we doing on number of available code points?

> I'm curious about the source of the current "X" shaped sharp glyph. It's been that way as far back as I've been involved with gregorio as a user.

Same here.  @eroux, you probably designed that glyph.  Where did it come from?

**Comment by henryso** [comment]
@rpspringuel We have 655 code points left.

**Comment by henryso** [comment]
Something interesting: The SMuFL (at https://w3c.github.io/smufl/gitbook/tables/medieval-and-renaissance-accidentals.html) calls the "double X" a "croix," and it's in Unicode 10.0 at U+1D1CF.  SMuFL names the glyph "medRenSharpCroix."

In https://music.stackexchange.com/questions/46391/where-did-the-symbols-and-%E2%99%AF-originate-from-and-why-those, the answer from alephzero states:

> The original sign for "sharp" was written using diagonal lines, like an x with double strokes. I don't know when or why the "single sharp" became more vertical, and the modern diagonal "double sharp" was first used.

I would guess that this symbol came from the same place where those Mensural and Hufnagel clefs came from.

**Comment by rpspringuel** [comment]
Hmm... @henryso That make me think that the primary (non-hole) glyph for the sharp (both the cross one and the modern one) could be placed at their appropriate unicode code points, instead of in our private use area.  That would save us some code points in the private area and by converting all the existing alterations to do that we might end up gaining a few code points even as we add a glyph (or two).  How hard would it be to move the existing alterations to their appropriate code points?

**Comment by henryso** [comment]
We could use the code points for sharp, natural, and flat, but then we would need to adhere to the Unicode glyph naming.  I don't think this is worth the trouble for three code points.  As for the croix, that Unicode code point is *not* in the BMP which we are trying to stay within since using the extended Unicode planes slowed things down significantly.

**Comment by rpspringuel** [comment]
The first one is good.  I'll see if I can't find some time to start playing with it in FontForge.  It may be a while though (lots on my plate at the moment) so if anyone else wants to take up the task of adding the glyph to one of the fonts, feel free.

**Comment by henryso** [comment]
I can do it.  Are we settling on that form?

**Comment by henryso** [comment]
Do we have to worry about copyright of that glyph?

**Comment by rpspringuel** [comment]
I don't know.  @maxpawkas, can you check the book to see what its copyright notices say.  (Probably not definitive, but it'll be a start. 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by henryso** [comment]
The copyright notice on the book is:

> Ⓒ 2011 ConBrio Verlagsgelsellschaft, Regensburg
> 
> In Kooperation mit der Libreria Editrice Vaticana
> Herstellung: ConBrio Verlagsgesellschaft, Regensburg
> Druck: Friedrich Pustet KG, Regensburg
> 
> ISBN 978-3-940768-15-5
> CB 1215

Reading the English Preface, there's nothing there that specifically mentions the glyphs used for engraving.  In these cases, I typically assume "all rights reserved," so would consider the shapes copyrighted.  To wit Solesmes, who are very protective of their engraving shapes.  I don't know that we should take the risk here.

However, in the Preface, flat is indicated using an italicized _b_ rather than a ♭ and sharp as a # rather than a ♯.  So I don't think we need to take their word for the musical shape here.

Which brings me to my original statement.  The real difficulty is in drawing the glyph.  Not necessarily drawing it in fontforge, but rather drawing it so that it can be put into fontforge.  One option is to extrapolate the Caeciliae ♯ into a ♮ by extending the lines.  At least then it might harmonize with the rest of the font.

**Comment by rpspringuel** [comment]
Good catch on the copyright issues, I wouldn't have thought of it.

> However, in the Preface, flat is indicated using an italicized b rather than a ♭ and sharp as a # rather than a ♯. So I don't think we need to take their word for the musical shape here.

That makes me think that my first suspicion about the typography was correct.  I'm therefore inclined to base our shape on something that more closely resembles ♯ instead of #.  We can play with the size of the glyph to keep it within the lines (or at least not extending beyond them by more than the existing flat does).

I think that turning ♮ into ♯ is decent idea.  If we can merge the glyph with a vertical mirror of itself, then our verticals would be taken care of and we would only need to manually work on the horizontals.  It would be also be possible to simply reuse the hole glyph (though I don't know how easy the existing mapping logic would work for actually reusing the code point).

We could also borrow the ♯ from a font which permits that (e.g. Linux Libertine), though we might have issues with scaling and harmonization and would have to create a new hole glyph.

Which would be easier: borrowing a whole glyph, rescaling it (if necessary), and creating a new hole, or copying and modifying one of our existing glyphs?

**Comment by henryso** [comment]
Creating the hole is not an issue.  Taking a glyph from elsewhere poses a problem with the weights of the lines not matching those of our font.  I'll see what I can come up with.

**Comment by rpspringuel** [comment]
I think it's a suitable start.  Should someone with a better eye for asthetics want to try their hand at designing something else, then we can always change it (or add it to one of the other fonts) later.

**Comment by henryso** [comment]
Ok, this is what I came up with.  It looks funny to me (knowing modern music) with no line behind the hole.

![image](https://user-images.githubusercontent.com/421318/36238648-f199c9d8-11d1-11e8-8f59-37a049832ee6.png)

**Comment by henryso** [comment]
Here's an example with other alterations for contrast

![image](https://user-images.githubusercontent.com/421318/36238731-76879be8-11d2-11e8-8a73-751bdef81620.png)

**Comment by rpspringuel** [comment]
Looks good to me, though I agree that hiding the line behind the sign looks funny.  Is it possible for the option on whether or not to show those lines to be modified to be character by character?

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by henryso** [comment]
Right now, the option (`\gresetlinesbehindalteration`) is to hide or show for all alterations.

**Comment by henryso** [comment]
I guess it looks no funnier than hiding the lines behind flats and naturals:

![image](https://user-images.githubusercontent.com/421318/36265273-dfcf57a2-123c-11e8-87dc-2a7a05ff2348.png)

**Comment by rpspringuel** [comment]
> Right now, the option (\gresetlinesbehindalteration) is to hide or show for all alterations.

I know that, I was wondering if it would be possible to change that.  I was away from my computer without access to the code at the time.  Now that I'm back home, looking at the code it would be possible, it's just a matter of expanding [this `\ifgre@hidealtlines` check](https://github.com/gregorio-project/gregorio/blob/b7e1660116a2775e5cbc363677b2c343515d525b/tex/gregoriotex-signs.tex#L2414) to also check which alteration is being set (value of `#3`) and differentiating the behavior accordingly.

Does the GN generally show lines behind the flat?  If it does, then I feel that keeping things as is should be fine.  If it hides that line, then I think it might be useful to create that expanded option.

**Comment by termiciasty** [comment]
> Does the GN generally show lines behind the flat? If it does, then I feel that keeping things as is should be fine. If it hides that line, then I think it might be useful to create that expanded option.

The example that @maxpawkas put in the very first post shows that the lines are visible behind the sharp sign.

Are you planning on writing a GregorioTeX command for switching between sharp glyphs or is there going to be another gabc command (e.g. `g#0`) for the new one?

**Comment by rpspringuel** [comment]
> The example that @maxpawkas put in the very first post shows that the lines are visible behind the sharp sign.

I realize that.  The issue is whether the lines show behind the *flat* too.  As it stands we can toggle between showing the lines or not, but only at the global level, i.e., for all alterations in a score.  The question is whether we need to differentiate the behavior between the different types of alterations so that the line behind a flat is hidden while the line behind the sharp appears in the *same* score.

> Are you planning on writing a GregorioTeX command for switching between sharp glyphs or is there going to be another gabc command (e.g. g#0) for the new one?

Neither.  The existing GregorioTeX functionality for swapping out glyphs covers it.  See [the new test](https://github.com/henryso/gregorio-test/blob/965950b9d641b844163008340be277b00f2c8c74/tests/gabc-output/modern-sharp-preamble.tex) for an example of how the switch is made.

**Comment by henryso** [comment]
According to the preface, besides si♭ (which will always be in a space), there is also mi♭.  I will try to look for this elusive mi♭ (which would be on a line) and give you an answer unless someone beats me to it.

**Comment by henryso** [comment]
Ok, I opened the book and idly looked at a few random pages and happened to find an instance (page 296, third staff from the top, for reference).  The lines do show behind the flat.

**Comment by rpspringuel** [comment]
> si♭ (which will always be in a space)

Wouldn't a fa clef put the flat on a line?

> The lines do show behind the flat.

In that case our existing global setting should be sufficient.  I'll review the PR this weekend.

**Comment by henryso** [comment]
You're right.  I keep thinking about above the clef for the fa clef.

**Comment by maxpawkas** [comment]
@henryso the shape of yours is beautiful.
It was a great idea to reshape a natural!

Chapeau bas.

**Comment by henryso** [comment]
I make some tiny changes because I thought the balance of the sharp against the natural was wrong (the glyph seemed too tall when zoomed in).  As you can see here, there's not much change, but this shape makes me a bit happier.

![image](https://user-images.githubusercontent.com/421318/36342524-00c63c86-13ce-11e8-9b02-cda65e2fb173.png)
