### ISSUE TITLE
Document new centering controls

### ISSUE THREAD

**Issue by chrylis** [gregorio-project/gregorio#1454]
The documentation mentions that `centering-scheme` is obsolete in favor of control from TeX but then doesn't mention anywhere how to do that. I've seen #28 and related which suggest it's `\englishcentering`, but I also know there's been a lot of development for other languages. What's the current status?

**Comment by rpspringuel** [comment]
`\gresetlyriccentering` is the command to control how the notes get aligned to the lyrics beneath.  It takes 1 argument with three possible values: `vowel`, `syllable`, and `firstletter` (2.2.12 in GregorioRef).  Of the three only `vowel` is language dependent (since what counts as a vowel varies from language to language).

The language is set with the `language` header in the gabc file and Latin, English, Church Slavonic, and Hungarian are supported out of the box.  Polish, Czech, and Slovak are supported as aliases for Church Slavonic.  Languages can be specified by name (in which case both titlecase and lowercase names are accepted) or by their two letter ISO 639-1 or three letter ISO 639-2 code.

**Comment by chrylis** [comment]
`\gresetlyriccentering` doesn't appear to be included in the documentation anywhere; could it get a description in the TeX details and a link from the Text Centering section? (The current phrasing even with the updates doesn't reveal how to, for example, change the centering anchor to first-letter.)

**Comment by rpspringuel** [comment]
`\gresetlyriccentering{firstletter}` places any where in the document before the score inclusion. 

It’s documented in GregorioRef.pdf.  That is the most complete and up to date documentation.

It is not, currently, on the website.  Our website documentation is in desperate need of some updates. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
