### ISSUE TITLE
problem updating \gre@stafflinefactor

### ISSUE THREAD

**Issue by asbloomf** [gregorio-project/gregorio#1461]
This was happening on 5.2.1

If \greconffactor is different than what the staff size is set to, it seems to cause a problem when loading the new space file.  It multiplies by the staff size but divides by \greconffactor.  Anyway I think that is what was going on.  So if you have the staff size set to something big like 23 and the regular \greconffactor of 17, when you load the new spacing, \gre@stafflinefactor gets set to 31  (23 * 23 / 17).  It's easy to workaround so it's not a big deal.  I'm not sure if anything else is affected, but the line thickness was certainly quite noticeable.

**Comment by rpspringuel** [comment]
It sounds like expected behavior. Your new spacing file should have its own `\greconffactor`.  This variable indicates what size staff the gsp file assumes so that the distances loaded by the file can be scaled appropriately if a different staff size is currently in effect.  This prevents odd order effects in changing staff size and loading custom spaces.

Example: I have a project for which I expect to print staves at 20.  In designing a custom gsp file for the project I set `\greconffactor` to 20 so that I can enter custom spaces directly based on page measurements without any math for scaling.  Later on, I create another project in which I want to include a scaled down version of one of the scores in the first project, say at size 10 (half scale).  Because of `\greconffactor`, I can load my custom gsp file either before or after switching to size 10, and I never have to switch to size 20 (if that isn’t used elsewhere in the new project). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by asbloomf** [comment]
It didn't seem like expected behavior, but maybe it is.  What confused me was that I got different behavior when I changed the order of \grechangestaffsize{17} and \greloadspaceconf{default} when switching back.  It seemed to me that loading the spacing configuration wouldn't be dependent on what the staff size was set to but then it was.  Anyway, like I said, now that I understand how it works it's not a big deal.

**Comment by rpspringuel** [comment]
Order effects are exactly what `\greconffactor` was implemented to avoid.  If you saw one, then there's a bug to be worked out.  Can you post a MWE which shows the order effect?

**Comment by asbloomf** [comment]
I think this shows it.  I set the staff size and then each time I load the default spacing, it makes the lines a little thicker.
[mwe.pdf](https://github.com/gregorio-project/gregorio/files/3152708/mwe.pdf)
[mwe.tex.txt](https://github.com/gregorio-project/gregorio/files/3152710/mwe.tex.txt)

**Comment by rpspringuel** [comment]
That's definitely a bug.  I'm in the midst of exams, and have my pre-ordination retreat next week, but I'll put this on the to-do list.

**Comment by rpspringuel** [comment]
Fix is up (#1464).  Please test and indicate if it is acceptable.

**Comment by asbloomf** [comment]
Yes, this fixes the problem.
