### ISSUE TITLE
moving tests from examples/

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#147]
`examples/` directory contains `completetest.gabc` and `test_all_headers.gabc` which are not really examples intended to users, but tests. One is on [the test repository](https://github.com/gregorio-project/gregorio-test).

Also, maybe it would be good to move all test files (from `tests/`) to this repository?

**Comment by henryso** [comment]
I'm in the process of putting all the tests into the test repository, which is why `test_all_headers.gabc` is already there.  I was unable to get `completetest.gabc` to work last night, so that one is pending Br. Samuel's latest fixes.  All the tests in `tests/` are also there as well, but I know Br. Samuel's workflow involves running them against the linked GregorioTeX files in `tests/`, and I haven't figured out an elegant way to run the tests (in gregorio-test) against not-installed versions of Gregorio yet.

**Comment by rpspringuel** [comment]
You probably want to look into making gregorio a [submodule](http://git-scm.com/docs/git-submodule) of gregorio-test.  Then you can use soft links to the submodule to get the tests to run against it, rather than the installed version.

It should be noted, that this setup only works replaces GregorioTeX with the development version, not the command line tool.  If the command line tool changes, I have to go through the whole installation process.

**Comment by henryso** [comment]
Provided you build gregorio static (`./configure --enable-all-static`) you should now be able to run `gregorio-test.sh` (in the gregorio-test project) with a `-g /path/to/gregorio/root` and it will use the `gregorio` executable and GregorioTeX files within.  The remaining problem is for me to figure out how to override how luatex loads the fonts.  An initial search seems to indicate the need to change how the font is selected, but that would mean destabilizing Gregorio for 3.0.  If anyone knows a better way, I'm open to suggestions.

**Comment by eroux** [comment]
I have a few difficulties with my tex files right now, but here are some pointers 

 * if you register a callback in [find_font_file hook](http://www.luatex.org/svn/trunk/manual/luatexref-t.pdf#42), you'll be able to cheat luatex and make it find the font you want
 * `\global\font\gregoriofont="file:path/to/greciliae.ttf" at 1700000 sp` may work, but I'm not 100% sure

**Comment by eroux** [comment]
Adding

    \makeatletter
    \def\setgregoriofont#1{%
      \xdef\gregoriofontname{#1}%
      \gre@count@temp@three = \the\grefactor %
      \multiply\gre@count@temp@three by 100000 %
      \global\font\gregoriofont="file:../fonts/#1.ttf" at \the\gre@count@temp@three sp%
      \relax%
    }%
    \makeatother

will make things work (finally managed to test). But if you have an old luaotfload version, there might be bugs... By the way, I'm not being in the middle of a big project is not the best moment for that, but luaotfload and luatex really improved over the years, compilation under TeXLive 2014 is much faster than under TeXLive 2012, and TeXLive 2015 will be even faster...

**Comment by henryso** [comment]
I think I've figured out a way without the TeX hackery.  If I install GregorioTeX into a temporary directory (`using install-gtex.sh dir:...`) and prepend that directory to TEXMF via the environment, it'll use that version of fonts unless you installed the ttf files to system font directories.

**Comment by eroux** [comment]
That sounds like a good solution

**Comment by henryso** [comment]
I've made the changes to gregorio-test.  Please try them out.

In order to run using a not-installed gregorio, do the following:

1. `cd /path/to/cloned/gregorio`
2. `autoreconf -f -i`
3. `./configure --enable-all-static`
4. `cd fonts`
5. `make fonts`
6. `cd /path/to/cloned/gregorio-test`
7. `./gregorio-test.sh -g /path/to/cloned/gregorio`

**Comment by henryso** [comment]
Note: all tests from the gregorio project are there (plus Populus Sion, for good measure) except for completetest.gabc, which is pending a resolution for (or a decision not to resolve) #153 and/or #155.

**Comment by henryso** [comment]
Since these files don't get released anyway, I will leave them in (and this issue open) until people are more comfortable with [gregorio-test](https://github.com/gregorio-project/gregorio-test).

**Comment by henryso** [comment]
Closed by #561.
