### ISSUE TITLE
Using Versicle/Response in libreoffice?

### ISSUE THREAD

**Issue by hbeni** [gregorio-project/gregorio#1485]
Hello,
for many years i was able to use the Versicle and Response symbol using the gresym.ttf in libreoffice.
Since i needed to reinstall my computer, i don't see the font and formatting anymore.
From the log of the project i see there where Font changes. i tried to get hold on a gresym.ttf but with no success.

How can i use the default versicle/response symbol from gresym in openoffice again, peferrably under the font name 'gresym', so i don't need to manually redo all my documents (all minor hours.... that is)?

Thank you very much in advance

**Comment by hbeni** [comment]
To clarify, i talk about this:
![image](https://user-images.githubusercontent.com/13608602/72227136-545ef880-3599-11ea-85b2-79099985fb35.png)
(bottom the used font in libreoffice, the chant was produced somewhere in 10/2015 using debian)

**Comment by rpspringuel** [comment]
> On 12 Jan, 2020, at 6:14 PM, Benedikt Hallinger <notifications@github.com> wrote:
> 
> To clarify, i talk about this:
> 
> (bottom the used font in libreoffice, the chant was produced somewhere in 10/2015 using debian)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Those characters no longer exist in the font because they hard coded the look of the letter and so would look out of place with most fonts (basically anything that didn’t resemble Libertine.  Instead, what we have now are several different bars which can be composed with letters of the current font, leading to a much more consistent look.

To get the old stuff, you’ll need to find either a release version from before the change (the releases should have the fonts pre-built for you) or clone the repository, check-out a commit from before the change and then build the gresym.ttf font yourself.

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Fr. Samuel, OSB
(R. Padraic Springuel)
St. Anselm’s Abbey
4501 South Dakota Ave, NE
Washington, DC, 20017
202-269-2300
(c) 202-853-7036

PAX ☧ ΧΡΙΣΤΟΣ

**Comment by hbeni** [comment]
Thank you for your fast response!
How exactly can i built the fonts from the source (git checkout was already done)

**Comment by rpspringuel** [comment]
IIRC `make gresym.ttf` should do it. 

✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️
Fr. Samuel, OSB
(R. Padraic Springuel)
St. Anselm’s Abbey 
4501 South Dakota Ave, NE
Washington, DC, 20017
202-269-2300
(c) 202-853-7036

PAX ☧ ΧΡΙΣΤΟΣ

**Comment by hbeni** [comment]
Thank you very much! i could not build it this way, but _fontforge_ came to the rescue.

For the archives:
- I used commit 6ff43833195a83ad10322540df125f2df93e5ff5 (HEAD, tag: `v4.0.0-beta`)
- That got me the gresym.sfd version i needed.
- Using _fontforge_ i was easily able to convert it to ttf (using this technique: https://unix.stackexchange.com/questions/358673/convert-in-command-line-an-sfd-file-fontforge-to-ttf-otf-woff-svg).
- That i put into `~/.local/share/fonts` and libreoffice could pick it up from there.
All is fine now again.

Here the resulting ttf (inside zip, so github accepts it):
[gresym2.zip](https://github.com/gregorio-project/gregorio/files/4055661/gresym2.zip)


Thank you very much for this great piece of software!
