### ISSUE TITLE
Adding a marginal note renders extra staves

### ISSUE THREAD

**Issue by adunning** [gregorio-project/gregorio#1494]
Gregorio 5.2.1 has rendering problems when attempting to add a marginal note using the [`marginnote`](https://ctan.org/pkg/marginnote) package (`\marginpar` results in an error):

<img width="984" alt="Screenshot 2020-05-22 at 12 18 09" src="https://user-images.githubusercontent.com/1084407/82662726-4e071a00-9c26-11ea-912f-59733f4c4905.png">

```tex
\documentclass{article}

\usepackage{gregoriotex}
\usepackage{marginnote}

\begin{document}

\gabcsnippet{(c3) Test(h) <v>\marginnote{marginal note}</v> mu(h_)sic(g_)}

\end{document}
```

**Comment by rpspringuel** [comment]
I think this is probably caused by the same thing causing the problems in #1500.  The marginal note ends up inside a box and gets processed multiple times.  There also seems to be an invocation of `\localleftbox` inside the margin note.  

In this case, since there's nothing visible in the score itself, you might try using the verbatim macros in the notes instead: http://gregorio-project.github.io/gabc/details.html#verbatim

**Comment by adunning** [comment]
Might it be possible to add a macro for marginal notes into Gregorio itself? It's a reasonably common feature in chant sources.
