### ISSUE TITLE
puncta inclinata ascending and descending

### ISSUE THREAD

**Issue by olivierberten** [gregorio-project/gregorio#1502]
![inclinata](https://user-images.githubusercontent.com/213117/104130980-08918b80-5374-11eb-857e-83a9ecd99626.png)

Is this expected behaviour?

**Comment by rpspringuel** [comment]
Can you be more specific about what behavior you're concerned about?

**Comment by olivierberten** [comment]
the fact HGF isn't rendered the same way both times

**Comment by rpspringuel** [comment]
Checking the generated gtex, no, this is not the expected behavior.  For some reason the first `HGF` sequence generates a series of punctum inclinatum ascendens instead of the expected descendens (which is what the second sequence generates). It seems like the initial ascendens choice persists across syllables (words, really, in this case) where I would expect that boundary to reset the selection algorithm. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by henryso** [comment]
This is actually the way this is designed.  When you have a stream of punctum inclinatum, the system attempts to keep them the same shape (left-leaning or right-leaning).  When the algorithm doesn't do the right thing, there's the 0 and 1 that let you override the shape.

**Comment by rpspringuel** [comment]
So what are the conditions under which the determination algorithm is reset?  Is it only the presence of a note which isn't a punctum inclinatum?

**Comment by henryso** [comment]
Yes. It's the presence of a non-punctum-inclinatum.

**Comment by rpspringuel** [comment]
@olivierberten, given that this is as intended then, do you want some sort of fix (and if so, what would that look like)?

**Comment by olivierberten** [comment]
I guess no fix is needed as that kind of case never happens in real music. I was just trying to summarize different shapes when I bumped into that surprising behaviour... that actually makes totally sense in real cases.
