### ISSUE TITLE
Unison notes on the same syllable should by default not allow line breaks

### ISSUE THREAD

**Issue by jperon** [gregorio-project/gregorio#1504]
Here is a example illustrating the problem:

![Screenshot_20210123_211723](https://user-images.githubusercontent.com/4775231/105613344-39d17900-5dc2-11eb-83dc-b7bbef4b3d3f.png)

The actual behaviour is that this code:

```gabc
%%
(hff) (::)
```
gives following output from `gregorio`:

```tex
% File generated by gregorio 5.2.1
\GregorioTeXAPIVersion{5.2.1}%
\GreBeginHeaders %
\GreEndHeaders %
\GreBeginScore{fdfb0937e15f22d0431f6d53899bc3d9b4e7544f}{10}{8}{0}{0}{}{4}{\GreInitialClefPosition{3}{0}}%
\GreSetLargestClef{c}{3}{3}{c}{0}{3}%
\GreScoreOpening{%
}{%
\GreSetInitialClef{c}{3}{3}{c}{0}{3}{1}%
}{%
}{\GreSyllable}{\GreSetNoFirstSyllableText}{}{\GreUnstyled}{1}{\GreSetNextSyllable{}{}{}{}{}}{}{15}{}{%
\GreSyllableNoteCount{3}%
\GreGlyph{\GreCPFlexusLongqueueTwoNothing}{10}{\GreNextCustos{8}{}}{1}%
{%
\GreGlyphHeights{10}{8}%
}{}{}%
\GreEndOfElement{0}{0}{2}%
\GreGlyph{\GreCPPunctum}{8}{\GreNextCustos{9}{}}{0}%
{%
\GreGlyphHeights{8}{8}%
}{}{}%
}%
%
\GreFinalDivisioFinalis{%
}%
\GreEndScore %
\endinput %
```

IMO, the last `\GreEndOfElement{0}{0}{2}%` should be by default `\GreEndOfElement{0}{1}{2}%`, so that the two notes stay on the same line.

In fact, I think that, within a melism, any breakable space should be explicit (which was the behaviour "once upon a time", but I don't remember when this changed): for example, in `hGFgv`, the `gv` should stay with the `hGF`, unless a cut is added: `hGF/gv`. Perhaps it's more debattable when notes aren't unison ones, but (IMO again) it's really expected for unison ones.

**Comment by rpspringuel** [comment]
Have you tried changing `\gresetunbreakablesyllablenotes` to a number higher than 4 (the default)?  This was changed in response to #1044 which gave the user control over just how many notes stayed together.

**Comment by jperon** [comment]
I wasn’t aware of this macro. That said, the case I’m highlighting isn’t IMO a matter of *number*, but rather a matter of *elements* that should have an unity: whatever be the number of notes in a melisma:

- the two notes of a *distropha* and the three ones of a *tristropha* (be this distinction meaningful or not isn’t the point : it’s a fact it exists in practice) should stay together without explicit `!/` (that moreover make the gabc code quite dirty), event when typed as a sequence of *punctum*s (as in 1960 books) ;
- a *climacus resupinus* (`hGFgv` mentionned before) shouldn’t be divided by default.

The proposal in #1505 would make an explicit `/` necessary between neumatic elements, but:

- it’s already necessary in many cases anyway;
- even when it’s not necessary with the current behavior, it would be cleaner than, for example, than having to type `h!/hh!/h!/h` to ensure "a distropha, then a breakable cut (implicit), then a tristropha" (which may occur in the middle of a melisma, thus not covered by `\gresetunbreakablesyllablenotes`).

This proposal wouldn’t even make `\gresetunbreakablesyllablenotes` useless: it would (as it’s the case now) ensure not too few notes before and after a line break.

**Comment by rpspringuel** [comment]
I'm still not entirely sure I understand the issue.  Can you throw together some test cases (preferably in the test repository) which show the problem when your fix is not applied and are correct when it is?

**Comment by henryso** [comment]
I think this is a matter of style. The old way was inconsistent, so the decision was made that breaks would be allowed between elements regularly unless they are "glued" together by non-breaking spaces.  This would allow the scores to be placed in any width containers with predictable line breaks (like putting a paragraph into a document).  Then the engraver would tweak the score as necessary to deal with spacing, etc.  You can argue the opposite probably as vehemently and correctly, so this is probably something where the default behavior is configurable.

**Comment by rpspringuel** [comment]
Is it just me, or is #1473 making a complaint about almost the exact opposite problem?

**Comment by eschwab** [comment]
It would seem so. I'm in agreement with @henryso's comment above. Glue and breaks can be added as the engraver sees fit.

**Comment by fiat96** [comment]
As one who has come across this line breaking all too often myself, I thought I'd put my two cents out there.

Any time two neums (or two notes) meet at the same note on the same syllable, no singer of chant I know would tolerate a line break.  Several instances have slipped into my scores in the past, and they're always pointed out to me as errors.  Thus, I would say that `ghhg` should be unbreakable, as should `ighhg` or `ghh`.  This is because, according to the Solesmes method, the two notes on the same pitch are blended into a _pressus_.  If the first note is the last on a line, the singers will fail to recognize the pressus in time, and familiar tunes and patterns will look weird.  Writing in `!/` at every possible bad line break is cumbersome.

An exception would be a line break between a distropha or tristropha and another neum, which does not form a pressus (`ggggh` or `fggg`).

The issue in #1473, on the other hand, is that the following long neum was rendered unbreakable:
(gfHHhvFEfHHh)
![image](https://user-images.githubusercontent.com/62146958/107454534-d3af5a80-6b12-11eb-9819-c23de5e081f6.png)

I think this is the result of a desirable implementation, as I have commented there.

**Comment by fiat96** [comment]
In summary, then, I would like to propose that Gregorio forbid a line break between two consecutive notes that are: 
- on the same pitch,
- within the same one syllable, and
- not separated by a bar.

I do not see any such line breaks in my liturgical books.

**Comment by henryso** [comment]
If we can get agreement on this set of rules, I can try to implement it, but this will be a major version update, and till happen after TeXLive 2021.

**Comment by jperon** [comment]
Sorry for my silence: I’m quite busy for now, and didn’t find time to reply to @rpspringuel.
I’d agree with @fiat96’s proposal.

**Comment by henryso** [comment]
Ok, any objections to @fiat96's proposal?  I'll start working on this for 7.0 if not.

**Comment by fiat96** [comment]
Parenthetically...

I mentioned earlier that I didn't see any line breaks like those condemned by my proposal in the liturgical books.  I spotted one yesterday in the Liber Usualis for Palm Sunday's Gradual, so I felt conscience-bound to mention it:
![image](https://user-images.githubusercontent.com/62146958/111054801-2e4f1580-8435-11eb-9f19-450524dfa78e.png)

It's actually a rather unique neum anyway, since the two notes in question, being immediately preceded by a note with an ictus, don't form a pressus.  I still hold to my proposal, since rare cases like these could be marked with a break if the typesetter desires.

**Comment by henryso** [comment]
I think if the vast majority (or even just the majority) of cases is to keep them together, then I don't disagree with you.

**Comment by henryso** [comment]
I tried implemented this three ways and nixed two of them because I didn't like how they ended up (the first try injected new elements and the second try injected non-breaking spaces between the glyphs).  This final implementation seems satisfactory as it only alters the interpretation of the data structures and is configurable from TeX.  It will default to `breakable` unison notes to maintain backwards compatibility, but can be set to `unbreakable` with `\setunisonbreakbehavior{unbreakable}`

**Comment by henryso** [comment]
@fiat96 @jperon I've merged the changes into the develop branch.  The behavior is controlled by `\gresetunisonbreakbehavior{breakable}` or `\gresetunisonbreakbehavior{unbreakable}`, with the former being the default for better backwards compatibility.  Please try it out if you can and let me know.

**Comment by henryso** [comment]
Closing this since it's been merged.  Please re-open if you find bugs (or report a new bug, whatever works).
