### ISSUE TITLE
Clarify TeXworks/TeXShop workflow and installation

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#175]
I'm currently building [an updated version of the website](http://gregorio-project.github.io/), simpler, easier to maintain (only one language, for gregorio > 3.0 only). I'm currently updating the TeXShop/TeXworks page, but as I don't use these, I'm not sure about the best way to do it...

From what I understand, the workflow that should be advised by Gregorio (>= 3.0) should be the one involving

    % !TEX root = test.tex
    % !TEX TS-program = LuaLaTeX

in the `.gabc` scores, is that so? If it is, I'll update the example to use these.

Also, here are a few thoughts:
 * it would be better to have a configuration page for TeXShop, a configuration page for TeXworks and a common introduction page, what do you think? The introduction pages are almost the same right now.
 * instead of making users compile all their LuaLaTeX documents with `--shell-escape`, maybe it would be better to make them create a `LuaLaTeX+se` engine that would be the equivalent, keeping the LuaLaTeX engine safe (which is the whole point of not having `--shell-escape` enabled by default), what do you think? This is quite important to figure out before 3.0, as it will change documentation, examples, etc.

**Comment by eroux** [comment]
Another point: should the Windows installer hack TeXworks configuration? I tend to believe that pointing to [the page on the website](http://gregorio-project.github.io/installation-texworks.html) would be easier to maintain, cleaner and not really more difficult to the end user (with a few screenshots). What do you think?

**Comment by henryso** [comment]
Note: I use neither TeXShop nor TeXworks, so my opinion here might just be nonsense.

* Separate configuration pages is definitely the way to go
* Do we even need an introduction page?  What would be on it?
* I am in favor of keeping the LuaLaTeX engine safe and creating a new engine with --shell-escape.

**Comment by eroux** [comment]
I opened #176 for a proposal.

For the record, I also opened [this TeXworks issue](https://github.com/TeXworks/texworks/issues/691) that could help in the future...

**Comment by eroux** [comment]
by the way, don't hesitate to proofread the new website and open issues [here](https://github.com/gregorio-project/gregorio-project.github.io/issues)

**Comment by rpspringuel** [comment]
It will be easier on novices if the configuration pages are separate for each program. While TeXShop and TeXworks are very similar (by design, TeXworks is imitating TeXShop) there are enough subtle differences that I think having the separate pages is worth while. 

Having a separate LuaLaTeX engine with shell escape enabled makes sense for the security conscious.  It'll also make the configuration instructions easier for TeXShop. 

Those are the correct header lines, though if we add a new engine we'll need to edit them accordingly. 

As is the Windows installer is only able to configure TeXworks for the administrator who installs Gregorio, so we need the manual configuration instructions on the website anyway.  Unless we can solve that issue, I don't mind dropping the configuration script from the installer.

**Comment by eroux** [comment]
I separated the pages on the new website
