### ISSUE TITLE
README.md et al. links

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#198]
Can we make the links in README.md et al. that point to the other markdown documents into absolute links whose target is the file in the repository rather than relative links?

I.e. instead of `[CHANGELOG.md](CHANGELOG.md)` we would have `[CHANGELOG.md](https://github.com/gregorio-project/gregorio/blob/master/CHANGELOG.md)`.

The reason I ask is that when I put README et al. in the Mac installer, the relative links end up as dead links (i.e. they don't go anywhere because the relative location doesn't exist).  If we have them directed to the appropriate repository file, then they remain linked to something which actually exists.

**Comment by eroux** [comment]
The drawbacks I see are:

 * links are going to be on master only, so they'll be wrong on branches
 * markdown more difficult to read in plain text

but honestly it's not blocking at all.... otherwise there could be a `sed` script detecting all links not starting by `http` and prefixing them with the complete url. Would it be hard? If so, we can definitely put absolute links directly.

**Comment by rpspringuel** [comment]
Hadn't thought about that.  I'll look into creating a `sed` script that adds the necessary information to the converted file.

**Comment by rpspringuel** [comment]
Got a `sed` script working.
