### ISSUE TITLE
enhanced parsing of liquescences

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#20]
gabc `gwhi>` should be the same as `gwh!i>`

**Comment by henryso** [comment]
`(gwhi>)` is currently determined to be a scandicus auctus descendens.  However, since scandicus cannot begin with a quilisma, I can change this determination to be a quilisma-pes followed by a punctum auctus descendens, but that would be equivalent to `(gwh/i>)`.  The user would still need to do `(gwh!i>) if they really want the notes right up next to each other.  Is that satisfactory?  Or maybe I'm misunderstanding this issue?

**Comment by henryso** [comment]
@eroux Do you have any thoughts on this?

**Comment by eroux** [comment]
Sorry, I think that would be satisfactory yes... but I admit I can't remember the background for this issue... Let's do it the way you said.
