### ISSUE TITLE
add virga aucta for liquescens salicus

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#21]
A new virga aucta symbol is requested.

Shape:

![virgaaucta](https://cloud.githubusercontent.com/assets/60868/5610758/a22b0a32-94bc-11e4-9b55-3443804ba68d.png)

gabc:

`iV>`

use:

used in the Nocturnale Romanum (2002) p. 242, in a salicus (`GHiV>`, as represented in the above picture), corresponding to a liquescens salicus, nabc `- sa>2`.

**Comment by olivierberten** [comment]
This looks very similar to a regular virga... Holger Peter Sandhofe used to have much more characteristic liquescences. See http://web.archive.org/web/20070715191323/http://www.nocturnale.de/pdf/Quadratnotation.pdf

**Comment by eroux** [comment]
The shape should be a mix between a virga and a punctum auctum... Anyway, thank you very much for the link to the pdf! The main thing I see that are missing from Gregorio are:

 * quilisma duplex (and the various combinations)
 * strophicus liquescens (which design is very pretty by the way)

Did I miss anything else?

Also, is there any known heir to HPS? It's kind of a shame that all his work got lost... It would be great to have it public-domained and freely available... also, I admit I'd ask to take the strophicus liquescens design into Gregorio (which I might do if there is no known heir).

**Comment by olivierberten** [comment]
Most of his online works are available on musica sacra: http://media.musicasacra.com/pdf/HPS/

You may try contacting his publisher, who stopped his business: Christof Schroeder <cns@hartker.com>

**Comment by eroux** [comment]
Thanx, I'll do that!

**Comment by jakubjelinek** [comment]
Here is how it looks like in Nocturnale Romanum.  The virga aucta is smaller to what is in the first comment, but only because the i> looks similarly - see STELla for h> and videRANT for iV>.

![nocturnale](https://cloud.githubusercontent.com/assets/9370665/5614598/f945ad14-94f2-11e4-9760-d78fa5a76639.png)

**Comment by grzegorzrolek** [comment]
I think the probable reason why Greciliae’s _punctum auctum_ looks that much neutral is because originally the Caeciliae’s glyph for _punctum auctum_ was used mainly in _cephalicus_ or _epiphonus_ as the ‘punctum’ base, the ‘liquescence’ form of which is more of a support for the following, proper liquescent note, thus doesn’t have to be that much explicit.

But it appears that back in the early days Greciliae took the Caeciliae’s _auctum_ as is, and got itself a new shape for the base of _cephalicus_ etc. (and a rather flat one if you consider the overall Caeciliae’s character, by the way). It should, in fact, be the other way around: Caeciliae’s _auctum_ should form the base of Greciliae’s _cephalicus_ etc., and a new shape with enough ‘liquescence’ should be drawn for _punctum auctum_, and for that matter _virga aucta_.

My take on Olivier’s issue would thus be to simply move the current Greciliae’s _auctum_ outline to the slot that now serves as the base of _cephalicus_ and _epiphonus_, and to redraw the _auctum_ with a more distinctive liquescence. Élie, what do you think?

**Comment by eroux** [comment]
https://github.com/grzegorzrolek , your idea is interesting, and you might be right: maybe gregorio should have more distinct liquescence glyphs. 

I though I find those from Nocturnale Romanum rather ugly though, the drawings of Gregoria for instance are ways better (I can paste a screenprint if you want, they look more than those of the "Gregorio" font).

But I'm not sure I'm following all your thoughts, if you look at Caeciliae Tutorial from [latest caeciliae](http://marello.org/caeciliae/downloads/), the output is the same as Gregorio... can you give a more precise example?

Thanks!

**Comment by eroux** [comment]
Jakub, can you please test branch `fix-21`? If it suits your needs, I'll merge it with master and nabc.

**Comment by grzegorzrolek** [comment]
Oh, the tutorial doesn’t mention _punctum auctum_ explicitly (it talks about the liquescent neumes as a whole), and I must have assumed at the time I read it, that the auctum as a standalone glyph is an afterthought of the shapes used for the liquescents. But now I see from the examples, that they both likely have an equal status in Caeciliae.

But the fact remains that Caeciliae doesn’t have separate shapes for liquescents and the aucta, and the shape had to be quite neutral to be used in both scenarios.

Regarding the particular drawing for the auctum, Gregoria is indeed nice and likewise in many other ways, but it’s still a different typeface. Both Gregorio and Greciliae should get an individual treatment that would go nicely with each one’s design. For example, I really do think that current Greciliae’s _cephalicus_ and _epiphonus_ have their bases a bit too flat for a rather full and curvy cut of the original Caeciliae. That’s exactly why I’d copy the current _punctum auctum_ in their place, and then redraw the original one with a deeper curvature, or possibly with an additional little tail or the like. For what it’s worth, this tail or a hook is the most distinctive feature of all the liquescent neumes, and one that have its origins in the earliest notations, so it could be a nice idea to reconsider it as part of the Greciliae’s design.

**Comment by eroux** [comment]
@grzegorzrolek , if others agree, what I can do is an alternate version of Greciliae, something like `greciliae-sa` (for `strong aucta`, but it's just the first thing that crossed my mind). And if everyone seems convinced, I can make it the default.

Unlike what one might think, I'm no gregorian expert (and, actually, I'm not a Gregorio user myself, I just maintain it because I think it's useful to some people), so if you could give a few gabc example for everything you just told, I'll formalize it into requests that I understand better :)

**Comment by grzegorzrolek** [comment]
No worries, I will file separate issues myself in the upcoming days with some illustrations and we’ll see what people think.

**Comment by eroux** [comment]
Ok thanx!

**Comment by jakubjelinek** [comment]
Branch fix-21 looks good to me.  If you merge it to master, can you please also merge master to nabc branch afterwards, so that there is both this fix and the ocba fix?  Thanks.

**Comment by eroux** [comment]
done!
