### ISSUE TITLE
distclean not cleaning subdirectories

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#237]
I noticed this in particular in the doc folder, but it may be happening elsewhere as well.  @eroux [has noted](https://github.com/rpspringuel/gregorio/commit/1d250e22cc2a7317009e86427317c2a8ae744c05#commitcomment-10588920) that a `distclean-local: clean-local` is needed, but I don't know where it should go.

Personally, I think this is a bug fix to the distribution files and should be fixed as part of 3.0.0

**Comment by henryso** [comment]
That line should go in the `doc/Makefile.am`.  I don't think it'll work properly in `release-3.0` because the change from `clean` to `clean-local` is currently only in `develop`.

I don't think this needs to be part of 3.0.0 because `distclean` is really something used more by the people making the distribution files than the people using the distribution files.  Not having `distclean` won't break anyone trying to use the tarballs in the typical way.

**Comment by eroux** [comment]
I admit I don't understand the issue... do you have a concrete example?

**Comment by rpspringuel** [comment]
Go through a build process that builds the documentation (such as `make doc` in the doc folder).  Then, from the root folder enter `make distclean`.  If you look, the documentation build files (the pdf and all the auxiliaries) will still be there when the command is done.

This is why I have both `make clean` and `make distclean` in my script that builds the Mac installers.

**Comment by eroux** [comment]
Oh, ok I remember the context now, I'll do that.
