### ISSUE TITLE
english centering scheme should be available as TeX option

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#27]
having the centering scheme set in gabc was, I believe, as mistake (though, now, it will stay). But it should be possible to set "English" centering scheme from TeX, for scores with a normal gabc centering scheme.

**Comment by rpspringuel** [comment]
A quick look at the TeX and my idea for implementing this is as follows:
1) Create a new global count to function as a boolean, `\gre@englishcentering`
2) Create user functions which set the value of this count to 1 (use English centering scheme) or 0 (use what is specified in the gabc score)
3) Add variables `\gre@firstsyllablepart` `\gre@middlesyllablepart` and `\gre@endsyllablepart` and to `\gresyllable` and use these instead of references to arguments `#1`, `#2`, and `#3`.
4) Add a check at the beginning of `\gresyllable` which maps the arguments to the new variables based on the value of the new count.

Assuming I haven't missed anything, I should be able to implement this fairly quickly.

**Comment by eroux** [comment]
I can't see any reason no to close it... Tell me if there is some!

**Comment by rpspringuel** [comment]
No reason.  I just forgot to close it when I merged the commit.  Sorry.
