### ISSUE TITLE
Documentation on macros callable by the user.

### ISSUE THREAD

**Issue by eschwab** [gregorio-project/gregorio#29]
There is a lack of good documentation on macros that the user can call in his main TeX file. I am aware of the list here: http://home.gna.org/gregorio/gregoriotex/details but it is out of date.

It would be helpful to have a list of macros. A simple item/definition list in plain text or markdown would possibily suffice. I am willing to work on this.

**Comment by eroux** [comment]
You're right, this will be very helpful! Markdown is enough yes.

**Comment by rpspringuel** [comment]
This is part of what's taking me so long to finish establishing a macro naming convention; I'm documenting the macros as I go.  Take a look at the Command_Index_* files in the texrenaming branch in my fork.  I've created a pull request (#30) to update the base fork's texrenaming branch to make finding them easier. 

Since I've been documenting things as I go, the documentation reflects the naming convention I'm headed towards rather than the current working state (with a couple of exceptions I haven't yet decided how to deal with).  Still, it should be useful as a starting point if you want to make use of it.

**Comment by eschwab** [comment]
@rpspringuel Your Command_Index_* files are mostly what I was looking for. After #33 is merged I may consider adding examples or something to help out a new user. Would need to find a way to keep it simple to not interfere with the cleanness of the Command_Index* files.

A doc/ section might be helpful and a more obvious location. But, I don't want to introduce multiple lists of macros for maintenance's sake. Just bouncing ideas around at the moment.

**Comment by rpspringuel** [comment]
The only reason for them being in the tex/ folder is because that's where I started my work and I felt my time was better used at this point continuing with the work needed to establish the naming convention rather than cleaning up my working documents.  If you want to start a proper doc/ section in the repository, feel free.  I can always add to them documents in their new location.

It was always my intention to eventually spruce up the Command_Index_* files to make them fully typesettable (and/or converting them to html format for posting on the website).  I'd also hoped, one day, to add examples for the User commands, as I don't expect that the average user would necessarily understand the simplistic, code oriented documentation I've written thus far.  Said day, however, is still well in the future for me.  I'd actually be delighted if you got to (some of) it before me.

**Comment by eschwab** [comment]
Fixed with #34.
