### ISSUE TITLE
PlainTeX compatibillity

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#319]
In order to be future-proof, and be able to use Gregorio in LaTeX3, ConTeXt, Lilypond (who knows), it's important not to depend on LaTeX. One way to test it very simply is to try to compile the following:

    \input gregoriotex.tex
    \input gregoriotex-symbols.tex
    
    \includescore[a]{PopulusSion}
    
    \bye

Currently, `gregoriotex.tex` loads `graphicx.sty`, incompatible with PlainTeX.... It is used for `\resizebox` to make square brackets above notes fit a certain width, but it could be implemented in another way.

**Comment by eroux** [comment]
If I understand correctly, `graphicx` is not compatible with Plain anymore, but it used to be. `graphics` also seems to provide `\resizebox`...

**Comment by henryso** [comment]
On my system, `graphicx.sty` requires `graphics.sty` which requires LaTeX, so that won't work.  On the other hand, `graphicx.tex` in `tex/plain/graphics-pln` apparently does something to allow `graphicx.sty` to load under plain TeX.

**Comment by henryso** [comment]
There are a couple of other problems just loading `gregoriotex.tex` into plain TeX:

- `\f@size` doesn't exist, but we can shim that over with Lua code
- `\gre@debug` is not set because that's done by `kvoptions` in `gregoriotex.sty`; we can define a dummy version if it's not already set.
- the @ sign is catcode 12

I've gotten something working where I renamed `gregoriotex.tex` to `gregoriotex-main.tex` and put workarounds for the above issues into a new `gregoriotex.tex` file.  I made the `.sty` do the LaTeX-based loading and the `.tex` file do the `\input`-based loading.

So, for LaTeX, you would `\usepackage{gregoriotex}` and for plain TeX, you would `\input gregoriotex.tex`.

A pull request is forthcoming.  I'm not entirely convinced I've done it right, so I'd appreciate an external review.

**Comment by eroux** [comment]
I cannot reallh review your code correctly (on a smartphone), but what you
did seems good. You can inspire from luaotfload or lualibs that defind a
sty common to LaTeX and plain, but what you did is ok. I think the
resizebox thing is used to scale the curly braces above notes if you want
to test it. Thanx!

**Comment by henryso** [comment]
The brace tests are up at https://github.com/gregorio-project/gregorio-test/tree/master/tests/plain-tex/braces, and they are satisfactory.  I don't fully understand what luaotfload is doing in `luaotfload.sty`, so I've merged the changes for now.  I will leave this issue open so that there is more time to review the change and also to give me time to do research into how to approach the LaTeX vs. plain TeX inclusion issue.

**Comment by henryso** [comment]
After some research, I think I actually like it better with a separate `gregoriotex.tex` and `gregoriotex.sty`.  It's actually optional in plain TeX to omit the `.tex` extension of the file, so you are able to simply `\input gregoriotex` to use GregorioTeX in plain TeX.  Unless anyone has strong opinions on this matter, I will leave it like that.

**Comment by eroux** [comment]
No problem!

**Comment by henryso** [comment]
Any other comments/review notes on this?  If not, I'll close it in a day or so.

**Comment by eroux** [comment]
Ok
