### ISSUE TITLE
horizontal episemus bridge not always appearing

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#389]
A bridge should be done for these two cases:

- the most simple: `hg__hof__`
- a bit more complex: `hg__gof__`, gregorio should detect that the episemi are in the same line interval and thus "merge" them

The fix might not be too complex, it might be in `determine_h_episemus_top_note` (iirc)

**Comment by henryso** [comment]
Can someone explain to me when `\grehepisemusbridge` is supposed to be generated?  From reading the code, it seems this only happens if a note with an episemus that is not following a note with an episemus is followed by puncta inclinata.  Is that correct?

**Comment by eroux** [comment]
I admit this is a very distant memory... but doesn't it work for bivirga, trivirga, etc. too?

**Comment by henryso** [comment]
I don't know how/when/why it works.  The code is confusing me.

**Comment by henryso** [comment]
What I missed was that `\grehepisemusbridge` will also appear if there are no more notes in the current glyph.  What I don't quite understand is the additional condition that there either be no previous note in the glyph or that the previous note be without an episema.  I'm having trouble translating this logic into the rewrite of the positioning code.  I think I'll just have to do what I can and then pick up the pieces as they fall.  Also, I think we should put 4.0 through a beta period because of all the changes.
