### ISSUE TITLE
kpse-safe version

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#415]
With inclusion in TeXLive in mind, I asked the texlive mailing list if it was possible in the current state, on [this thread](http://tug.org/pipermail/tex-live/2015-May/036780.html). Nothing is decided yet, but you can give your ideas here!

**Comment by eroux** [comment]
I've started a kpse branch in the main repo with a few experiments to link against kpathsea, install `libkpathsea-dev` under Debian... is kpathsea dev also available under other distributions? What about Mac? apparently the texlive from macports adds it, but I'm not sure MacTeX does...

**Comment by eroux** [comment]
@henryso after a few experiments, kpse restriction `openout_any=p` (the default under Debian) doesn't allow absolute paths (see the current state of `kpse` branch). I wanted to make `define_path` (in `gregorio-utils.c`) not use absolute path when unneeded, but, as it is your code, I was wondering if this change might induce some side effects?

**Comment by henryso** [comment]
@eroux It might.  The purpose of this code is to prevent the user from clobbering the input file accidentally.  Maybe there's a better way to detect this case without getting the absolute path of the input and output files.

**Comment by eroux** [comment]
I see... Well, the conversion to absolute path could be made in `check_input_clobber` without modifying the file names used to open the files?

**Comment by henryso** [comment]
Yes, if that is satisfactory.

**Comment by eroux** [comment]
Ok, doing that

**Comment by rpspringuel** [comment]
I just read the discussion over on the TeXLive list.  Based on what was posted over there, if we go this route (which I agree is a good idea) we'll only be able to make "official" releases (as in releases through the TeXLive distribution) to the C code 1/year.  It thus might be a good idea to adopt an alternative development model with 2 separate develop branches.  One branch would be for features that require modifications to the C code, the other would be for features which don't require any changes to the C code.

Of course, we have about a year to figure this out, as the earliest we'll be able to get into TeXLive is 2016 (since 2015 is already frozen in preparation for release).

**Comment by henryso** [comment]
It *might* be a better idea to branch for TeX Live.  So we develop in `develop`, merge into `master` for non-TeX Live releases, and merge into `texlive` for TeX Live releases.  Mid-year bug fixes that are allowed within TeX Live rules would be developed in a temporary branch against `texlive`, merged into `texlive` once vetted, and then merged from `texlive` into `master` and from `master` into `develop`.
