### ISSUE TITLE
Clivis with 2 puncta mora

### ISSUE THREAD

**Issue by jakubjelinek** [gregorio-project/gregorio#424]
Is it intentional that we typeset (h.f.) or (i.h.) differently from (hf..) or (ih..) ?
Just noticed last night, I've been using those two interchangeably, but the liturgical books I've looked at always use the (hf..) or (ih..) way apparently, with both puncta mora above each other, rather than one above the second (lower) square note.

**Comment by henryso** [comment]
I can't speak for the original intent, but your case certainly was not anticipated by the current code.  The only way for the `_AUCTUM_DUPLEX` sign to be added to a note is if there are two adjacent dots in the gabc.  That's not probably telling you much, but as to if/how this should be fixed, I think we need clearer direction, especially since one can do really weird things with dots in a multi-note neume.

**Comment by eroux** [comment]
It is intentional yes, it's just to have more flexibility, there might be some edge cases where `(h.f.)` might be useful...

**Comment by jakubjelinek** [comment]
Ok, perhaps the documentation should mention that somewhere (e.g. in a quick reference page show both), so that users are aware of this.

**Comment by eroux** [comment]
Indeed, gabc documentation needs a lot of updates and improvements...

**Comment by eroux** [comment]
BTW, here is an example, beginning of second line: http://gregobase.selapa.net/chant.php?id=2267
