### ISSUE TITLE
`Package keyval Error: autogobble undefined` while compiling gregorio

### ISSUE THREAD

**Issue by jperon** [gregorio-project/gregorio#498]
I'm on 3775cac ; while compiling debian package, I get this error.
Here are the last lines of the message : 

```
(/usr/share/texlive/texmf-dist/tex/latex/bookhands/ot1cmin.fd)) [1{/var/lib/texm
f/fonts/map/pdftex/updmap/pdftex.map}] (./GregorioRef-3_0_2.toc)LuaTeX warning (
ext4): destination with the same identifier (name{page.1}) has been already used
, duplicate ignored
<to be read again> 
\relax 
l.146 \cleardoublepage
                     [1]
Overfull \hbox (5.73155pt too wide) in paragraph at lines 154--157
[][][] 
(./Command_Index_User.tex [2]

! Package keyval Error: autogobble undefined.

See the keyval package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.55 \begin{latexcode}
                    
? 
```

**Comment by henryso** [comment]
I guess `autogobble` is too new a feature in the `minted` package (it's not part of TeX Live 2014 on my system).  I'll take it out for now.  One level of indentation in the listings doesn't look too bad.

**Comment by eschwab** [comment]
@rpspringuel added `autogobble`. He changed it from `gobble=2`, not sure why.

**Comment by rpspringuel** [comment]
I changed it from `gobble=2` because I convert the indentation in the TeX files from 2 spaces to tabs in my working directory.  Since the tab is only a single character, gobbling the first two characters was gobbling the first character in each line of code.   Switching to `autogobble` fixed that and I figured it would still work for everyone else. I didn't realize how recent an addition to the package it was.
