### ISSUE TITLE
oddities with annotationseparation

### ISSUE THREAD

**Issue by jperon** [gregorio-project/gregorio#508]
Perhaps I miss something, but `\grechangedim{annotationseparation}{VALUE}{0}` doesn't seem to work as expected. This "mwe" illustrates it : 

![mwe](https://cloud.githubusercontent.com/assets/4775231/8213811/015ed14e-1525-11e5-8307-9e2d84f0be44.png)

~~~~~~~~
\documentclass[a5paper,11pt,DIV=17]{scrartcl}

\usepackage[autocompile]{gregoriotex}
\usepackage{libertine}
\usepackage{calc}
\pagestyle{empty}
\grechangestaffsize{13}
\newlength\tmpsize
\setlength\tmpsize{\grefactor pt}
\def\greinitialformat#1{{\fontsize{2.5\tmpsize}{2.5\tmpsize}\selectfont #1}}

\begin{document}

First, let's show default behaviour :

\greannotation{\scriptsize Test}
\greannotation{\scriptsize 1.}
\gabcsnippet{(f3) Dó(f)mi(fgf___)ne.(f.,ef!hhkxi./jkI'Gh_ihhf.) (::)}

\smallskip
Here, one would expect second annotation to "touch" the first :

\grechangedim{annotationseparation}{0mm}{0}
\greannotation{\scriptsize Test}
\greannotation{\scriptsize 1.}
\gabcsnippet{(f3) Dó(f)mi(fgf___)ne.(f.,ef!hhkxi./jkI'Gh_ihhf.) (::)}

\smallskip
So, let's try a negative value : one would expect the first not to move, but the second to raise ;
the space between annotations stays the same, and both raise.

\grechangedim{annotationseparation}{-2mm}{0}
\greannotation{\scriptsize Test}
\greannotation{\scriptsize 1.}
\gabcsnippet{(f3) Dó(f)mi(fgf___)ne.(f.,ef!hhkxi./jkI'Gh_ihhf.) (::)}

\smallskip
With a positive value, the second annotation is lower, but the first too (which is counter-intuitive) :

\grechangedim{annotationseparation}{3mm}{0}
\greannotation{\scriptsize Test}
\greannotation{\scriptsize 1.}
\gabcsnippet{(f3) Dó(f)mi(fgf___)ne.(f.,ef!hhkxi./jkI'Gh_ihhf.) (::)}

\end{document}
~~~~~~~~

**Comment by rpspringuel** [comment]
I think I can explain what is going on:

1. I can't close the gap between the lines in an annotation beuond a certain amount. 

When boxes are stacked inside a vbox there is normally a certian minimum gap between the lines.  This can be turned off with a `\offinterlineskip` command at the beginning of the vbox.  Given what you're observing, I'm fairly certian I forgot this command. 

2. I can't get the annotation lunes to overlap. 

In order to get lines of text to overlap, one has to trick TeX into thinking the height and/or depth of the text is less than it actually is.  The code to fill the annotation box doesn't implement any of this trickery so negative values of `annotationseperation` are effectively 0.

3. When I chang `annotationseperation`, but not `annotatioraise` the top line of the annotation moves.

This is probably happening because there isn't a separate check to see if the annotation is empty before building the box.  As a result, when the first line is populated what is actually being comdtructed is a composition of an empty box, the seperation distance, and the first line.  What is needed is a check to see if the box is empty, and if it is to build it slightly differently. 

Issues 1 & 3 are bugs in the current implementation.  Issue 2 is a limition of the implementation which could only be overcome by a complete overhaul of how the box is created.

**Comment by rpspringuel** [comment]
Correction: the check to see if the box is empty is there, the problem is that the spread is still used in the construction of the box when we are on the first line.

**Comment by henryso** [comment]
Based on @rpspringuel's explanation, I tried the following patch:
```
--- a/tex/gregoriotex-main.tex  Sat Jun 27 11:13:06 2015 -0400
+++ b/tex/gregoriotex-main.tex  Sat Jun 27 11:58:22 2015 -0400
@@ -458,10 +458,10 @@
     \gre@debugmsg{annnotation}{Initial set point.}%
     \global\gre@dimen@annotationtrueraise= 0.8em\relax%
     \global\advance\gre@dimen@annotationtrueraise by -\dp\gre@box@annotation@add%
-    \setbox\gre@box@annotation = \hbox to \gre@dimen@temp@three{\vtop spread \gre@dimen@annotationseparation{\vss\noindent\box\gre@box@annotation@add}}%
+    \setbox\gre@box@annotation = \hbox to \gre@dimen@temp@three{\vtop{{\offinterlineskip\vss\noindent\box\gre@box@annotation@add}}}%
   \else%
     \gre@debugmsg{annotation}{We're not on the first line of the annotation.}%
-    \setbox\gre@box@annotation = \hbox to \gre@dimen@temp@three{\vtop spread \gre@dimen@annotationseparation{\noindent\box\gre@box@annotation@old\vss\noindent\box\gre@box@annotation@add}}%
+    \setbox\gre@box@annotation = \hbox to \gre@dimen@temp@three{\vtop spread \gre@dimen@annotationseparation{{\offinterlineskip\noindent\box\gre@box@annotation@old\vss\noindent\box\gre@box@annotation@add}}}%
   \fi%
 }%
```
This is what I get:
![image](https://cloud.githubusercontent.com/assets/421318/8392782/f3b42f0c-1cc3-11e5-88da-438ec899f5ca.png)

**Comment by eschwab** [comment]
Works for me.

**Comment by henryso** [comment]
@eschwab Thanks.  I submitted the pull request.
