### ISSUE TITLE
Triggering End of Line Shifts

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#584]
I'm having trouble figuring out the conditions that are supposed to trigger an end of line shift.  Based on my reading of the code, here's what I'm seeing:

1. End of line shifts should be triggered only when `\gre@lastoflinecount` is `1` _after_ the syllable text is printed.
2. `\gre@lastoflinecount` is set to `1` by `\GreLastOfLine` (`\GreLastOfScore` does so too, but for the moment I'm only going to worry about `\GreLastOfLine`).  This command only appears in a gtex file when an explicit line break is coded in the gabc (i.e. we find a `z` or `Z` somewhere).  It appear in argument `#8` for `\GreSyllable` (the code executed before placing the syllable)
3. If we have a `z` or `Z` in the score, then we'll also get a `\GreNewLine` or `\GreNewParLine` in the score.  Specifically these appear as part of argument `#9` for `\GreSyllable` (the syllable notes).
4. Both `\GreNewLine` and `\GreNewParLine` call `\gre@newlinecommon` which, as part of it's operation, sets `\gre@lastoflinecount` to 2 when printing the syllable text (as opposed to boxing it up).

As a result, `\gre@lastoflinecount` is **never** `1` when it comes time to apply the eol shift and thus said shifts are never applied.

Something tells me this state of affairs isn't intentional, but I'm not sure of what the intended behavior should be in order to fix it.

**Comment by eroux** [comment]
I think point1 is wrong, the reason is a bit complex though... First you need to understand how TeX "trims" spaces at the beginning and end of line and how GregorioTeX uses it to have some special shifts at beginning and end of lines, see [this comment](https://github.com/gregorio-project/gregorio/blob/develop/tex/gregoriotex-syllable.tex#L528) for more explanation (don't worry if you don't understand it at first reading, this really isn't obvious).

So, eolshift must be triggered at each syllable (whatever lastoflinecount). But so is bolshift... thus I don't really understand [the conditional](https://github.com/gregorio-project/gregorio/blob/develop/tex/gregoriotex-syllable.tex#L541). I think what's happening is that due to the [commented line](https://github.com/gregorio-project/gregorio/blob/develop/tex/gregoriotex-syllable.tex#L846), and the fact that lastofline is initally 2 (which could be made more obvious by setting it to 2 at each score beginning). So all syllables get a lastofline of 2 and the conditional is always true... at least that's what I guess, this should be tested...

**Comment by eroux** [comment]
I've made a [small snippet](https://gist.github.com/eroux/e05e52dbd10db45d1c41) (compile with luatex, not lualatex) showing the mechanism used by GregorioTeX, this should be more understandable than the comment.

**Comment by eroux** [comment]
@rpspringuel what do you think about https://github.com/gregorio-project/gregorio/commit/924804fe9b39d97ca72ee27832c0a772b284b7ca ? Does it help? Also, tell me if you need more information on this.

**Comment by rpspringuel** [comment]
Okay, I've had a chance to look and while the changes make some of the logic clearer (especially for the beginning of line shifts), they aren't changing the fundamental problem I identified above.  End of line shifts can only be triggered if `lastoflinecount` is 1 after syllable text is printed, but the only syllables which change `lastoflinecount` to 1 (those which call `\GreLastOfLine`) also change it to `2` when they print (via `\gre@newlinecommon`), making it impossible to trigger the end of line shift.

As I understand it, the end of line shift is supposed to allow the text of the lyrics to go under the custos at the end of a line.  Thus it should be triggered under the following conditions:

1. The user wants it to happen (`\ifgre@eolshiftsenabled` evaluates to true)
2. We are at the last syllable of a line (`\gre@lastoflinecount` is 1 prior to printing the syllable)
3. The text for this syllable is longer than the notes above them (`\gre@dimen@enddifference` is negative).
4. We are printing a custos at the end of the line (`\ifgre@blockeolcustos` evaluates to false)

If all 4 of the above conditions are met, then we want to shift left by the width of a custos and the space before the custos.  Otherwise, there should be no shift.

Does that about sum up what the end of the line shift is supposed to do?

**Comment by rpspringuel** [comment]
See #594

**Comment by eroux** [comment]
The whole point of my small demonstration with a snippet was to show that it should be made at every syllable, not just know end of lines, so you can remove point 2

**Comment by henryso** [comment]
Is this done?

**Comment by rpspringuel** [comment]
Yes.
