### ISSUE TITLE
bolshift for flats

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#599]
When a line starts with a flat, the beginning of line alignment makes it aligned with the notes, while it would be better, when possible, to shift it left a bit more (it can be quite close to the key). I believe that a little change in `\gre@compute@bolshift` might be enough for this... Maybe by changing this line:

    \advance\gre@dimen@clefwidth by -\gre@dimen@minimalspaceatlinebeginning %

and changing `\gre@dimen@minimalspaceatlinebeginning` to `clefflatspace` if the first glyph is a flat...

See [mail archives](https://mail.gna.org/public/gregorio-users/2015-09/msg00028.html) for original report

**Comment by rpspringuel** [comment]
Seeing as I'm currently futzing around with the bolshift code, I'll see what I can do about this.

**Comment by eroux** [comment]
Thanks a lot! if it's a lot more complex than what I describe, don't hesitate to ask for help, I'll try to be more helpful than on the eol thing!

**Comment by rpspringuel** [comment]
I've started work on this and have run into an issue.  I obviously need to trigger the altered `bolshift` calculation based on the presence of an alteration at the beginning of the glyph.  Since these alterations are already taken into account when aligning the text and the notes, Gregorio clearly already has the necessary infrastructure in place to know this.  Examining the functions, it appears that this should be indicated by the notes alignment type argument (#4) for `\GreGlyph`.  However, when I try to trigger off this, nothing happens.  After adding some debug messages to figure out why, I've come to the realization that the command-line tool always sets this argument to 0 (and by always I mean that all of the tests in gregorio-test always set this argument to 0 when writing `\GreGlyph` into the gtex file).  This would imply that the code related to this argument is dead and should be eliminated.  Is this the case?  Are there conditions (not present in the test repository) where this argument takes on a non-zero value?

**Comment by henryso** [comment]
In the output from tests/gabc-output/montes.gabc, there are several cases where argument #4 is not 0.

**Comment by rpspringuel** [comment]
My mistake.  I had a `<` where I should have had a `>` in the code that was looking for those occurrences.  So, the code is not dead.  Now to run some more tests to figure out why my code isn't working the way I intended it to.

**Comment by eroux** [comment]
@rpspringuel this can be closed, right?

**Comment by rpspringuel** [comment]
Yes.
