### ISSUE TITLE
adapt to new LaTeX version

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#629]
There's a new move in LaTeX to adapt to new engines such as LuaTeX (better late than never!), so a few changes will come with the new version of LaTeX, see [announcement](http://article.gmane.org/gmane.comp.tex.latex.latex3/3683). Gregorio is affected by these changes, especially by the removal of the `luatex` prefix of primitives like `localleftbox` and `localrightbox`, and also by the change in the attribute allocators. As Gregorio is not yet integrated into TeXLive, I think it should adapt to both versions (old and new).

**Comment by rpspringuel** [comment]
I'm reopening this issue because I've just discovered a related problem:

`fontspec and `gregoriotex` aren't playing together seamlessly.  If `fontspec` is loaded before `gregoriotex`, everything works as expected.  However, when `gregoriotex` is loaded first, then I get the error: Undefined control sequence:  `\xetex_suppressfontnotfounderror:D`.

For me, at least, this means many of our tests fail as they load `gregoriotex` first.

There are, as I see it, two possible fixes:

1. Modify the documentation to indicate that `fontspec` if used, should be loaded before `gregoriotex`.  This would also mean modifying the tests so that they comply with this order.
2. Make some technical fix so that `gregoriotex` doesn't interfere with `fontspec`.

I've no idea how to make the second (and it may involve waiting for wspr/fontspec#217 to be resolved), but can do the first myself fairly easily.

**Comment by henryso** [comment]
I noted this issue in #633, but didn't realize it correlated it to load order.  Since things are in flux as people fix bugs in packages, I say we do the former (document and update tests).

**Comment by rpspringuel** [comment]
Okay, I'll work on that later tonight and submit PRs with the necessary changes.
