### ISSUE TITLE
Installer is not El Capitan compliant

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#645]
Because the installer looks for TeX tools in `/usr/texbin` it is not compliant with El Capitan (which prohibits modification of `/usr` so MacTeX no longer can create `/usr/texbin`).  At the very least the test and postflight scripts will need to be modified.  There may also be other aspects of the installer which need modification, but I haven't looked at them yet.  Hopefully I can come up with something which allows the same installer to work on both El Capitan systems and earlier ones.

**Comment by rpspringuel** [comment]
The uninstaller will also need some work.

**Comment by rpspringuel** [comment]
I'm making progress here.  I think I've redesigned the scripts, I just need to test them.

Question, would it make sense for the installer to automatically configure TeXShop and/or TeXworks?  Or perhaps to create extra "installers" which would run a script designed to configure one or the other program?

**Comment by henryso** [comment]
I think that's a question that might be better for the list, since I think you are the principal (if not the only) Mac OS developer at this time!

If you're asking my opinion, I typically don't like installers to muck around in other application configurations automatically (unless of course it's a plugin installation or something).  The option to do so is fine, but I typically opt out.  This is, of course, assuming that Mac installers work like Windows installers and can give you options.  I guess that shows you how much I know about Mac OS!

**Comment by rpspringuel** [comment]
That makes enough sense to me that I'll develop those tools as a separate entity and will work on them later.  Right now I'll concentrate on debugging the reworked installer and get that ready for rc2.

**Comment by rpspringuel** [comment]
See #649
