### ISSUE TITLE
Neography issue: salicus with clivis

### ISSUE THREAD

**Issue by jakubjelinek** [gregorio-project/gregorio#687]
In Nocturnale Romanum 2002, p. [171], I see another neume I haven't managed to typeset with gregorio:
![sa cl](https://cloud.githubusercontent.com/assets/9370665/11572930/e8f57acc-9a03-11e5-979a-77f96a374c22.png)

I've tried (deOfd), (d!eo<!fd), (d!eo<fd), without success, the second one is closest to it, except that it has the stem that should not be there.
In nabc the corresponding neume is sa!cl .
Perhaps another case for backslash - (d!eo<\fd) ?

**Comment by henryso** [comment]
What is the meaning of the reverse oriscus in that instance?  What does it signify different from the "normal" oriscus?

**Comment by jakubjelinek** [comment]
Hard to say, I don't know.  That said, I haven't found a way to typeset it even with the normal oriscus.
The original manuscript has:
http://www.e-codices.unifr.ch/en/csg/0391/113/0/Sequence-1325
(the last neume above dignissima in Felix namque responsory).

**Comment by henryso** [comment]
Well, with the fix for #631, you *should* be able to implement it with a normal oriscus.

**Comment by jakubjelinek** [comment]
I'll try that soon.  Perhaps we could use O< instead of O for reverse oriscus in the salicus?

**Comment by henryso** [comment]
My understanding (and the reason for my previous question) was that the flow of the oriscus (in square notation) is based on the note that follows, so an oriscus that looks like up-down-up (a.k.a., "normal") leads to a higher note and down-up-down ("reverse") leads to a lower note.  However, this figure seems to contradict that, and drawing lines to connect the notes in this figure results in a non-flowing figure.  If that's just an "artist's interpretation" of an oriscus, then I think the salicus flexus of #631 would suffice, and that figure may even be considered a typographical error.  However, if there is a semiological reason for it, then we need to think about how to draw it.  If we use the `<` in the middle of the figure, this is the first time a "liquescent" is applied to something other than the whole figure, and would require some changes to the data structures or some other "clever" way of dealing with it.

**Comment by jakubjelinek** [comment]
I'll try to talk to various people about this (hopefully during the weekend).

**Comment by henryso** [comment]
Have you had a chance to speak with anyone about this?

**Comment by henryso** [comment]
#### The Problem
After working through the cases, the oriscus design is a bit of a mess.
* `o` = oriscus
* `o<` or `o>` = reversed oriscus
* `o~` = liquescent oriscus
* `O` = the connected oriscus (i.e., in a salicus) or the stemmed oriscus

This is inconsistent with all other figures.  The reversed oriscus is *not* an auctus figure.  The connected oriscus should really be detected from context.

I realize this is due to the evolution of things, so I'm not sure how to clean this up, if at all.

#### Case I : Solesmes

Looking at most recent Antiphonale Monasticum (I – III) from Solesmes, the direction of the oriscus is consistently pointing in the direction of the note that follows.  If above, it's an up-down-up oriscus, and if below, it's a down-up-down oriscus.  Even if the following note is detached from the oriscus (i.e., in the next word), Solesmes is pretty consistent with this rule.  Salicus is always up-down-up because it leads to the higher note, and pressus is down-up-down because it leads to the lower note.  I couldn't find any contradictory cases, but I also didn't go through every score in the three books.

So, if we had a do-over and are interested in mimicking Solesmes rules, it would be possible to detect the correct oriscus shape from its context and connect it in the salicus form, also from context.  There would be no need for a capital-O as a connected oriscus, and there is no stemmed oriscus in Solesmes.

#### Case II: Nocturnale Romanum

Things start to get weird when you consider the *house rules* of recent books from outside Solesmes, namely the Nocturnale Romanum.  Unfortunately, I don't have the book, so I can't scour it for examples, but based on the snippets posted here, Sandhofe was inconsistent with how he used the oriscus.  He added a stem to it for the pressus,  He favored the up-down-up oriscus, regardless of the notes that followed, but was not always consistent with that.

If someone is typesetting by visual imitation rather than intent (not that there's anything wrong with that), then the only way to imitate this is a completely manual system.

#### My Ideal Design

So, if we had a do-over and want a manual system, so that someone could do it either way, I would ideally want to define four shapes:

* oriscus
* reverse oriscus
* stemmed oriscus
* stemmed reverse oriscus

To be consistent with `v` = virga, `V` = reverse virga, ideally you would want something like

* `o` = oriscus (up-down-up)
* `O` = reverse oriscus (down-up-down)
* `u` = stemmed oriscus
* `U` = stemmed reverse oriscus

These shapes would each have a liquescent form, obtained through `~` or `<` or `>`, though I have no idea how these would be differentiated, if at all.

In this scenario, salicus oriscus would be detected from context, and you would stop it using the ! in an appropriate place, like before the oriscus: `f!hoj` (= the disconnected salicus) vs `fhoj` (= the connected salicus).

#### Compromise

This would obviously break any score with salicus or stemmed oriscus in it, so we would retain backwards compatibility at the expense of inconsistency:

* `o` = oriscus (up-down-up)
* `O` = stemmed oriscus
* `u` = reverse oriscus (down-up-down)
* `U` = stemmed reverse oriscus

All of these would have a liquescent form, obtained through `~`.

For backward compatibility, `o<` or `o>` would also produce a reverse oriscus, but would only work for an oriscus at the end of an element, whereas 'u' would work within an element as well or with neume fusion. Note: we could choose to deprecate `o<` and `o>` for obsolescence a version or two after.

As for `<` and `>` used with `O`, `u`, or `U`, we could choose that it generate the shape itself (i.e., `U<` generates the same as `U`) or that it generate the same liquescent form as obtained by `~` (i.e., `U<` generates the same as `U~`).

In this scenario, salicus oriscus would only occur when `O` is used.  For consistency, reverse salicus oriscus would occur only when `U` is used.

Does anyone have any thoughts on this?

**Comment by eroux** [comment]
I don't think my opinion is very relevant, but the compromise part seems good to me. How many additional glyphs would that be?

**Comment by henryso** [comment]
My quick calculation is 697, not counting fusion glyphs, which adds another 10.

**Comment by eroux** [comment]
Well, if it fits without problem in the unicode range why not, another solution is to build the parser as you said in gabc but to generate only the glyphs we have now plus the few others we need for the new features, and wait for a bugreport of a missing glyph before actuallly building the glyphs? Is it possible with the way you want to implement it?

**Comment by henryso** [comment]
Sure, that's possible, especially since we use glyph names now instead of numbers.

**Comment by henryso** [comment]
We definitely are running out of space in the BMP-PUA (there are only about 1200 code points left), so I think I will only generate the necessary glyphs.

**Comment by henryso** [comment]
I've run into a wrinkle I hadn't realized when I typed the proposal above.  The current flexus oriscus figures currently (already) use the "reverse" oriscus, which agrees with Solesmes usage (and the flow of the shape itself).  The "compromise" above would actually break them.  So I withdraw the proposal.  What this means is:

* The reverse oriscus will continue to be called up as `go>` or `go<` when differentiated from `go`.
* When the note after an oriscus is fused higher, the system will use the up-down-up ("normal") oriscus
* When the note after an oriscus is fused lower, the system will use the down-up-down ("reverse") oriscus (to agree with the current flexus oriscus).
* To generate the glyph from the opening post, one would use `d!eo<@fd`.  The reverse oriscus will not fuse upwards, so there would be no line between the `eo` and `@ge` in `d!eo<@ge`.
* If one wants to follow an up-down-up oriscus by a lower note, then one would have to use the `!` between them, as in `eo!d`.  This would not fuse downwards.

Any thoughts?

**Comment by eroux** [comment]
Sounds reasonable

**Comment by henryso** [comment]
In creating the glyphs in the greciliae font, I notice that `SalicusOriscus` is shorter than other oriscus figures.  It looks like this shape would have made sense for a "pes quassus" figure with a punctum above (to the left of the line), but we don't have this figure (other than deminutus, the next note is to the right of the line).  It seems that we use the taller oriscus for an ambitus of one (or alone) and the shorter for an ambitus of two or more, so the shapes are inconsistent.  Should I switch everything to use the taller oriscus?

**Comment by eroux** [comment]
I think so yes, thanks for noticing!

**Comment by henryso** [comment]
Please try out the feature in the develop branch.
