### ISSUE TITLE
Improve security (in C code)

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#697]
The goal here is to have the command `gregorio` accepted in the `shell_escape_commands` of TeXLive, which means there will be a security audit. Once gregorio is in the `shell_escape_commands`, it will be more simple and safe for users (no need of `--shell-escape` switch), and it will also make Gregorio work on online platforms such as [overleaf](https://www.overleaf.com/) or [ShareLaTeX](https://fr.sharelatex.com/), lowering the barriers for new users.

We can continue the discussion started on #696 here, and PR related to security can reference this issue.

**Comment by eroux** [comment]
(note that it is not blocking for 4.0.0 release)

**Comment by eroux** [comment]
I've tried a few things:

- [SEI CERT standards](https://www.securecoding.cert.org/confluence/display/c/SEI+CERT+C+Coding+Standard) look promising but it's quite a lot of work and might not be that relevant...
- [splint](http://www.splint.org/) is very easy but outputs so many errors it certainly has to be tamed a bit, but it's hard for me to know which warnings should be disabled
- [frama-c](http://frama-c.com/) is really not easy to work with...

Anyway, non of these said anything about `PATH_MAX`, so even if we follow them strictly, it wouldn't be enough...

**Comment by henryso** [comment]
Are TeX Lives security audit rules documented anywhere?  Maybe we can start there?  To be honest, I need some guidance how to proceed with this.

**Comment by eroux** [comment]
There's no documentation about this... and I'm not really able to give any guidance... @jakubjelinek would you have a few ideas?

**Comment by henryso** [comment]
I think the merge of release-4.0 into master auto-closed this issue, so I'm re-opening it.

**Comment by henryso** [comment]
Would it be possible to get gregorio into TeX Live without getting it into `shell_escape_commands`, in case we are unable to get this fixed before the cut-off date for TeX Live 2016?

**Comment by eroux** [comment]
Yes of course, but I think it would help many people to have it in `shell_escape_commands`... But if we can't deal with it before, we'll do when TeXLive 2016 will start to build (around February or March I think).

**Comment by kberry** [comment]
i've never heard of any of the things you found (good job looking).

there is no hard and fast rule, since creating a "secure" program remains an unsolved and unsolvable problem, even in theory.

basically, the program should obey the kpathsea settings for reading/writing (already done i believe), and shouldn't crash.
two obvious things are don't overflow arrays (under any circumstances) and
check return values (under all circumstances).  i believe gregorio doesn't execute subprograms or call out to shells under any circumstances, right?  if it does, there are lots more things to worry about.

if you're feeling ambitious, my recommendation for an automated checking program is valgrind. it can report on a lot of practical problems.

**Comment by henryso** [comment]
@kberry The C program does not call out to any subprograms or shells under any circumstances **except** when the kpathsea library is not built into it (in which case it must call out to kpsewhich to find a data file).  I do not believe this will be a problem when the binary is built as part of TeX Live as that code will be `#define`d out.

We use valgrind regularly to detect memory leaks and all the default checking that it does.  Do you have any suggestions as to what additional checks we should enable to help us further?

We will look further into buffer overflows and checking return values.

**Comment by eroux** [comment]
@kberry thanks a lot for your suggestions! For others, some more info about TeXLive building schedule [here](http://tug.org/pipermail/tex-live/2016-January/037672.html) and [here](http://tug.org/texlive/). The best would be to have 4.1.x released for March 1st.

**Comment by henryso** [comment]
Clang comes with a static analysis tool that we can use for additional checking.  You would run `scan-build ./configure` followed by `scan-build make`, which would run the static analysis while compiling.  Then `scan-view /path/to/dir/returned/by/build` to look at the results.  Right now this finds a few potential problems.  I haven't had time to review in detail, but it's another avenue.

**Comment by kberry** [comment]
i also just heard about this (from a report on the tex-live list): https://en.wikipedia.org/wiki/AddressSanitizer

i think gcc can do static analysis stuff too, btw, but don't have any pointers at hand.  happy hacking!

**Comment by eroux** [comment]
About address sanitizer (which is just `-fsanitize=address` if I understand correctly), maybe we should use it in the test repository? Or should we add it in our default `CFLAGS` if available?

**Comment by jakubjelinek** [comment]
I'd suggest -fsanitize=address,undefined instead.  But, those flags are not suitable for the default flags, especially -fsanitize=address has quite large address space requirements and some cost.  So perhaps you want to enable those if detected by configure only if --enable-debug-build or something similar.
Another useful approach might be fuzzing, e.g. take existing test repository and by some script start doing small random or semi-random modifications to the test files and make sure the program does not crash on the modified tests.

**Comment by jakubjelinek** [comment]
Also, useful is to use some code coverage tool (e.g. gcov), build the tool with -ftest-coverage -fprofile-arcs -O0 -g, run the testsuite and then look at gcov output and try to add tests for code paths not covered by the tests.

**Comment by eroux** [comment]
Thanks a lot for these advises! the `--enable-debug-build` flag looks like a good solution. Fuzzing is a good idea, though developing the fuzzing script will take some time. Integrating gcov to the test is a very good idea too!

**Comment by jakubjelinek** [comment]
Tried -fsanitize=undefined,address built gregorio develop on some of my sources, and with LSAN_OPTIONS=detect_leaks=0 it is clean, otherwise I just see memory leaks on pretty much everything, like:
==23193==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 96 byte(s) in 12 object(s) allocated from:
    #0 0x7f87b8dc3b09 in __interceptor_calloc (/lib64/libasan.so.2+0x98b09)
    #1 0x55626153df2b in gregorio_calloc /tmp/gregorio/src/support.c:64
    #2 0x556261581a17 in gabc_y_add_notes gabc/gabc-score-determination.y:692
    #3 0x556261584cd5 in gabc_score_determination_parse gabc/gabc-score-determination.y:874
    #4 0x556261581424 in gabc_read_score gabc/gabc-score-determination.y:642
    #5 0x556261521789 in main /tmp/gregorio/src/gregorio-utils.c:608
    #6 0x7f87b7c7a6ff in __libc_start_main (/lib64/libc.so.6+0x31c84206ff)

Direct leak of 88 byte(s) in 11 object(s) allocated from:
    #0 0x7f87b8dc3b09 in __interceptor_calloc (/lib64/libasan.so.2+0x98b09)
    #1 0x55626153df2b in gregorio_calloc /tmp/gregorio/src/support.c:64
    #2 0x556261581a17 in gabc_y_add_notes gabc/gabc-score-determination.y:692
    #3 0x556261584eb3 in gabc_score_determination_parse gabc/gabc-score-determination.y:896
    #4 0x556261581424 in gabc_read_score gabc/gabc-score-determination.y:642
    #5 0x556261521789 in main /tmp/gregorio/src/gregorio-utils.c:608
    #6 0x7f87b7c7a6ff in __libc_start_main (/lib64/libc.so.6+0x31c84206ff)

SUMMARY: AddressSanitizer: 184 byte(s) leaked in 23 allocation(s).

BTW, I'm surprised that the default ./build.sh configuration doesn't build optimized build (which together with -D_FORTIFY_SOURCE=2 in the CPPFLAGS leads to expected warnings:
In file included from /usr/include/stdio.h:27:0,
                 from vowel/vowel-rules.y:23:
/usr/include/features.h:328:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
Would be better if only --enable-debug-build used -O0 and the default build used -O2.

**Comment by jakubjelinek** [comment]
Fix for the leak: https://github.com/gregorio-project/gregorio/pull/820

**Comment by eroux** [comment]
For the optimization: #821

**Comment by henryso** [comment]
We should really add tests for nabc into the test repository.  Gregorio-test can be run with -G to use valgrind, and that should have been caught.

Another tricky one is that point-and-click was leaking (it's fixed in one of the commits in #819, which I only caught when enabling address sanitizer and running the gabc-output tests (which now turn on point-and-click).

**Comment by jakubjelinek** [comment]
For nabc tests, it depends on what amount would you like to see, and if it should be real-world tests, or artificial ones.  I have quite a lot of nabc-lines: 1; sources in
https://github.com/jakubjelinek/Editio-Sti-Wolfgangi
Perhaps what could be done is grab using a script from all such *.gabc files all the separate syllables, extract the nabc parts from them and stick it in the first column, followed by the original syllable (perhaps for cases with multiple ||s separate the nabc chunks by say |), and then for each unique nabc snippet (or set of combined snippets) add to the test one (randomly chosen, first, whatever) original combo of gabc + nabc.

**Comment by henryso** [comment]
There's a distinct lack of test coverage against the polyphony code in gregorio.  This code doesn't work properly, and there's really no support for it in GregorioTeX.  Should I leave it in and ignore the missing coverage or rip it out, to be replaced with whatever we come up with in the future (i.e.,  #674)?

**Comment by rpspringuel** [comment]
Two things:

I would query the user list before removing any working code.  If no one is making use of the admittedly primitive single staff polyphony, then I don't necessarily have any objections to removing it.  However, given that we were just asked for the ability to put two clefs on the same staff, it would seem that there might be some call for having this feature in place.

The single staff polyphony which we already have is (at least in my mind) distinct from the multi-staff polyphony mentioned in #674.  Even though both represent polyphony, I don't see them as being interchangeable in their use cases.

**Comment by henryso** [comment]
The code literally doesn't work.  If you try to use it, gregorio will throw a fit and return nonsensical errors, so I'm pretty sure no one uses it.  Whatever we come up with in the future will either be a "clean-room" implementation (in which case, I should rip it out) or some kind of adaptation of what's there (in which case, I should leave it).  As it is, the code is inconsistent with itself, so if you try to use `--` to separate voices in the header, it won't accept `&` in the notes anyway.  If you alter the code to bypass this check, it will then complain when trying to emit anything other than a dump because the output functions don't support polyphony.

**Comment by rpspringuel** [comment]
I'm talking about the single staff polyphony described here: http://gregorio-project.github.io/gabc/details.html#polyphony

That syntax worked in 4.0, as I regenerated the diagram for the website.  If it's not working now, then we've broken it some where since then.  It's this that I'm concerned about removing without making sure that no one is using it.

From the sounds of it, though, you may be referring to something else in the C code (which I'll admit, I haven't studied to closely).  If that's the case, and that particular feature isn't working, then I have no problem with it being stripped out.  Even if we later want to adapt what's in there at some future point when implementing true mult-staff polyphony, we can always retrieve the code from the history.

**Comment by henryso** [comment]
That's not the polyphony I'm talking about.  That still works fine, and the tests cover it.  I'm talking about the one with `&` between notes, basically what you put into #674.  There are vestiges of this code in C, and it doesn't work.

**Comment by eroux** [comment]
It can be removed indeed

**Comment by henryso** [comment]
I think I've gone as far as I can with this one.  Unless someone has more ideas, perhaps it can be closed?

**Comment by eroux** [comment]
Let's close it, we'll reopen if needed. You did an excellent job on that!
