### ISSUE TITLE
New horizontal episemus on porrectus except last note

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#70]
Page 125 of the Graduale Romanum (1961) lies a strange horizontal episemus currently impossible to reproduce with Gregorio, not even to represent in gabc:

![horizontal_episemus_porrectus](https://cloud.githubusercontent.com/assets/60868/6555219/2bee363a-c664-11e4-83ff-27d9ee2c6b5d.png)

I don't even know how to represent this oddity... Any suggestion?

**Comment by henryso** [comment]
What does that even mean? Are there episema on the first two notes or the first three?  Assuming this means the first three, I would have two suggestions.

My first suggestion is, since the _'s count from the the current note backwards, maybe have some other character as a "skip" character (I use = here for demonstration):  fhfg=___

My second suggestion is to not have the _ break up the neume: fhf___g or f_h_f_g

Is this chant in the Triplex?  Maybe we can look at the nondiastematic neumes and see if maybe this figure is just a typo.

**Comment by eroux** [comment]
This comment is not meant to reopen the issue or anything, it's just for another reference: page 98 of Graduale Triplex lies something similar, but the lines goes up to the middle of the final note, which makes it look like a printing error... maybe the original was too...

**Comment by henryso** [comment]
Well, the Laon is medium uncinus, large uncinus (with "a"), small uncinus, virga, so I'm inclined to believe this really is an episema on the first three notes but not the fourth.

**Comment by henryso** [comment]
Of course the St. Gall just shows a regular torculus here,  but that could also be a rhythmic variance between monasteries.
