### ISSUE TITLE
\gabcsnippet doesn't obey \greseteolcustos

### ISSUE THREAD

**Issue by olivierberten** [gregorio-project/gregorio#703]
If you have a multiline snippet, it will add a custos at the end of the line, even with \greseteolcustos{manual}

**Comment by henryso** [comment]
I cannot reproduce this.  Please provide an MWE.

**Comment by olivierberten** [comment]
Just figured out the bug appears from the second snippet on.

**Comment by henryso** [comment]
The value of `\greseteolcustos` is reset after each score inclusion.  It appears to be doing this purposely.  Perhaps @rpspringuel can speak to the intent here.

**Comment by rpspringuel** [comment]
That behavior was pre-existing to my renaming of the commands, but IIRC, `\greseteolcustos{manual}` is used to suppress the automatic custos at the end of the score (where it is meaningless as there is no next note).  Given the assumption that automatic custos are being shown (the default condition) we have to "revert" to `\greseteolcustos{auto}` so that subsequent scores will have the automatic custos appear.

What we should probably do is separate the persistent flag (the preference) from the immediate flag (should a auto-custos be printed on this line) so that the end of score stuff can change the immediate flag without affecting the persistent one.

This implementation should be very similar to the direction that @henryso took for the hyphen after a 1-letter first syllable.
