### ISSUE TITLE
\grecross and \grealtcross have been swapped

### ISSUE THREAD

**Issue by olivierberten** [gregorio-project/gregorio#713]
\grecross used to produce a maltese cross but now you need to type \grealtcross in order to produce the same result...

**Comment by henryso** [comment]
Anyone know if this was working correctly in 3.0.3 ?

**Comment by olivierberten** [comment]
No idea... I was still using 2.4...

**Comment by henryso** [comment]
If it is a bug in 4.0.0 vs 3.0.3, it becomes a high priority to be a bug we fix for 4.0.1.  However, if it's been this way since 3.0.3, then we need to discuss how to deal with it since some people will have used the new behavior, so we can't call at bug so much as a change in behavior.

**Comment by rpspringuel** [comment]
I think the most likely point for this sort of swap to have been introduced is when we changed the font interface system.  Perhaps the names of the crosses in the font got switched in that process?

**Comment by henryso** [comment]
I don't dispute that.  What I'm trying to determine is the course of action here:
* If it's a bug introduced between 3.0 and 4.0, then it should be fixed in 4.0.1 as a bug
* If it was introduced between 2.4 and 3.0, no one noticed it, so we have to choose whether to treat this as a bug and fix it (which would break documents created during the 3.0 era that use the `\grecross` in its 3.0 behavior) or just document it (which breaks documents created prior to 2.4 that use the `\grecross` in its 2.x behavior).

**Comment by rpspringuel** [comment]
Right, I was hoping that by identifying what might have caused the error, I could narrow down the search parameters for some one trying to differentiate between the two situations you describe.  Seeing as I didn't have the time to actually conduct that search myself, it was the best I could do at the time.

Now that I have the time:
[Main.pdf](https://github.com/gregorio-project/gregorio/files/60708/Main.pdf)

[Main.pdf](https://github.com/gregorio-project/gregorio/files/60722/Main.pdf)

It looks like the swap was between 3.0.3 and 4.0.0, making this a bug.

**Comment by henryso** [comment]
Perfect.  Thanks.
