### ISSUE TITLE
use `dimexpr` instead of `\advance`, `\multiply`, etc.

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#739]
This is a long term issue with no deadline, but I was advised by @OldClaudio (Claudio Beccari) to use `\dimexpr` instead of the individual operations we currently use. As stated in [eTeX's manual](http://www.let.rug.nl/alfa/tex/tetex30/etex/base/etex-man.pdf#8), these operations are a bit safer and are sometimes a bit faster and more precise. We should certainly make new code use them, and convert some code from time to time...

**Comment by henryso** [comment]
Out of curiosity, what exactly is the "question" here?

**Comment by eroux** [comment]
My knowledge of TeX internals is quite limitted, so some may disagree with using `\dimexpr`

**Comment by OldClaudio** [comment]
The enhancements provided  by eTeX have been an integral part of the TeX 
internals since 2005. they are embedded also in pdfTeX, XeTeX, and 
LuaTeX. Their important feature is that expressions (numbers, 
dimensions, glues and muglues)  are now performed within the CPU 
registers including some temporary results. a dimensional expressione 
such as

\dimexpr \dimone * \dimtwo / \dimthree (terminated with an optional \relax)

where each term is internally saved as a "double word" of 32 bits, is 
executed from left to right, and the product is maintanied into a CPU 64 
bit register, so that the division then shortens the overall result to 
32 bit again, without loosing digits in between and rounding (not 
truncating the result) according to the value of the first bit discarded.

The whole thing is described in etex.pdf; Buth these internal details 
are sort of irrelevant to the final user; the point is that "old" tex 
could not evaluate expressions but the interpreter had to interpret a 
single operation at a time, loading to CPU end saving from CPU every 
intermediate result, while the etex expressions are all done in the CPU 
while their code is more expressive and more easily maintained.

The situation nowadays with the various interpreters of the TeX system is:

1) tex used just maintianed by Knuth himself and used as a gauge to 
allow any other interpreter to contain the string "tex" in their names; 
nobody uses it any more, except, perhaps Knuth himself.
2) etex: tex extended with the etex enhancements; When you click on the 
button Plain TeX you actually use "etex & plain".
3) pdftex; includes the enhancements since 2005; it may behave in 8 
different modes; produces dvi or pdf output; enable or disabled for 
shell escape; extended or not extended with the etex extensions; by 
default pdftex operates with pdfoutput, extended and shell-escape 
disabled, or better enabled only to run a half dozen safe TeX system 
programs (protected shell escape).
4) xetex includes the enhancements since its birth; it operates in four 
modes: shell-escape enabled or disabled; pdf or dvu (a special version 
of dvi enabled for unicode encoding); its default operating mode is pdf 
output and protected shell-escape.
5) luatex includes the enhancements since its birth;  it is an engin 
with most features of pdftex, but it can interpret lua script so as to 
dialogue between tex and lua; int includes a myriad of other libraries 
coming from the aleph engine, from metafont/metapost, and several other 
ones. It also can use shell-escape in protected mode, so that in order 
to run GregorioTeX it is necessary to enable it for full unprotected 
shell-escape.

But as you see all of them except the pure Knuthian tex, can operate in 
extended mode.

Élie, if you think that some gregoriotex users still use the knuthian 
version of tex, then you have two solutions:
1) either you avoid extended mode expressions and the many other etex 
enhancements, or
2) you use the extended mode enhancements and warn tex users to use etex 
instead of tex.

Claudio

**Comment by eroux** [comment]
Thanks for the detailed explanation! Removing the `question` tag. Also, Gregorio only works under LuaTeX, so no problem with eTeX!

**Comment by henryso** [comment]
I'll work on this when development has calmed a bit, as it is likely to cause merge issues.

**Comment by henryso** [comment]
In `\gre@convertto`, we do something like:
```
\gre@unitfactor = \number\gre@maxlen%
\divide\gre@unitfactor by \number\gre@unit\relax%
```
and then later
```
\multiply\gre@unit by \gre@unitfactor%                                     
```

If I change the first to
```
\gre@unitfactor = \number\dimexpr(\gre@maxlen / \gre@unit)\relax%
```
then the second line fails with
```
! Arithmetic overflow.
```

Any idea what I'm doing wrong here?

**Comment by eroux** [comment]
Shouldn't it be

```
\gre@unitfactor = \numexpr(\gre@maxlen / \gre@unit)\relax%
```

?

But apart from that, I admit I really have no clue, having never used `\dimexpr`, etc.

**Comment by henryso** [comment]
`\gre@maxlen` and `\gre@unit` are dimensions, so it'd have to be
```
\numexpr(\number\gre@maxlen / \number\gre@unit)\relax
```
but that results in the same error.

**Comment by rpspringuel** [comment]
I don't think you're doing anything wrong per se, but are running into the size limits of length registries because of rounding.  IIRC that was one of the big problems I had in getting that function working correctly in the first place. 

As for a solution, it may be possible to eliminate the use of `maxlen` entirely when switching to `\dimexpr`.  I used `maxlen` to increase the accuracy of the calculation and minimize rounding errors, something which I found necessary due to the one step at a time nature of the primitives.  If you write all the math out in a single equation, `maxlen` should cancel out. 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by rpspringuel** [comment]
Oh, and the other reason for using `maxlen` is because you can only `\divide` by an integer.  This made the rounding issues I mentioned even more severe than normal. 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by OldClaudio** [comment]
What should be assigned to what?

I mean the result of the suggested number expression should be assigned 
to a numeric register? Or the ratio of the two lengths should be used in 
some way?

Assuming that the primitive command \number is applicable to a dimension 
register, the indicated expression yields the result of an integer 
division not a fractional number. In terms of decimal notation, the 
integer ratio of 347.125 / 415.456 is zero; the integer ratio of 415.456 
/ 347.125 is 1. Is this kind of result you are looking for? I doubt.

If you want the fractional ratio of two lengths with minimum rounding 
error you should, say, define a macro in this way

\edef\@tempA {\strip@pt\dimexpr \gre@maxlen * \p@ / \gre@unit}

Of course \@tempA should be replaced by one of the legal names \gre@... 
to be used in the gregoriotex name space, but the code I am suggesting 
resorts to the scaling algorithm of \dimexpr that stores the 
intermediate multiplication result in a double precision register so 
that no truncation errors take place, and then it isrestored to a single 
precision register after the division is executed. The problem is that 
\strip@pt is a macro defined in the core of LaTeX (that can be copied 
and reused within gregoriotex) that does exactly what its name suggests: 
the dimension result is converted in string form with decimal digits and 
decimal point followed by the default unit of measure "pt"; then the 
macro detaches the "pt" part so that the macro \@tempA receives just the 
fractional number. The above operation 415.456 / 347.125 lets \@tempA to 
be defined with the value 1.19685 (with rounding, not with truncation as 
it would be done with the primitive \divide).

Claudio

**Comment by rpspringuel** [comment]
Okay, now that I'm at home and have a full keyboard (and big screen) let me try to explain what `\gre@convertto` is doing and why.

`\gre@convertto` is supposed to take a distance (argument `#2`, which it puts in `\gre@base`) and convert it so that it can be represented in the units specified in `#1` and stored as a string in `\gre@converted`.  I.e. `\gre@convertto{in}{72.27pt}` should result in `\def\gre@converted{1 in}`.  The issues that arise in doing this are several (some of which have been pointed out above):

1. TeX math is inherently integer math.  Decimal numbers, where they are allowed, are truncated to just the integer part (and in many cases we have to do this ourselves, hence `\gre@makein`).  This creates large rounding errors, especially with smaller numbers.
2. In keeping with the above, TeX length registers actually store their value as a 32-bit integer.  This number is in scaled points (sp) where 1pt = 65536sp.
3. There are two primitives which allow one to convert a length register to text: `\the` and `\number`.  `\number` simply outputs the integer value in the register (i.e. the length as measured in sp).  `\the` outputs the length as measured in pt, so it is dividing the integer in the register by 65536 and then outputing the result (to 5 decimal places) with `pt` attached.
4. `\multiply` and `\divide` can only take an integer for their second argument (what comes after the `by`).

In order to convert arbitrary lengths to a different unit, therefore, this is what `\gre@convertto` does:

1. Set `\gre@base` to be the length to be converted.  We'll always access this value textually though `\the` so we consider this length to be in pt (even though the internals will represent it in sp).
2. Set `\gre@unit` to be 1 in the unit we want to convert to.  Again, when accessed via `\the` this will be in pt so it represents the conversion factor in pt/un (where `un` is the generic target unit).
3. The goal at this point is `\divide \gre@base by \gre@unit` but chances are that `\gre@unit` is not an integer.  To get there with reasonable accuracy we'll multiply both `\gre@base` and `\gre@unit` by as large a number as possible so that when we truncate `\gre@unit` to get an integer we've lost as little precision as possible.
4. To find this factor we take `\gre@maxlen`, the largest value TeX can have in one of its registers, and divide it by `\gre@base` and `\gre@unit`.  The smaller of these two then becomes our factor for the process described in the previous step.
5. We multiply both `\gre@base` and `\gre@unit` by the factor found in the previous step.  To do this we must first truncate the factor (not round) so that its an integer and the results of the multiplication are always less than the maximum register value.
6. We now truncate and strip the units from `\the\gre@unit` and perform `\divide \gre@base by \gre@unit`.  This will result in `\gre@base` holding the a value equal to our original length, but now in our target unit.
6. Since `\the\gre@base` will add the wrong units to our number (pt instead of the target unit) we strip off the units and manually add the right ones when creating `\gre@converted`

The problem you're probably running into is in step 5.  Since `\dimexpr` rounds instead of truncating the factor that results is such that either `\gre@base * \gre@basefactor` or `\gre@unit * \gre@unitfactor` is larger than the maximum value which can be stored in a TeX register.  To compensate for this you need to reduce the factor by some arbitrary value before continuing with the calculations.

However, as I suggested earlier it should be possible to avoid `maxlen` altogether.  The following sample document demonstrates that judicious use of `\numexpr` allows one to get a much more accurate division without going through the above described process:

```
\documentclass{report}

\begin{document}
{\catcode`p=12 \catcode`t=12 \gdef\makein#1.#2pt{#1}}%
\newdimen\test
\newdimen\unit
\newcount\result
\newcount\temp
\test=12in
\unit=1in
Test value: \the\test

Target unit: \the\unit

\result=\numexpr\number\test / \number\unit\relax
\textbackslash dimexpr result: \the\result

\temp = \expandafter\makein\the\unit
\divide \test by \temp
\textbackslash divide result: \the\test

\end{document}
```

**Comment by rpspringuel** [comment]
Actually some further testing reveals that the above still has some problems with non-integers and I've come up with something better based on @OldClaudio's suggestion:

```
\documentclass{report}

\begin{document}
\newdimen\test
\newdimen\unit
\base=14.5in
\unit=1in
\makeatletter
\edef\result {\strip@pt\dimexpr \base * \p@ / \unit}
\textbackslash dimexpr result: \result

\end{document}
```

Thus I would redefine `\gre@convertto` as follows:

```
\def\gre@convertto#1#2{%
  	\gre@debugmsg{general}{convertto (#1) (#2)}%
	\gre@debugmsg{ifdim}{ #2 = 0pt}%
	\ifdim#2=0pt\relax%
		\edef\gre@converted{0 #1}%
	\else%
		\gre@unit = 1 #1%
		\gre@base = #2%
                \edef\gre@converted {\strip@pt\dimexpr \gre@base * \p@ / \gre@unit #1}%
	\fi%
}%
```
I haven't fully tested this for accuracy yet (I've got to get ready for Vespers now) but I think this should satisfy all requirements and is a hell of a lot simpler than the complicated mess than what I wrote before.

**Comment by OldClaudio** [comment]
Thank you Brother Samuel for your long and detailed explanation.
I think that your algorithm is more complicated than it could be, 
especially if the final goal is to convert a length into a string where 
its measure is expressed in an arbitrary unit, that is in a fractional 
decimal multiplier of a specified length unit.

I remind you that the whole task is already solved by package 
lengthconvert that can use any unit of measure understood by TeX bat 
includes the full set of SI length units. May be the package cannot be 
used by gregoriotex, because it is coded with the new LaTeX3 language 
(L3 for short), while I understand the gregorio project tries to be as 
independent as possible from this or that format, except the Plain one, 
as the simplest one on which to build the gregoriotex code.

Using the extensions of etex, that are primitive commands to the modern 
typesetting engines, except the original knuthian TeX, there are several 
ways to enter the target unit in such a way that something as 1in can be 
interpreted as a dimension or a string from which to extract the "in" 
component, then the \strip@pt or a similar macro already defined in 
gregoriotex, can be used to transform the measure \gre@base into a 
different unit; the syntax of \gre@convertto is already a shortcut that 
bypasses the above steps; but the rest is simply obtained with \dimexpr 
as you can see in the following example

\documentclass{article}
\makeatletter
\newlength\gre@unit

\newcommand\gre@convertto[2]{\gre@unit=1#1
\edef\gre@converted{\strip@pt\dimexpr#2 * \p@ / \gre@unit\relax #1}}

\begin{document}
\makeatletter
\gre@convertto{in}{72.27pt}
Result = \gre@converted

\gre@convertto{in}{25.4mm}
Result = \gre@converted

\gre@convertto{dd}{1pt}
Result = \gre@converted

\gre@convertto{cm}{\maxdimen}
Result = \gre@converted

\end{document}

Let me point out that numeric registers store their values in 32-bit 
words using one bit for the sign and 31bits for the integer absolute 
value that is stored (let's forget the specific way used internally to 
represent negative numbers; the point is that a negative number requires 
one bit more that the corresponding positive one) and this is why the 
maximum positive integer TeX can handle is 2^(31)-1. Lengths are also 
stored in 32bit words, but two bits are reserved for the sign and other 
pieces of information for special lengths; therefore the maximum 
positive length is 2^{30}-1 sp = 16383.99999 pt = \maxdimen

The primitive command \dimexpr scales a length through a multiplication 
and a division; the multiplication is executed first and the result is 
stored in a 64-bit CPU register; this word as a product of two lengths, 
has a very large value in scaled points, but its result does not contain 
more than 60 significant bits; there is no truncation or rounding in 
this operation. Then comes the division that is an integer division 
between scaled points: the result is therefore shortened to 30 
significant bits and the most significant discarded bit in this process 
is used to round the result. There are non problems of overflow, also 
because except for scaled points, all the units specified with the first 
argument of \gre@convertto are never that small so as to produce an 
overflow.

The simple code I wrote above without mixing integer and length values 
(although the internal calculations are all integer ones) is much 
simpler and it does not cause loss of precision except that intrinsic to 
the decimal to binary and binary to decimal conversions.

The example you posted in your message clearly shows the correct result 
with the \dimexpr  algorithm and a very modest result with the \divide 
procedure.

When the eTeX primitives were not available and/or were not integrated 
into all the typesetting engines of the TeX system, I had developed 
other algorithms for dividing lengths while retaining the fractional 
ratio and the best precision possible by working with 32-bit words; 
there I simulated long division as done by hand on paper; it worked 
pretty well, but overflows were always around the corner; the precision 
was excellent, but when I compared the results with those obtainable 
with \dimexpr I found out that possible differences amounted to one unit 
on the fifth decimal digit. I assure you that \dimexpr works well, too 
well to spend any time in trying to convince TeX to do better than that.

Final observation: using luatex/lualatex as the only possible engine for 
gregorio scores, the scripting language Lua is available as well as the 
primitives to pass information from tex to lua and viceversa, and with 
lua it is possible to do any kind of calculation without any problem 
with overflows: I have seen it used to calculate the first 800 decimal 
digits of pi=3.14159...

Claudio

**Comment by henryso** [comment]
Why not just
```
\def\gre@convertto#1#2{%
  \gre@debugmsg{general}{convertto (#1) (#2)}%
  \gre@debugmsg{ifdim}{ #2 = 0pt}%
  \ifdim#2=0pt\relax%
    \edef\gre@converted{0 #1}%
  \else%
    \edef\gre@converted{\expandafter\gre@makenum\the\dimexpr#2*65536/\number\dimexpr 1#1\relax\relax #1}%
    \gre@debugmsg{general}{converted value is \gre@converted}%
  \fi%
}%
```
This avoids the latex `\strip@pt` as well as `\p@`.

**Comment by rpspringuel** [comment]
@OldClaudio, knowing what I know now I would definitely go one of the routes you're suggesting rather than writing my original algorithm.  The problem, of course, is that I didn't know these things when I wrote that algorithm.  Thanks for the information as this will help clean up the code.

@henryso, If `\strip@pt` and `\p@` are LaTeX only, then you're right to avoid them (and it looks like you've done it well too).  Additionally, you actually may be able to remove the `\ifnum#2=0` statement.  That was necessary in my algorithm because there was a division by `\gre@base` (i.e. `#2`) which had to be avoided when the distance being converted was 0 (for obvious reasons).  In the revised algorithm there is no such division so there is no need to avoid it:

```
\def\gre@convertto#1#2{%
  \gre@debugmsg{general}{convertto (#1) (#2)}%
  \gre@debugmsg{ifdim}{ #2 = 0pt}%
  \edef\gre@converted{\expandafter\gre@makenum\the\dimexpr#2*65536/\number\dimexpr 1#1\relax\relax #1}%
  \gre@debugmsg{general}{converted value is \gre@converted}%
}%
```

**Comment by OldClaudio** [comment]
For your information \p@ is a plain TeX definition; \strip@pt is a more 
modern interpretation of the code Donald Knuth published in his TeXbook 
in 1984; its code is the following

% Definitions of \rem@pt and \strip@pt
\begingroup
   \catcode`P=12
   \catcode`T=12
   \lowercase{
     \def\x{\def\rem@pt##1.##2PT{##1\ifnum##2>\z@.##2\fi}}}
   \expandafter\endgroup\x
\def\strip@pt{\expandafter\rem@pt\the}

The 1984 original code did not use the \lowercase primitive, with which 
Knuth used to make wizardries even in those gone by times. As you see, 
\strip@pt does not only strip the pt component from the length string, 
but also eliminates a possibly null fractional part. On the other side 
\gre@makenum is almost identical to the original Knuthian macro.

The solution by Henry So uses integers for the scaling operation by 
substituting \p@/\gre@unit with their scaled point integer values, which 
is OK even if the macro becomes a little less time efficient; of course 
there is no need to worry because of a few microseconds spent in a 
numerical conversion that could be avoided.

Warning: it must be noticed that when using \dimexpr with alla 
dimensions the denominator must be a name of a length register, not an 
explicit length or a parameter number or a macro with the dimensionless 
value but with units appended. This is not explained in the 
documentation of etex, but it comes from my experience across several years.

Claudio

**Comment by henryso** [comment]
Since `\p@` is plain TeX, and ostensibly more efficient, then I'll use that instead.  Thanks, @OldClaudio.

**Comment by eroux** [comment]
Thanks a lot for your help on this @OldClaudio !
