### ISSUE TITLE
gabc header: handle transported modes

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#756]
gabc header `mode` can now contain only one arabic number, but some pieces require to indicate that the mode is "transported". Quoting:

> Each mode should finish with a fixed note: 1st and 2nd finish in D, 3rd and 4th in E, 5th and 6th in F and 7th and 8th in G. But in manuscripts sometimes this doesn't happen, and you can find, for example, a 6th mode that finishes in C: it's a 6th transported a 5th up.
> This should be indicated because cantores must know what note is the first to start psalmic tone.

So maybe the convention (and the code) for `mode` header should be one arabic number + an optional `t` (ie: `6t`)?

**Comment by henryso** [comment]
Currently the `mode` header is used for the first annotation (rewritten in Roman numerals) when no explicit annotation is given.  Would `6t` then show up as `VI t.` (or something) to indicate the transposed 6-mode melody, or would it still just show up as `VI`?

**Comment by eroux** [comment]
Good point, here it would appear in the annotation too, but not in the same style as the mode, it would be `VI` small caps and `t` in lower case italic (I think)... so maybe there could be a new style?

**Comment by henryso** [comment]
If we really want to be general about it, we could instead have an additional header, like `mode-modifier` which would accept any string and would output its string value in a separate style after the mode.  This way, third-party software that happens to parse the `mode` header won't break.  What do you think?

**Comment by eroux** [comment]
That's a more generic solution indeed, ok

**Comment by olivierberten** [comment]
I guess these should use mode-modifier:
![Antiphonale Monasticum, Solesmes, 1934, p. 5*](http://gregobase.selapa.net/sources/7/1308.png)

**Comment by olivierberten** [comment]
Or should we add a `mode-termination` header since the Antiphonale Monasticum puts them all while most books don't, where a transposition should be displayed anyway.

And what about Tonus Peregrinus? And C,D,E modes? aren't they allowed anymore?

**Comment by olivierberten** [comment]
See http://forum.musicasacra.com/forum/discussion/9137/psalm-tones-besides-the-usual-ones

**Comment by rpspringuel** [comment]
The `mode` (and `mode-modifier`) field wouldn't work in these instances anyway because of the two annotation lines.  `mode` only applies when there is *no* `annotation` field.  If there is an `annotation` field than that becomes the ruling field (though it can be supplanted by an explicit call to `\greannotation` in the project document).  To have two lines, as in these cases it is necessary to have two annotation fields:

```
annotation: 4 Ant.
annotation: \textsc{vii} a
```

**Comment by rpspringuel** [comment]
If one didn't want the first line of the above pictured annotations, then one could use the `mode` and `mode-modifier` fields as follows (for the first example):

```
mode: 1;
mode-modifier: g 2;
```

**Comment by olivierberten** [comment]
I'm thinking more about archival and automatisation: if one wants to store the piece in a database, he would add the `office-part` (antiphon), `mode` (7), `mode-termination` (a). If you want to use it in a service and use the Antiphonale convention, you could automatically put "4 Ant." (4th antiphon) as first annotation and "VII a" as 2nd annotation while the Liber way would be "4. Ant." and "7. a" and the Graduale does "Antiph." "7."

But it gets more complicated when you have both termination and transposition...
![Antiphonale Monasticum, Solesmes, 1934, p. 1163](http://gregobase.selapa.net/sources/7/1174.png)

**Comment by henryso** [comment]
You can use the header capture feature to capture the headers and build the annotation in TeX in any way you like, or even push into Lua if it's really complex.

**Comment by olivierberten** [comment]
Another "funny" mode: t.irreg.
![Antiphonale Monasticum, Solesmes, 1934, p. 47](http://gregobase.selapa.net/sources/7/50.png)

**Comment by olivierberten** [comment]
What I'm trying to explain is: if I want to automate booklet creation, I need standard fields. Can I do that with gabc or does it have to be sticked to a database? If D mode or Tonus Peregrinus aren't valid anymore, I can't use a generic booklet creation script, for instance. And if termination and transposition sit in the same header, I can't choose if I want only one of them, or even have them both together...

Needless to say that wasn't possible until now anyway... but if we try to improve it, why not try to have it a bit more complete ;-)

**Comment by henryso** [comment]
You can create any number of extended headers, capture them in TeX in any combination with the "standard" headers, and then do whatever you want with them in TeX/Lua.

**Comment by olivierberten** [comment]
So, are Solesmes Antiphonales so exotic they are not worth standard headers? ;-)

And do you also confirm one shouldn't put anymore any other mode than the 8 more common ones in the `mode` header?

**Comment by olivierberten** [comment]
I think I'm also a bit confused by the mix of metadata and "presentational" headers. Most headers are giving information about the score while annotations are purely for rendering intent. Not really sure they should be there at all...

**Comment by henryso** [comment]
Should I modify gregorio to take any name as a custom header?  For backward compatibility, we could reserve some names for existing system headers and promise all new system headers will start with `gregorio-`.  This way, all headers (like `manuscript` and `office-part`) that don't influence system behavior will be considered a custom header and the system header list can be reduced and be made less crazy to parse.

The mode header accepts a number from 1-8.  Anything else will produce undefined behavior.  How it got this way predates me.  I've always used `\greannotation` (or its old form) from TeX for the text above the initial.

**Comment by olivierberten** [comment]
It might be the way to go indeed... Out of the [23 documented headers](http://gregorio-project.github.io/gabc/index.html#header), only 6 do influence the rendering... and some of these were added rather recently... That said, there are already GregorioTeX functions to achieve the same result. So we might as well come back to a situation where none of the headers get used. I don't know anybody using Gregorio who's not customizing the main tex file anyway...

We might want to decide whether the intent of gabc format is first archival or rendering.

**Comment by eroux** [comment]
Well, this discussion is quite interesting, here are some insights:

- gabc headers were first thought as metadata with conventions (ie: mode in arabic number), so that it could be treated automatically by some analysis software or a database (such as gregobase)
- but they also contained some presentation (like annotation), so it's kind of a mix, just like gabc is

Personally, I think it's quite important to be able to differentiate the different modes in the gabc header, and if there was only one way to modify modes, a convention could be established in mode-modifier convention, but if there are several of them, it will just be confusing...

The ideal solution for me would be:

- standard metadata headers for the different mode modifiers in gabc (@olivierberten could you provdide us with a detailed list of the types and values?)
- a default handling on the TeX side that would just take all the modifiers (in a certain order) and typeset them as they are used now in mode-modifer (a solution based on `\GreHeader`), and this solution could be overriden by users who want to typeset them in a different way...

I'm no hardcore gregorio user, so feel free to discard my opinion!

What do you think?

**Comment by henryso** [comment]
Should I make the header change that I mentioned above in anticipation of whatever @olivierberten provides or should I wait until the mode-specific headers are more clear?

**Comment by eroux** [comment]
Yes, I think it goes into the good direction! We can change the documentation afterwards to document  headers as conventions, but not mandatory

**Comment by olivierberten** [comment]
According to the Liber Usualis, modes 1,3,4,7,8 have several possible terminations:

First tone:
* D
* D²
* f
* g
* g²
* g³
* a
* a²
* a³

Third tone
* b
* a
* a²
* g
* g²

Fourth tone
* g
* E
* c
* A
* A*

Seventh tone
* a
* b
* c
* c²
* d

Eight tone
* G
* G*
* c

But I have no idea whether that's completely exhaustive...

![Liber Usualis, Solesmes, 1961, p. 113](http://gregobase.selapa.net/sources/3/224.png)
![Liber Usualis, Solesmes, 1961, p. 114](http://gregobase.selapa.net/sources/3/225.png)
![Liber Usualis, Solesmes, 1961, p. 115](http://gregobase.selapa.net/sources/3/226.png)
![Liber Usualis, Solesmes, 1961, p. 116](http://gregobase.selapa.net/sources/3/227.png)
![Liber Usualis, Solesmes, 1961, p. 117](http://gregobase.selapa.net/sources/3/228.png)

**Comment by jakubjelinek** [comment]
On Tue, Jan 12, 2016 at 12:02:19PM -0800, Olivier Berten wrote:
> According to the Liber Usualis, modes 1,3,4,7,8 have several possible terminations:

Antiphonale Monasticum, pp 1210-1222 lists these:

> First tone:
> * D
> * D²
> * f
> * g
> * g²
> * g³
> * a
> * a²
> * a³

D, D*, D2, a, a2, a3, f, g, g2, g3, g4, g5

Secondus modus is depending on transposition either D (with (f3) clef) or
A (with (c3) clef) and has also D* and A* terminations for solemn tone.

> Third tone
> * b
> * a
> * a²
> * g
> * g²

a, a2, a3, b, g, g2

> Fourth tone
> * g
> * E
> * c
> * A
> * A*

E, E2, d, d2, a, g, E*, E2*
and quartus alteratus has
A, d, c, A*

Quintus modus

a, g

Sextus modus again depending on clef (either (c4), then F, or (c2), then C).

> Seventh tone
> * a
> * b
> * c
> * c²
> * d

a, c, c2, d
> 
> Eight tone
> * G
> * G*
> * c

G, G2, a, c

Tonus peregrinus, Tonus irregularis and directum have just single
termination each.

	Jakub

**Comment by olivierberten** [comment]
You can see samples of tones II*, IV*, C, D, E from AM2005 as well as some other exotic tones on [this thread at MusicaSacra](http://forum.musicasacra.com/forum/discussion/9137/psalm-tones-besides-the-usual-ones). So I think limit modes to 1-8 is definitely not enough...

**Comment by henryso** [comment]
The modes (as listed in the Liber Usualis) do not have several possible terminations.  The psalm tones do because they lead into the antiphon, which may not start on the final of the mode.  So is the text above the initial the mode or is it the psalm tone that you are to use?  Or is it something else?

**Comment by olivierberten** [comment]
Good point. But, since I'm far from a specialist, how does Tonus Peregrinus relate to modes, for instance?

And obviously, Solesmes puts the psalm tones rather than the modes...

**Comment by igneus** [comment]
"So is the text above the initial the mode or is it the psalm tone that you are to use?"

For antiphons, mode + termination of the psalm tone ("differentia"). For other types of chants, mode only.

**Comment by henryso** [comment]
Now that we have a better feeling for what that text is, how should we break it up into sections?  If we will continue to use the mode header for this, how do we change it to support everything?  Do we continue to translate Arabic numerals to Roman?  How do we do this considering its current use (backwards compatibility)?

**Comment by igneus** [comment]
For me it would make sense to
1. leave `mode` as it is, but allow non-numeric values - these would never be translated to something else.
2. introduce `mode-modifier` for transported and other derived modes
3. introduce another header field for the psalm tone ending (in Latin it's commonly called `differentia`, but I will have to look for the proper English name). Only antiphons would make use of this one.

**Comment by henryso** [comment]
Do we still try translate Arabic numbers to Roman numerals?  Do we try to translate `2*` to `II*`?  Or is `*` actually the `mode-modifier`?

I think it would be fine to call the psalm tone ending header `differentia` or `mode-differentia`.

How should the differentia be formatted?  Currently, we do:
- `mode` in small caps
- followed by `mode-modifier` in italics (separated by a space)

If `*` is to be a `mode-modifier`, should we suppress the space if the `mode-modifier` starts with `*`?

**Comment by igneus** [comment]
Unfortunately I don't understand the "new Solesmes chant theory" enough to say if II* is rather a separate mode or a modified mode II. But for practical purposes rule "translate any leading number to Roman numeral, leave the rest" seems OK.

**Comment by henryso** [comment]
Looking at the pictures, `II*` and `IV*` appear to be variants of `II` and `IV` that change the dominant to the "other side" of the unstable half-step compared to the older tradition, `II*` to a minor fourth above the final (instead of a minor third) and `IV*` to a minor third above the final (instead of a minor fourth).  I think these tones attempt to be more sensitive to the time in which the given antiphon was composed.  As time passed, intervals became more and and more modern so I'm guessing that these melodies, while still plagal and retaining their finals, exhibited a shifted dominant, which Solesmes wanted to match with these psalm tones.

That said, it's very much in the grey area whether this is `mode` or `mode` plus `mode-modifier`.  From a practical perspective, I agree with your suggestions of "translate any leading number to Roman numeral, leave the rest".

We still need to agree on how to typeset the three portions by default: `mode`, `mode-modifier`, and `mode-differentia`.  Should it be:
- `mode` with initial Arabic numeral translated to Roman numeral, in small caps
- followed by `mode-differentia` in italics(?) (and separated with a space)
- followed by `mode-modifier` in italics (and separated with a space)

Or does `mode-differentia` come after `mode-modifier`?

**Comment by jakubjelinek** [comment]
mode in Roman numerals, followed by mode-modifer (without space in between, at least if modifier is *), followed by small space and then mode-differentia.
So like:
IV* e
VIII g
VI F
etc.

**Comment by henryso** [comment]
And if mode modifier is `t` for transposed?

IV t e

**Comment by henryso** [comment]
What is our policy on user-redefinition of GregorioTeX-supplied macros?  It would seem most flexible to call `\GreMode` with three arguments, with the default being whatever we define here, but I know we've been moving to using styles instead of redefining macros for styling.

**Comment by jakubjelinek** [comment]
E.g. in Antiphonale Romanum 2002, I see 2 line annotation:
VII a
transp.
where transp. is smaller and in italic.

**Comment by olivierberten** [comment]
Since the first purpose of that `modifier` header was actually transposition, why not just add `mode-transposed` (yes|no)?

And keep the \* in the `mode` header.

That said, it seems tone II\* used to be called *IV A* or *quartus modus alteratus*, so I wonder if its mode should be set to 4 or 2...

**Comment by jakubjelinek** [comment]
Comparing II* mode in AROM2002, p. 739 and Quartus modus alteratus in AMON34, p. 1215, shows different initio, the rest is indeed the same (and II* mode has also transp. variant with (f3) clef instead of (c3)).  II* starts (i)(hi)(i)... while IV alteratus, typeset in AMON34 in italics, say italic IV A, starts with (f)(hi)(i)...

**Comment by henryso** [comment]
The feature we are designing here is something that will be suppressed if there is an annotation header in gabc, which will further be suppressed should `\greannotation` be used in TeX.  So it's the default of the default.

I don't want to adopt the Antiphonale Romanum 2002 style noted by @jakubjelinek because that is much too specific to one way of doing things.  I suggest, if you want to do something like that, use your own headers, capture them, calling `\greannotation` appropriately.

Let's come up with something simple, relatively generic, and typeset in some way *by default*.  There are, after all, two ways to override it.

Thus, my suggestion is
- `mode`, using @igneus's suggestion of converting any initial Arabic numeral to Roman (thus `2*` would become `II*` and `4 A` would become `IV A`).  This would be typeset in small caps as it is currently.
- followed by `mode-differentia` as supplied in gabc, typeset upright, separated by from `mode` by a space.
- followed by `mode-modifier` as supplied in gabc, typeset in italics, separated from whatever precedes it by a space.

If `mode` is left out, nothing will be typeset.  `mode-differentia` and `mode-modifier` are both optional.

This would be done by the `\GreMode` macro, which can be overridden to do whatever the user wants (provided this is not against our redefinition policy).

This is obviously not going to satisfy everyone, but is it a reasonable default?  If the user wants something more elaborate, like putting `transp.` on a separate line in a smaller font, they can either use the `annotation` header or capture their own custom headers for custom typesetting.

**Comment by igneus** [comment]
"but is it a reasonable default?"
I don't think so. Mode and mode modifier should be printed together (as in every printed antiphonal I have ever seen) - they together describe the mode. Differentia should come at the end, after the mode description.

So: "II* d", not "II d *"; "IV t A", not "IV A t"

**Comment by henryso** [comment]
Ok, so if we switch `mode-modifier` and `mode-differentia` around, is *that* a reasonable default?

**Comment by igneus** [comment]
For me - yes.

**Comment by jakubjelinek** [comment]
For me too, if the headers can be easily queried from TeX or lua.

**Comment by henryso** [comment]
@jakubjelinek All the headers are now (in 4.1) passed from gabc to TeX.  You can use the `\gresetheadercapture` command to send specific headers to specific macros.

**Comment by rpspringuel** [comment]
> What is our policy on user-redefinition of GregorioTeX-supplied macros? It would seem most flexible to call \GreMode with three arguments, with the default being whatever we define here, but I know we've been moving to using styles instead of redefining macros for styling.

Personally I'm opposed to relying on people redefining commands to get something done.  There's no way we can prevent people from doing it, but redefining commands requires some knowledge of the package's internals in order to avoid creating problems and thus should be reserved for advanced users.  Common things which we expect novice users to want to customize should be provided with commands that allows them to that in a straight forward manner.  That was the point of shifting to the style system.

Now, to what extent this qualifies as something particular to an advanced user or something a relative novice might want to do, I leave to others.  I just wanted to weigh in on this aspect since the style system was my initiative.

**Comment by henryso** [comment]
@rpspringuel Given three inputs (this being the case here), I want to allow the user to order them in any way they like.  Do you have any suggestions for the best way to allow them to do this?

**Comment by rpspringuel** [comment]
There are just 6 ways to order 3 inputs when all are included.  Adding the ability to omit some of them increases the number of possible cases a bit, but not beyond reason.  A fairly generic internal using a `\gre@count@modeorder` flag to specify the order sequence and a `\ifgre@showmodea`, `\ifgre@showmodeb`, and `\ifgre@showmodec` boolean flags to specify which of the three should be shown would look like this:

```
\ifcase\gre@count@modeorder%
  %case 0 = abc
    \ifgre@showmodea...\fi%
    \ifgre@showmodeb...\fi%
    \ifgre@showmodec...\fi%
  \or %case 1 = acb
    \ifgre@showmodea...\fi%
    \ifgre@showmodec...\fi%
    \ifgre@showmodeb...\fi%
  \or %case 2 = bac
    \ifgre@showmodeb...\fi%
    \ifgre@showmodea...\fi%
    \ifgre@showmodec...\fi%
  \or %case 3 = bca
    \ifgre@showmodeb...\fi%
    \ifgre@showmodec...\fi%
    \ifgre@showmodea...\fi%
  \or %case 4 = cab
    \ifgre@showmodec...\fi%
    \ifgre@showmodea...\fi%
    \ifgre@showmodeb...\fi%
  \or %case 5 = cba
    \ifgre@showmodec...\fi%
    \ifgre@showmodeb...\fi%
    \ifgre@showmodea...\fi%
  \else\gre@bug...%
\fi%
```

One would then need at least 1, possibly 4, `\greset...` macros to change the flag settings.

However, I'm not sure that we need to be that generic here.  It seems that there may be some reasonable rules which can be applied to these fields which reduces the number of cases.  For instance, doesn't `mode` **always** come first?

**Comment by rpspringuel** [comment]
Oh, and it should be pointed out that if one wants the mode number to be in small caps, then the text representation should use lowercase roman numerals not uppercase (i.e. `iii` instead of `III`).  Right now `\GreMode` uses uppercase, while the default style is for small caps.  One of those needs to be changed.

**Comment by henryso** [comment]
The "down-casing" of the Roman numerals brings up an interesting problem: what if the user changes the style of `mode` to *not* use small caps?

**Comment by rpspringuel** [comment]
Well, if the user wants capitals but not small caps, they have a couple of options:

1. As I mentioned in #589, [the answer to this question](http://tex.stackexchange.com/questions/100336/towards-a-ucshape-and-textuc-command-for-uppercase-text-xetex-luatex) provides a method for creating a `\ucshape` command which can be used in place of `\scshape` in the style for the mode.  This will force the Roman numerals to use regular uppercase letters.
2. I've recently discovered the [environ package](https://www.ctan.org/pkg/environ?lang=en) which provides an alternative syntax for defining environments.  With this syntax it is possible to define a simple uppercasing environment as `\NewEnviron{ucase}{\MakeUppercase{\BODY}}`.  This can then be used in the style definition for the mode to force the letters to uppercase.

We decided before not to include the `\ucshape` command in GregorioTeX (as being outside the scope of the package).  Perhaps we should revisit that decision or at least include links in the documentation to these two options?

**Comment by henryso** [comment]
This comment is going to be a bit of a mess because I don't have it clear in my head, but here goes:

I was actually considering something like `\ucshape`, but, as you know, people do very strange stuff when you let them,  so for example, let's say for whatever reason, they decide `mode` should be `6b`.  They don't want small caps, but rather that this be printed as `VIb`.  Do we chalk stuff like this up to "use annotations, instead"?  Further, since people typically see Roman numerals as capitals, might it be better to actually render Arabic numbers as capitals and then do the "down-casing" in the style (i.e., the opposite of `\ucshape`)?  But then you'd run into problems where people want to render `6A` as `ivA`  in small caps.

The only "clean" answer I can come up with is to define `\GreRomanI`, `\GreRomanII`, and so on.  Then have a macro which redefines these as lower case Roman numerals or uppercase Roman numerals or Arabic numerals, with the default being lower case Roman numerals meant to be used with the default small caps style (or perhaps upper case, for backwards compatibility).  gregorio (the program) would translate any initial Arabic numerals to these macros before passing to `\GreMode`

Is that a bad idea?

**Comment by rpspringuel** [comment]
Hmm... I don't think that `\GreRomanI` etc. is the way to go (it just seems cumbersome), but the suggestion got me thinking of the `\Roman` and `\roman` command which LaTeX provides for formating counters.  Some quick searching shows that these are based on the TeX primative `\romannumeral` which takes, surprise surprise, a numeric argument an produces the lowercase roman numeral equivalent (i.e. `\romannumeral 3` produces `iii`).  Perhaps then the way to do this is to **not** convert to roman numerals when passing to `\GreMode` but rather pass the Arabic number and then use a command TeX side to convert that to roman numerals on the spot (the primative for lower case, something based on it for uppercase).

**Comment by henryso** [comment]
How about this, then: if the first character of `mode` is an Arabic numeral from 1-8, it gets converted to `\GreModeNumber{x}` before being passed to `\GreMode`.  Then we have a configuration that causes `\GreModeNumber` to convert it in some way.  The implementation details can thus be left in TeX.

**Comment by rpspringuel** [comment]
I think that could work.  It would require us to define one internal (a capitalizing equivalent to `\romannumeral`) and then have a setting which aliased `\GreModeNumber` to either our internal or the primitive (or `\relax` if the user wanted Arabic numbers for some reason) as desired.  That's a whole lot less code for us to maintain and it should be fairly straight forward.

**Comment by henryso** [comment]
If I `\let\GreModeNumber\romannumeral`, when I try to use it as `\GreModeNumber{6}`, TeX tells me that the `{` is not a number, so I think we'll need to create a simple wrapper for lowercase Roman numeral.

**Comment by rpspringuel** [comment]
That's unexpected, but not a terribly big deal.  Indeed, in some respects it makes things more consistent:

```
\def\gre@romannumeral#1{\romannumeral #1}%
\def\gre@Romannumeral#1{\MakeUppercase{\romannumeral #1}}%
```

**Comment by henryso** [comment]
Well, besides the fact that `\MakeUppercase` doesn't work in plain TeX, I'll be doing something like that.

**Comment by rpspringuel** [comment]
I forgot that was a LaTeX specific command.  In that case what you need is `\uppercase\expandafter{\romannumeral #1}`

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by henryso** [comment]
As pointed out by @rpspringuel, we currently use bold and small caps (by default) for the mode number, but we are using upper case Roman numerals.  What should I do about this?  There are numerous options, but the two that seem most obvious (as also mentioned by @rpspringuel):
1. Keep using upper case, but only use the bold style for the mode number.  This is the backwards compatible option.
2. Use lower case Roman numerals and continue to use bold and small caps for the default styling.  This will break scores since the Roman numerals would then actually be in small caps.  This might be a better expression of the *intent* of the styling that we have had in place.

Finally, how should the `mode-differentia` be styled?  Just bold?

**Comment by eroux** [comment]
I think option 2 is better, but I don't have a very strong opinion, and bold seems fine for `mode-differentia`

**Comment by henryso** [comment]
N.B. I have changed my mind about implementing arbitrary ordering of the mode parts until someone actually asks for that feature.  If implemented as specified by @rpspringuel, it seems a fairly compartmentalized change, but there's no need to implement stuff that no one will be using.

**Comment by henryso** [comment]
If anyone has any further comments on #785, please let me know; otherwise I will merge the pull request and re-close this issue tonight.
