### ISSUE TITLE
switch to align annotation top with top of lines

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#768]
Most people I know who use Gregorio want to align the top of the annotation with the top of the lines. Not all obviously, but I think it would be easier for them if there was an option for this, especially since if you have only one line of annotation (which most new users will have at the beginning), the current default state looks a bit odd...

**Comment by henryso** [comment]
I have forgotten why this change was made in the first place.  Also, perhaps a second annotation should push the first one up?

**Comment by eroux** [comment]
I thought about that, I discarded the idea because I thought this would make the configuration too complex... But on second thoughts, that seems good, I think we should do that indeed!

**Comment by rpspringuel** [comment]
I made the change when rewriting the annotation algorithm because in my experience the exact opposite was the case.  If you're encountering those who want it otherwise, then clearly it seems like a good idea to have the option for both.  This should be as simple as adding a boolean flag and making the execution of what is currently line 513 in `gregoriotex-main.tex` dependent on the value of that flag.

It's considerably less simple to change things when the second line is added since the annotation box is built recursively through the same function: `\gre@annotation`.  As is, we know that if the box was empty prior to the call of `\gre@annotation` then we're putting the first line into the box.  After that, the box is not empty and we simply are adding a line.  This doesn't differentiate between the added line being the second, third, fourth, etc.  As a result it would be fairly easy for all subsequent annotations to raise the box slightly, but if we want to differentiate so that only the second annotation does this, then things get slightly more complex.

**Comment by henryso** [comment]
An option does make sense, then.

As for pushing up the box, we only reasonably support two annotations (maybe three), so I think it's OK if all additional annotations push raise the box if this option is selected.

**Comment by rpspringuel** [comment]
Then how about the following options:

`\gresetannotationby{firstline|lastline}`

and

`\gresetannotationvalign{top|baseline|bottom}` (note `bottom` and `baseline` are the same unless the annotation contains letters with descenders like y, g, q, etc.

Current behavior would be `\gresetannotationby{firstline}\gresetannotationvalign{baseline}`.  The behavior being requested would be `\gresetannotationby{firstline}\gresetannotationvalign{top}`.

**Comment by eroux** [comment]
Sounds good!

**Comment by henryso** [comment]
What would `\gresetannotationby{lastline}` do?

**Comment by rpspringuel** [comment]
It would make the last line of a multi-line annotation the controlling line.

**Comment by henryso** [comment]
Thanks.  Your proposed settings make sense to me.

**Comment by rpspringuel** [comment]
In working on this I have discovered a potential bug in the current functionality of annotations.

Take a look at tex-ouput/bugsfix-508.  The second example in that test doesn't actually have the two annotations touching.  After some fiddling, it seems there are two problems:

1. Despite the use of `\offinterlineskip` TeX is introducing a 0.1em space in between the boxes when assembling the new annotation box
2. If one reduces the spread by said amount, there is still space between the lines because they are `\scriptsize`.  If one uses normal size text, then the annotations do touch, as expected.  This implies that the height of the bottom box is not the actual height of the visible text, but something a bit taller (it doesn't appear to be the full height of the font).  Experimentation shows this to be a problem with `\tiny` and `\footnotesize` too.  `\small` actually shows some overlap between the two lines.

The first is easy to fix, I just reduce the spread amount when marrying the two boxes together (in fact, I've already done this in my local working copy).  The other, however, is a harder fix because it will require looking inside the box to determine something about the font size of its contents and then applying a fontsize dependent fix.  Does anyone think it's worth me looking into it further to try and fix the problem, or should we identify it as a known bug and just put a warning in the documentation about the unexpected behavior?

**Comment by eroux** [comment]
About `1.`, `\offinterlineskip` doesn't seem to set `\parskip` to 0, maybe that's the problem?

About `2.`, maybe the problem is with the second argument of `\fontsize`? If it is, it's more a feature than a bug...

**Comment by rpspringuel** [comment]
1. Explicitly setting `\parskip` to 0pt within the annotation box doesn't fix the problem.

2. Using `\fontsize` doesn't fix the problem, regardless of the value of the second argument.

**Comment by rpspringuel** [comment]
In trying to work out a MWE I've been able to get an assembly of boxes which behaves as expected, but I've yet to figure out exactly what the important difference between the simplified structure that works and the functional macro.  I've asked [on LaTeX-community](http://latex-community.org/forum/viewtopic.php?f=44&t=27041) for some help figuring this out.

**Comment by eroux** [comment]
Ok, good idea. I don't know about LaTeX-community, but I know [tex.stackexchange](http://tex.stackexchange.com/) has some high-level gurus answering questions, so it might help in case LaTeX-community doesn't

**Comment by rpspringuel** [comment]
There's some crossover between the two and I've had success in both venues in the past.  If I don't get a response in the course of a few days, I'll cross post on TeX-stackexchange.

**Comment by rpspringuel** [comment]
Bugs solved, though without any help from my posting.  Sometimes you just have to wipe the slate clean and start all over again.

I'll document the changes and post the PR tomorrow (I'm sick and don't want to be up too late tonight).
