### ISSUE TITLE
alteration below staff lines

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#790]
It seems alterations below staff lines could be improved, see for instance this result:

[bubug.pdf](https://github.com/gregorio-project/gregorio/files/93597/bubug.pdf)

from

```
name: test;
%%
aaa(axZ)aaa(gxg)
```

- the flat should be taken into account by the text-staff lines separation space algorithm (so that it doesn't eat the text
- there should be a ledger line around it

**Comment by henryso** [comment]
I can work on this, but before I go down the wrong path, any objections to me treating alterations as note shapes rather than a special type of glyph?

**Comment by eroux** [comment]
Do you mean in the C code or in TeX? As long as end-user behavior is the same, I'm fine with both options

**Comment by henryso** [comment]
If you take a look at https://github.com/gregorio-project/gregorio-test/blob/master/tests/gabc-output/glyphs/accidentals.pdf, you'll see that (ggxgh) places the flat right up against the initial punctum.  Is the the desired behavior?  It might be fine because, if the flat is on a higher note, it probably looks OK.  I'm just checking before I try harder to retain this behavior.

**Comment by eroux** [comment]
That's a good question... I admit I'm a bit puzzled about the best way to deal with this... Maybe the current behavior leaves the user all the possibilities (adding a space by hand or keeping the flat close if it looks fine)... But I let you (or others) choose

**Comment by henryso** [comment]
I left the behavior mentioned earlier as-is, as it's probably fine in the "normal" case as opposed to `(ggxg)`, which is probably very rare if it actually exists somewhere.
