### ISSUE TITLE
-g -O2 in CFLAGS?

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#821]
See [this comment](https://github.com/gregorio-project/gregorio/issues/697#issuecomment-174176208): `./build.sh` does not add `-g -O2` to `CFLAGS`. 

A first guess was that we should call `AC_PROG_CC` instead of `AC_PROG_CC_C89`, the latter being called by the former according to [the manual](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/C-Compiler.html). But using `AC_PROG_CC` doesn't seem to fix the issue...

**Comment by jakubjelinek** [comment]
Ah, the problem is in build.sh, which does:
CFLAGS="$CFLAGS -Wdeclaration-after-statement"
CFLAGS is usually just unset when running build.sh, and by running ./configure with CFLAGS=" -Wdeclaration-after-statement" you override the automatic detection of what CFLAGS should be used.
IMHO that line should go from build.sh, it is not portable anyway, not all compilers support -Wdeclaration-after-statement.  Instead, some autoconf check for whether -Wdeclaration-after-statement is supported should be added and if it is supported, it should be added to the CFLAGS.  If that happens after AC_PROG_CC*, then you should be fine.
