### ISSUE TITLE
differenciate glyph of punctum inclinatum for ascendens figure

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#856]
The current output of puncta inclinata ascendens with greciliae is not really satisfactory:

![inclinata](https://cloud.githubusercontent.com/assets/60868/12703090/0fc2470c-c83a-11e5-8164-97821a97c3e3.png)

the reason is that the shape of the punctum is tuned to look nice in descendens figure. It would be good to be able to tune it for ascendens too.

I think it's not necessary to tune deminutum or ascendens forms as they shouldn't appear in ascendens figures. When there is a kind of ambiguity (only one punctum, etc.), the descendens figure should be taken.

**Comment by henryso** [comment]
This is what it looks like on my system (4.1):

![image](https://cloud.githubusercontent.com/assets/421318/12703157/174c05a6-c80a-11e5-8477-e13f0dc3980e.png)

Is the problem the spacing after the punctum inclinatum and the virga that follows?  Or is the "angle" of the diamond shape?  Or is it something else?

**Comment by eroux** [comment]
Hmm, sorry, I used a tune spacing that makes it completely off... you result is much better! Well, I think we can still do this, rotating the shape clockwise so that we can have the same angle as the descendens figure, but that's not really the most important feature...

**Comment by henryso** [comment]
Ok, so to be clear, this issue is that we need an alternate glyph for the punctum inclinatum in an ascending figure.  Can this be post-4.1?  I would like to concentrate on the test coverage and the bugs it's uncovering.

**Comment by eroux** [comment]
It can definitely be post-4.1 indeed. Maybe we could create a milestone?

**Comment by henryso** [comment]
There's already a 5.0 milestone for the next release.

**Comment by henryso** [comment]
A few questions:
- If we change the shape for ascending vs. descending puncta inclinata, won't it look funny if you have a descending string followed by an ascending string (or vice-versa)?
- In that case, would you then need to be able to override the automatic choice made by gregorio (similar to the oriscus)?
- I assume the default, for a punctum inclinatum all by itself, should be the descending shape.  Is that correct?

**Comment by eroux** [comment]
For 1., I admit I have no answer, I think this should be very rare, but when it happens I don't know... if you start to work on that, could you show an example of such a figure?

For the override, I was thinking about a global one with glyph substitution, but an override in gabc would be nice yes!

For 3, you are correct

**Comment by henryso** [comment]
This is a mock-up (created using an image editor) of what I mean by ascending followed by descending looking a little funny:

![image](https://cloud.githubusercontent.com/assets/421318/14224036/d2807f92-f85b-11e5-9da8-97bb2368bbd7.png)

and, more obvious if there's no virga:

![image](https://cloud.githubusercontent.com/assets/421318/14224066/f208dbd8-f85c-11e5-9bc6-3bd0d7b31587.png)

**Comment by eroux** [comment]
I think it might be a bit too tilted... Anyway, in the case of trigonus like `(GHG)`, the same glyph should be used (the current one), and maybe in your super trigonus (quintonus?) too... But I think you're on good tracks!

**Comment by henryso** [comment]
The algorithm for this will be rather complicated then.  I think I'll work on the other one and come back to this.

**Comment by eroux** [comment]
sure, no emergency!

**Comment by eroux** [comment]
Solesmes finally agrees to use this for their font too. Instead of rotating the glyph, they just mirror it, which I think is quite a good idea, it just didn't cross my mind!

**Comment by henryso** [comment]
In the sample image, I simply mirrored the shape.  I haven't gotten any further on implementation, though.

**Comment by eroux** [comment]
No problem, I told them it would not be in 4.2

**Comment by henryso** [comment]
How does this algorithm look?

```
SET previous ← nil
SET first ← nil
SET directon ← nil
SET running ← 0
FOR each note in the score
  IF note is non-inclinatum or determined inclinatum THEN
    IF first ≠ nil THEN
      IF note is determined inclinatum THEN
        SET direction ← direction of inclinatum
      ELSE-IF running > 0 THEN
        SET direction ← ascending
      ELSE
        SET direction ← descending
      END-IF
      FOR each note-to-change from first until previous
        SET direction of note-to-change to direction
      END-FOR
      SET first ← nil
      SET running ← 0
    END-IF
    IF note is non-inclinatum THEN
      SET direction ← nil
    END-IF
  ELSE // current is undetermined inclinatum
    IF direction ≠ nil THEN
      SET direction of note to direction
    ELSE
      IF first = nil THEN
        SET first ← current
      END-IF
      // any cases not covered below will not change running
      IF previous ≠ nil THEN
        IF note is ascent from previous THEN
          increment running
        ELSE-IF note is descent from previous THEN
          decrement running
        END-IF
      END-IF
    END-IF
  END-IF
  SET previous ← current
END-FOR
```

I can either use the current punctum space cases flipped for the ascending shape (which assumes the figure is exactly flipped horizontally) or create 15 (or so) new spaces to cover the spacing requirements of the ascending figure.  I think it's probably better to do the latter, but then the already confusing names become even more confusing.  Should I rename the current 15 (or so) spaces to make everything consistent?

We currently have:

* `punctuminclinatumshift`
* `ascendingpunctuminclinatumshift`
* `beforepunctainclinatashift`
* `punctuminclinatumanddebilisshift`
* `ascendingpunctuminclinatumanddebilisshift`
* `punctuminclinatumdebilisshift`
* `punctuminclinatumbigshift`
* `ascendingpunctuminclinatumbigshift`
* `punctuminclinatummaxshift`
* `ascendingpunctuminclinatummaxshift`
* `descendinginclinatumtonobarshift`
* `descendinginclinatumtonobarbigshift`
* `descendinginclinatumtonobarmaxshift`
* `ascendinginclinatumtonobarshift`
* `ascendinginclinatumtonobarbigshift`
* `ascendinginclinatumtonobarmaxshift`

... and this is just for the current shape, which will, after this change, be considered the descending shape.  However, because groups of puncta inclinata retain the same shape regardless of whether they are physically ascending or descending, descending *and* ascending spaces are needed for both the descending and the ascending glyph.  Are you confused yet?  Any suggestions on the names?  Any suggestions on deprecation technique?

**Comment by eroux** [comment]
The algorithm looks good, though i'm not totally sure I understand what `determined inclunatum` means... Also, what does it give for `GHG`, ascending or descending?

For the spaces I didn't realize the problem... well... I think the best may be to keep the new shape only for stricttly ascending figures, and for the current shape, there could be only one space for ascending figure, which would be used for all ambitus: `GHG` is already quite rare (not used by Solesmes anymore), I doubt one can find `EHG`... What do you think?

**Comment by henryso** [comment]
As for `determined inclinatum`, since this is a heuristic algorithm, the heuristic can be wrong, so my intent was to implement `G0` and `G1` to force the desired figure, so `G` is an undetermined inclinatum and `G0`/`G1' in a determined inclinatum.  For `GHG`, it depends on the surrounding notes, if any.  If there are no surrounding notes, it gives descending.  This leads me to realize that the algorithm above is *not* taking into account the note after a string of puncta inclinata in determining direction, which I had intended, and also does not handle the case of a punctum inclinatum as the final note.

When you say one space for an ascending figure, you mean `GHJ` would use the same space between `G` and `H` as between `H` and `J`?  That doesn't sound right.

**Comment by eroux** [comment]
Ok, I understand the `determined` part, thanks! Ok for `GHG` too. In your algorithm you only take surrounding notes if they're not separated by a space right? 

For `GHJ` one would use spaces like `ascendingpunctuminclinatumbigshift`, etc. because it's all ascending with ascending glyphs, this is a simple case that we can already handle with our spaces. `EHG` is a different case, as the `EG` part is ascending notes with descending shapes, but there could be only one space for that, no need to dissociate between ambitus... What do you think?

**Comment by henryso** [comment]
The intent of my algorithm was actually to ignore spaces during determination.  It's a rough heuristic anyway, and we can tune it if it proves more incorrect than correct.

I misunderstood your suggestion with the spaces, but I think I understand now.  This means that figures moving opposite from their glyph direction with an ambitus greater than one will not align in a visually pleasing fashion.  As long as you are fine with that, then we only need two additional spaces.

**Comment by henryso** [comment]
Note: I updated the algorithm above.

**Comment by eroux** [comment]
That's what I'm suggesting indeed, thanks!

**Comment by henryso** [comment]
How should I deal with liquescence?  I suppose for deminutus, I can just flip the current deminutus figure, but how about auctus?  Flipping the current auctus figure would look incoherent since the "drop" will flow to the right, which is different than all the other glyphs.

**Comment by eroux** [comment]
I don't think these really need to be flipped... Would it be a problem if they're not? (In real use cases)

**Comment by henryso** [comment]
It'll just make coding it less orthogonal, but that's not an issue.

**Comment by henryso** [comment]
I'm close to completing this, but the result of the above algorithm in some cases is too wrong, so I'm tuning the algorithm and it will surely not exactly match the above.

**Comment by henryso** [comment]
This is about ready.  I just need to document the TeX changes.  Should I check this into release-4.2 or develop?

**Comment by eroux** [comment]
Thanks a lot! Well... if it's ready I don't see any reason not to add this to 4.2... What do you think?
