### ISSUE TITLE
Euouae block features

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#9]
Euouae blocks have several features that can be different from other parts of the score. Among which:

 * no line breaking
 * different spacing

There should be a `<euouae>` (or `<eu>`?) markup in gabc so that these can be automated without ugly TeX inside gabc. Or maybe gregorio should detect it automatically? Would be feasible.

Gregorio should also not break line before the last syllable before the Euouae, and keep the main score and the euouae block on the same page.

**Comment by eroux** [comment]
I admit I don't really know how to end this feature, the C part is done, but on the TeX side, I'm not sure about the best way to implement it.

The main idea is to allow users to change spacing between euouae blocks and the rest of the sore. I thought about different ways of doing this:

- the very supple way: defining `\AtEUOUAEBeginning` and `\AtEUOUAEBeginning` with reasonable defaults, and let the user change it if he wants
- the more rigid way to define a few additional spaces like `interwordspacetextnotes@euouae` that would be used in euouae blocks
- the overkill way, to redefine a `gsp-euouae.tex` with different spaces and switch at each euouae block

@rpspringuel , you're the one who knows spacings best, what do you think? What would be the best way to do that? There would be only few horizontal spaces (around 10) impacted by the euouae blocks.

**Comment by rpspringuel** [comment]
My inclination would be to define extra spaces (option 2) as then manipulating these spaces will be consistent with the way other spaces are handled and thus easier on the user.

Options 1 and 3 would both require either an alternative method for manipulating these distances specifically, or a rewrite of the code for manipulating distances so that it could access these alternate storage locations.

The trick is figuring out how to swap back and forth between the "normal" distances and the "euouae" ones.  In this regard, options 1 and 3 actually have something to recommend them here, as they could handle this switch fairly easily.

Oh, and it should be noted that a `gsp-euouae.tex` file need not redefine every distance.  It could just redefine those distances which are effected by the block.  Since we automatically load the default as part of package loading, a partial `gsp-euouae.tex` file would automatically inherit from the default those distances which it doesn't define itself.

**Comment by eroux** [comment]
Ok, let's go for this solution then. In https://github.com/gregorio-project/gregorio/commit/c2015160395ce5a381b04a605c3eb595c9245248 there is already a `\greendeuouae` and `\grebegineuouae` for this switch. What would be their best definition in order to make Gregorio use `interwordspacetextnotes@euouae` instead of `interwordspacetextnotes`? Once there is a mechanism for one space, others should follow easily.

**Comment by rpspringuel** [comment]
There are three options here:

1. `\grebegineuouae` and `\greendeuouae` can set a simple boolean switch.  Then within the code where `interwordspacetextnotes` is used, set up a conditional that will check the value of that switch and use `interwordspacetextnotes` or `interwordspacetextnotes@euouae` as appropriate.  The advantage here is that the code where the distance is used will be explicit that there's a choice going on based on whether we're in a `euouae` block or not.  The disadvantage is that this requires a bunch of conditionals to be inserted into the code and probably has more overhead as a result.
2. We create a `current@interwordspacetextnotes` register which is used in the spacing code.  The value of this register defaults to `interwordspacetextnotes`.  `\grebegineuouae` would set it to `interwordspacetextnotes@euouae` and `\greendeuouae` would set it to `interwordspacetextnotes`.  This solution avoids running an if...then...else sequence each time the distance is used, but also hides, some what, how `current@interwordspacetextnotes` is determined.

**Comment by eroux** [comment]
I was thinking about something more straightforward, but I don't know if it's possible or not:

in grebegineuouae:
- set interwordspacetextnotes@noneuouae to current value of interwordspacetextnotes
- set interwordspacetextnotes to interwordspacetextnotes@euouae

in greendeuouae:
- set interwordspacetextnotes to interwordspacetextnotes@noneuouae

Would that be feasible? That would be the less intrusive way of doing this...

**Comment by rpspringuel** [comment]
I thought about that option (indeed, I'd initially formulated option 2 in that manner) but decided against it because the spacing code would suggest that we're always using `interwordspacetextnotes` (which is explicitly defined in `gsp-default.tex`) even though it's been changed behind the scenes.  By changing `interwordspacetextnotes` to `current@interwordspacetextnotes` in the spacing code, I can immediately tell that I may not be using `interwordspacetextnotes` as defined in `gsp-default.tex` (or a custom configuration) and know to look for the places where `current@interwordspacetextnotes` is defined to figure out what value the distance has at that moment.

Certainly this would be a far less intrusive change to the code (most of the changes would be inside `\grebegineuouae` and `\greendeuouae`) but it also obfuscates (for me) what's actually going on and would make it harder down the road to identify and fix problems.  By reformulating it as I did, I gain some clarity in the code, without changing the computational overhead, but at the cost of a few more changes being needed in the code.
