### ISSUE TITLE
new bar algorithm not correct at end of lines

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#943]
See the examples of [this message](https://www.mail-archive.com/gregorio-users@gna.org/msg03349.html), the bars are too far from the end of the line, even with manual end of line

**Comment by rpspringuel** [comment]
The way to solve this is to move the position where the after bar penalty is imposed so that instead of placing it at the very end of the bar syllable (i.e. after we've moved the full whitespace amount which follows the bar) it occurs at the right most edge of the printed matter for the syllable (or maybe just beyond that).

Unfortunately this isn't as simple as moving it to be before the `\gre@hskip` because the text might end to the right of the bar.  We thus will need to check for that and move appropriately before imposting the penalty.  We also might need to incorporate the `eolshift` material.

**Comment by eroux** [comment]
I think the penalty should be moved as you said, and yes, integrating `\gre@calculate@eolshift` is definitely necessary

**Comment by rpspringuel** [comment]
In working on #935, I noticed another end of line error.  When manually ending a line on a bar line which has text attached the bar line and the text can get separated if a justified line end occurs in the same syllable (e.g. `text(::z)`).  This may mean bringing back one of the two line break fixes we tried (and determined weren't needed) for the earlier line break problem.

**Comment by eroux** [comment]
Ok, the fixes are not really hard, I'll make a PR when the rest will be ready. Do you have an example of such a behavior?

**Comment by eroux** [comment]
@rpspringuel will you have time to fix this before Wednesday? I'll try to work on it tomorrow if you don't.

**Comment by rpspringuel** [comment]
I've done a couple of things, but noticed a problem that should be fixed before going forward and I'm not quite sure what the best solution might be.

I have a take-home mid-term to do tomorrow, so I can't work on this again until that is finished.  The prof is only expecting about 90 minutes worth of work on it, so I should have some time later in the day.
