### ISSUE TITLE
Defining Changelog guidelines

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#99]
The changelog we have now in release-3.0 branch is extremely confusing for me, so I cannot imagine what users will understand when they'll look at it...

A few guidelines I propose (already discussed a bit [here](https://github.com/gregorio-project/gregorio/commit/29cc2e7b22801cc31405bc0c85a4c5289dc9e4c1#commitcomment-10255918). Please remember [these guidelines](http://keepachangelog.com/), and let's take an example on what I think can be considered as a good Changelog (though too big for us) [here](https://wiki.documentfoundation.org/ReleaseNotes/4.4).

A few thing I find extremely confusing in the Changelog:

 * if version 2.4.3 is yanked, why keep it in the Changelog at all? Ok, there's been confusion in the release cycle, but what does a yanked release mean? Are the changes listed in the changelog under 2.4.3 removed? Or are they in 2.4.2 or 3.0.0? If I ask myself these questions, users will... so I propose to yank it from the Changelog too, and to pass the relevant entries in 3.0.0. Also, remove "Fixed" entries if they relate to problems introduced in 2.4.3 (because it's another point that is ambiguous in the current state).
 * Changelog is for users, and something I'm 100% sure about, is that most users of gregorio will be confused about the following sentence: `Syllables were not being spaced correctly (see #79). This appears to result from the space calculations not terminating properly. There's a need for a \relax somewhere. Since the problem didn't show up in debug mode, I simply added a \else\relax to \gre@debug to eliminate the problem. We may need to go back and fix this better later.`. Apart from making people anxious, I think noone understands the technical description, and not many users (if any) care about this...
 * most entries are extremely blur from a user point of view, and users won't understand which entries impact them and which don't (which makes the changelog totally useless). Example : `Missed renaming bitristrospace.` What can it possibly mean? If you are the person who did this, of course you'll understand, but even I don't! What does it do? A more appropriate sentence would be `fixed wrong spacing in trivirga and bivirga`. Do you see the general orientation? 80% of entries are like this... Another example : the two entries `\grechangedim updated to reflect string storage of distances` and then `User settable distances now stored as strings (see #50)`. What can it possibly mean for a user? Apart from the fact that users are supposed to have read the second to understand the first (a strange literary choice); `settable distances are now stored as strings`: a user can simply not understand this. Users don't have the slightest idea what other representation distances can have in TeX, and it's definitely not relevant to them (unless they want to learn more TeX things, but that's not the point here)!

Also, if the argument is "it's for developers", try to imagine yourself in one year... what would you do of such a file? I personally won't read it, as the commit log will be much clearer. So if it's useless for users and useless for developers, maybe it's better to remove it? I would be in favor of improving it, and I prefer no Changelog than the current one, but it's up to you to decide.

**Comment by henryso** [comment]
If the features of the yanked release are in a forward release, I also don't see why it should be mentioned. However, the "Keep a Changelog" page does state that yanked releases should be mentioned. Maybe it can be reduced to a single line item that explains why the release was yanked?

I agree that bug fixes within a release are best left out of the change log.

One of the things I completely agree with in "Keep a Changelog" is that it should NOT be a repeat of the git logs.  I agree that, even for developers, what is fixed is much more important than technically how it was fixed.

**Comment by rpspringuel** [comment]
Since I'm the culprit for writing most of the confusing stuff, I very much appreciate this discussion as it'll help me clarify what needs to be in a change log and what doesn't.  Looking at what I wrote, I realize now there not even clear to me at first glance.  Given a second or two of thought, I can recall the change I made and understand what the line means, but that's going to be unique to me (or someone whose studied my commits).

On the issue of things being out of order, that would come from my practice of top posting additions.  This put the new stuff on top (within each section) and thus followed the overall pattern of the file, which had more recent releases on top.  Of course now that you point it out, I realize how that can be very confusing for someone reading the CHANGELOG for the first time.  Sometimes consistency is not a good thing.

On yanked releases, I was trying to follow the guidelines on [Keep a CHANGELOG](http://keepachangelog.com/), as @henryso pointed out.  I like his suggestion of reducing it to a line.  This would make it clear that there was a yanked release, but at the same time make it less ambiguous as to what happened to the features in that release.

I will try to revise my entries later today to make some improvements, but will probably need further revisions.
